import { QueryClient,QueryClientProvider } from '@tanstack/react-query';import { render,screen } from '@testing-library/react';import userEvent from '@testing-library/user-event';import { App as AntApp,ConfigProvider } from 'antd';import { HttpResponse,http } from 'msw';import { MemoryRouter } from 'react-router-dom';import App from '../../../../App';import { appTheme } from '../../../../app/theme/theme';import { AuthProvider } from '../../../../auth/AuthContext';import { server } from '../../../../test/server';import type { CargoManifest } from '../types/cargoManifest';
const orderId='44444444-4444-4444-8444-444444444444',lineId='55555555-5555-4555-8555-555555555555',manifestId='66666666-6666-4666-8666-666666666666';const manifest:CargoManifest={id:manifestId,manifestNumber:'CM-2026-000001',freightOrderId:orderId,freightOrderNumber:'FO-2026-000001',finalized:false,items:[],version:0,createdAt:'2026-08-25T00:00:00Z',updatedAt:'2026-08-25T00:00:00Z',createdBy:'manager',updatedBy:'manager'};const order={id:orderId,orderNumber:'FO-2026-000001',lines:[{id:lineId,description:'Pallet cargo',quantity:2}],customerId:'1',originLocationId:'2',destinationLocationId:'3',requestedPickupAt:'2026-09-01T00:00:00Z',requestedDeliveryAt:'2026-09-02T00:00:00Z',serviceLevel:'STANDARD',priority:'HIGH',version:0,createdAt:'2026-08-25T00:00:00Z',updatedAt:'2026-08-25T00:00:00Z',createdBy:'manager',updatedBy:'manager'};
function handlers(permissions:string[],value:CargoManifest=manifest){server.use(http.get('*/auth/me',()=>HttpResponse.json({id:'u',username:'manager',firstName:'Cargo',lastName:'Manager',active:true,roles:[],permissions})),http.get('*/v1/freight/manifests',()=>HttpResponse.json({content:[value],page:0,limit:10,totalElements:1,totalPages:1})),http.get('*/v1/freight/manifests/:id/readiness',()=>HttpResponse.json({ready:value.items.length>0,failures:value.items.length?[]:[{code:'UNMANIFESTED_CARGO',field:'items',message:'Pallet cargo has unmanifested quantity 2'}]})),http.get('*/v1/freight/manifests/:id',()=>HttpResponse.json(value)),http.get('*/v1/freight/orders/:id',()=>HttpResponse.json(order)),http.get('*/v1/freight/orders',()=>HttpResponse.json({content:[order],page:0,limit:100,totalElements:1,totalPages:1})));}
function renderAt(path:string){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<ConfigProvider theme={appTheme}><AntApp><QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider></AntApp></ConfigProvider>)}
describe('Cargo manifest pages',()=>{
 it('renders permission-aware paginated list',async()=>{handlers(['CARGO_MANIFEST_VIEW']);renderAt('/freight/manifests');expect(await screen.findByText('CM-2026-000001')).toBeInTheDocument();expect(screen.getByText('UNFINALIZED')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'New cargo manifest'})).not.toBeInTheDocument()});
 it('shows structured readiness and audit',async()=>{handlers(['CARGO_MANIFEST_VIEW','CARGO_MANIFEST_MANAGE','CARGO_MANIFEST_FINALIZE']);renderAt(`/freight/manifests/${manifestId}`);expect(await screen.findByText(/unmanifested quantity 2/)).toBeInTheDocument();expect(screen.getByRole('button',{name:/Add cargo item/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/Finalize manifest/})).toBeInTheDocument();expect(screen.getAllByText(/by manager/).length).toBeGreaterThan(0)});
 it('conditionally presents customs and hazardous inputs',async()=>{handlers(['CARGO_MANIFEST_VIEW','CARGO_MANIFEST_MANAGE']);const user=userEvent.setup();renderAt(`/freight/manifests/${manifestId}`);await user.click(await screen.findByRole('button',{name:/Add cargo item/}));expect(screen.queryByLabelText('Customs information')).not.toBeInTheDocument();await user.click(screen.getByRole('checkbox',{name:/Customs information applies/}));expect(screen.getByLabelText('Customs information')).toBeInTheDocument();await user.click(screen.getByRole('checkbox',{name:/Hazardous-goods information applies/}));expect(screen.getByLabelText('Hazardous classification')).toBeInTheDocument();expect(screen.getByLabelText('Hazardous details')).toBeInTheDocument()});
 it('renders finalized manifests read-only',async()=>{handlers(['CARGO_MANIFEST_VIEW','CARGO_MANIFEST_MANAGE','CARGO_MANIFEST_FINALIZE'],{...manifest,finalized:true,finalizedAt:'2026-08-25T01:00:00Z',finalizedBy:'finalizer'});renderAt(`/freight/manifests/${manifestId}`);expect((await screen.findAllByText('FINALIZED')).length).toBeGreaterThan(0);expect(screen.queryByRole('button',{name:/Add cargo item/})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Finalize manifest/})).not.toBeInTheDocument()});
 it('guards the route without view permission',async()=>{handlers([]);renderAt('/freight/manifests');expect(await screen.findByText('Select an available module from the navigation.')).toBeInTheDocument()});
});
