package com.transportlogistics.app.tracking.domain.routedeviation;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

public record RouteDeviationEpisode(UUID id,UUID tenantId,UUID vehicleId,UUID tripId,UUID driverId,UUID routeId,
 RouteVersion routeVersion,UUID ruleId,long ruleVersion,DistanceMeters configuredTolerance,DistanceMeters effectiveTolerance,
 UUID firstCandidatePositionId,UUID confirmingPositionId,Instant startSourceTimestamp,Instant confirmationSourceTimestamp,
 Instant endSourceTimestamp,DistanceMeters maximumDistance,int eligibleOutsideSampleCount,Severity severity,
 RouteDeviationReview.Status reviewStatus,long reviewVersion,TerminalOutcome terminalOutcome,UUID disruptionId,
 boolean distanceHighEscalated,boolean reviewRejectedEscalated) {
 public enum Severity { WARNING,HIGH }
 public enum TerminalOutcome { RETURNED_TO_ROUTE,SUPERSEDED,TRIP_ENDED_UNRESOLVED }
 public RouteDeviationEpisode {Objects.requireNonNull(id);Objects.requireNonNull(tenantId);Objects.requireNonNull(vehicleId);Objects.requireNonNull(routeId);Objects.requireNonNull(routeVersion);Objects.requireNonNull(ruleId);Objects.requireNonNull(configuredTolerance);Objects.requireNonNull(effectiveTolerance);Objects.requireNonNull(firstCandidatePositionId);Objects.requireNonNull(confirmingPositionId);Objects.requireNonNull(startSourceTimestamp);Objects.requireNonNull(confirmationSourceTimestamp);Objects.requireNonNull(maximumDistance);Objects.requireNonNull(severity);Objects.requireNonNull(reviewStatus);if(ruleVersion<1||eligibleOutsideSampleCount<2||reviewVersion<0)throw new IllegalArgumentException("Invalid episode versions/count");}
 public static Severity severity(DistanceMeters distance,DistanceMeters tolerance){if(distance.compareTo(tolerance)<=0)throw new RouteDeviationException("INVALID_DISTANCE","Deviation distance must exceed tolerance");return distance.compareTo(tolerance.twice())<=0?Severity.WARNING:Severity.HIGH;}
 public static RouteDeviationEpisode confirm(UUID tenant,UUID vehicle,UUID trip,UUID driver,UUID route,RouteVersion rv,RouteDeviationRule rule,RouteDeviationPosition first,RouteDeviationPosition confirming,DistanceMeters firstDistance,DistanceMeters confirmingDistance,DistanceMeters effective){DistanceMeters max=firstDistance.compareTo(confirmingDistance)>=0?firstDistance:confirmingDistance;Severity s=severity(max,effective);return new RouteDeviationEpisode(RouteDeviationEpisodeIdentity.create(tenant,vehicle,trip,route,rv,rule.id(),rule.ruleVersion(),first.positionId()),tenant,vehicle,trip,driver,route,rv,rule.id(),rule.ruleVersion(),rule.configuredTolerance(),effective,first.positionId(),confirming.positionId(),first.sourceTimestamp(),confirming.sourceTimestamp(),null,max,2,s,s==Severity.HIGH?RouteDeviationReview.Status.PENDING:RouteDeviationReview.Status.NOT_REQUIRED,0,null,null,s==Severity.HIGH,false);}
 public RouteDeviationEpisode progress(DistanceMeters distance){if(!open())throw new RouteDeviationException("EPISODE_CLOSED","Episode is closed");DistanceMeters max=maximumDistance.compareTo(distance)>=0?maximumDistance:distance;Severity next=severity(max,effectiveTolerance);return copy(null,max,eligibleOutsideSampleCount+1,next,next==Severity.HIGH&&reviewStatus==RouteDeviationReview.Status.NOT_REQUIRED?RouteDeviationReview.Status.PENDING:reviewStatus,null,distanceHighEscalated||severity==Severity.WARNING&&next==Severity.HIGH,reviewRejectedEscalated);}
 public RouteDeviationEpisode close(Instant at,TerminalOutcome outcome){if(!open()||at.isBefore(confirmationSourceTimestamp))throw new RouteDeviationException("EPISODE_CLOSE_INVALID","Open episode and valid close time required");return copy(at,maximumDistance,eligibleOutsideSampleCount,severity,reviewStatus,outcome,distanceHighEscalated,reviewRejectedEscalated);}
 public RouteDeviationEpisode reviewed(RouteDeviationReview review){Objects.requireNonNull(review);if(!tenantId.equals(review.tenantId())||!id.equals(review.episodeId())||review.reviewVersion()!=reviewVersion+1)throw new RouteDeviationException("STALE_REVIEW_VERSION","Review version is stale");return new RouteDeviationEpisode(id,tenantId,vehicleId,tripId,driverId,routeId,routeVersion,ruleId,ruleVersion,configuredTolerance,effectiveTolerance,firstCandidatePositionId,confirmingPositionId,startSourceTimestamp,confirmationSourceTimestamp,endSourceTimestamp,maximumDistance,eligibleOutsideSampleCount,severity,review.status(),review.reviewVersion(),terminalOutcome,disruptionId,distanceHighEscalated,reviewRejectedEscalated);}
 public boolean open(){return endSourceTimestamp==null;}
 private RouteDeviationEpisode copy(Instant end,DistanceMeters max,int count,Severity sev,RouteDeviationReview.Status review,TerminalOutcome outcome,boolean high,boolean rejected){return new RouteDeviationEpisode(id,tenantId,vehicleId,tripId,driverId,routeId,routeVersion,ruleId,ruleVersion,configuredTolerance,effectiveTolerance,firstCandidatePositionId,confirmingPositionId,startSourceTimestamp,confirmationSourceTimestamp,end,max,count,sev,review,reviewVersion,outcome,disruptionId,high,rejected);}
}
