package com.transportlogistics.app.tracking.domain.routedeviation;

public enum RouteDeviationAvailability {
    AVAILABLE,
    NO_TRIP,
    NO_ASSIGNED_ROUTE,
    NO_ROUTE_REVISION,
    ROUTE_UNAVAILABLE,
    GEOMETRY_UNAVAILABLE,
    MALFORMED_GEOMETRY,
    RULE_UNAVAILABLE,
    ACCURACY_UNKNOWN,
    EXCESSIVE_ACCURACY,
    STALE_POSITION,
    OUT_OF_ORDER_POSITION,
    UNTRUSTED_POSITION,
    INVALID_COORDINATE,
    PROVIDER_UNAVAILABLE,
    CONFIGURATION_UNAVAILABLE,
    POSITION_INELIGIBLE
}
