package com.transportlogistics.app.tracking.domain.routedeviation;
import static org.junit.jupiter.api.Assertions.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class RouteDeviationEpisodeReviewTest {
 @Test void severityBoundariesAndIdentity(){DistanceMeters t=DistanceMeters.of(100);assertEquals(RouteDeviationEpisode.Severity.WARNING,RouteDeviationEpisode.severity(DistanceMeters.of(200),t));assertEquals(RouteDeviationEpisode.Severity.HIGH,RouteDeviationEpisode.severity(DistanceMeters.of(200.01),t));UUID tenant=UUID.randomUUID(),vehicle=UUID.randomUUID(),route=UUID.randomUUID(),rule=UUID.randomUUID(),pos=UUID.randomUUID();UUID a=RouteDeviationEpisodeIdentity.create(tenant,vehicle,null,route,new RouteVersion("REVISION:1"),rule,1,pos);assertEquals(a,RouteDeviationEpisodeIdentity.create(tenant,vehicle,null,route,new RouteVersion("REVISION:1"),rule,1,pos));assertNotEquals(a,RouteDeviationEpisodeIdentity.create(tenant,vehicle,null,route,new RouteVersion("REVISION:2"),rule,1,pos));}
 @Test void stateCandidateNeedsDistinctSameContext(){UUID tenant=UUID.randomUUID(),vehicle=UUID.randomUUID(),trip=UUID.randomUUID(),route=UUID.randomUUID();Instant t=Instant.EPOCH;RouteDeviationPosition first=p(tenant,vehicle,UUID.randomUUID(),t);RouteDeviationRule rule=rule(tenant,route,t);VehicleRouteDeviationState s=VehicleRouteDeviationState.unknown(tenant,vehicle).candidate(first,trip,null,route,new RouteVersion("REVISION:1"),rule,DistanceMeters.of(20),DistanceMeters.of(30));assertFalse(s.confirms(first,trip,route,new RouteVersion("REVISION:1"),rule));assertTrue(s.confirms(p(tenant,vehicle,UUID.randomUUID(),t.plusSeconds(1)),trip,route,new RouteVersion("REVISION:1"),rule));assertFalse(s.confirms(p(tenant,vehicle,UUID.randomUUID(),t.plusSeconds(1)),trip,route,new RouteVersion("REVISION:2"),rule));}
 @Test void reviewValidationAndCompensation(){UUID tenant=UUID.randomUUID(),episode=UUID.randomUUID(),actor=UUID.randomUUID();assertThrows(RouteDeviationException.class,()->RouteDeviationReview.decide(tenant,episode,RouteDeviationReview.Status.APPROVED,RouteDeviationReview.Reason.UNKNOWN,"short",actor,Instant.EPOCH,0));RouteDeviationReview r=RouteDeviationReview.decide(tenant,episode,RouteDeviationReview.Status.APPROVED,RouteDeviationReview.Reason.AUTHORIZED_DETOUR,null,actor,Instant.EPOCH,0);assertThrows(RouteDeviationException.class,()->r.correct(RouteDeviationReview.Status.REJECTED,RouteDeviationReview.Reason.ROAD_CLOSURE,null,actor,Instant.EPOCH.plusSeconds(1),1));RouteDeviationReview correction=r.correct(RouteDeviationReview.Status.REJECTED,RouteDeviationReview.Reason.ROAD_CLOSURE,null,UUID.randomUUID(),Instant.EPOCH.plusSeconds(1),1);assertEquals(r.id(),correction.compensatesReviewId());}
 private static RouteDeviationRule rule(UUID tenant,UUID route,Instant t){return new RouteDeviationRule(UUID.randomUUID(),tenant,route,new RouteVersion("REVISION:1"),DistanceMeters.of(10),RouteDeviationRule.Lifecycle.ACTIVE,1,1,t);}
 private static RouteDeviationPosition p(UUID tenant,UUID vehicle,UUID id,Instant t){return new RouteDeviationPosition(id,tenant,vehicle,t,new RoutePoint(BigDecimal.ZERO,BigDecimal.ZERO),DistanceMeters.of(1),true,false,RouteDeviationPosition.Trust.TRUSTED,true,RouteDeviationPosition.Ordering.IN_ORDER);}
}
