package com.transportlogistics.app.tracking.adapters.configuration;
import com.transportlogistics.app.fleet.FleetReportingQuery;
import com.transportlogistics.app.tracking.application.TrackingService;
import com.transportlogistics.app.tracking.application.TrackingMaintenanceService;
import com.transportlogistics.app.tracking.application.TrackingProviderManagementService;
import com.transportlogistics.app.tracking.application.GeofenceEvaluationService;
import com.transportlogistics.app.tracking.application.GeofenceManagementService;
import com.transportlogistics.app.tracking.application.SpeedEvaluationService;
import com.transportlogistics.app.tracking.application.SpeedRuleManagementService;
import com.transportlogistics.app.tracking.adapters.inbound.security.SecuredGeofenceUseCases;
import com.transportlogistics.app.tracking.adapters.inbound.security.SecuredSpeedMonitoringUseCases;
import com.transportlogistics.app.integration.IntegrationSecretResolver;
import com.transportlogistics.app.tracking.application.provider.TrackingProviderAdapterRegistry;
import com.transportlogistics.app.tracking.ports.outbound.TrackingProviderAdapter;
import com.transportlogistics.app.tracking.ports.outbound.TrackingProviderConnectionStore;
import com.transportlogistics.app.tracking.ports.outbound.TrackingDeviceProviderBindingStore;
import com.transportlogistics.app.tracking.ports.outbound.TrackingStore;
import com.transportlogistics.app.tracking.ports.outbound.GeofenceEvaluationTransactionPort;
import com.transportlogistics.app.tracking.ports.outbound.GeofenceRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.GeofenceLocationLookupPort;
import com.transportlogistics.app.tracking.ports.outbound.GeofenceManagementSupportPort;
import com.transportlogistics.app.tracking.ports.outbound.GeofenceManagementTransactionPort;
import com.transportlogistics.app.tracking.ports.outbound.GeofenceTransitionRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.VehicleGeofenceStateRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedAttributionLookupPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedEvaluationJobRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedEvaluationTransactionPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedPositionRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedManagementSupportPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedManagementTransactionPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedRuleRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedingEpisodePublisherPort;
import com.transportlogistics.app.tracking.ports.outbound.SpeedingEpisodeRepositoryPort;
import com.transportlogistics.app.tracking.ports.outbound.VehicleSpeedStateRepositoryPort;
import java.time.Clock;
import java.util.List;
import org.springframework.context.annotation.*;
@Configuration class TrackingConfiguration {
 @Bean TrackingService trackingUseCase(TrackingStore store,FleetReportingQuery fleet,Clock clock){return new TrackingService(store,fleet,clock);}
 @Bean TrackingMaintenanceService trackingMaintenanceUseCase(TrackingStore store,Clock clock){return new TrackingMaintenanceService(store,clock);}
 @Bean TrackingProviderAdapterRegistry trackingProviderAdapterRegistry(List<TrackingProviderAdapter> adapters){return new TrackingProviderAdapterRegistry(adapters);}
 @Bean TrackingProviderManagementService trackingProviderManagementUseCase(TrackingProviderConnectionStore connections,TrackingDeviceProviderBindingStore bindings,TrackingProviderAdapterRegistry adapters,IntegrationSecretResolver secrets,Clock clock){return new TrackingProviderManagementService(connections,bindings,adapters,secrets,clock);}
 @Bean GeofenceEvaluationService geofenceEvaluationUseCase(GeofenceRepositoryPort geofences,VehicleGeofenceStateRepositoryPort states,GeofenceTransitionRepositoryPort transitions,com.transportlogistics.app.tracking.ports.outbound.GeofenceTransitionPublisherPort publisher,GeofenceEvaluationTransactionPort transaction){return new GeofenceEvaluationService(geofences,states,transitions,publisher,transaction);}
 @Bean GeofenceManagementService geofenceManagementService(GeofenceRepositoryPort geofences,VehicleGeofenceStateRepositoryPort states,GeofenceTransitionRepositoryPort transitions,GeofenceLocationLookupPort locations,GeofenceManagementSupportPort support,GeofenceManagementTransactionPort transaction){return new GeofenceManagementService(geofences,states,transitions,locations,support,transaction);}
 @Bean SpeedEvaluationService speedEvaluationUseCase(SpeedPositionRepositoryPort positions,SpeedRuleRepositoryPort rules,VehicleSpeedStateRepositoryPort states,SpeedingEpisodeRepositoryPort episodes,SpeedEvaluationJobRepositoryPort jobs,SpeedAttributionLookupPort attribution,SpeedingEpisodePublisherPort publisher,SpeedEvaluationTransactionPort transaction){return new SpeedEvaluationService(positions,rules,states,episodes,jobs,attribution,publisher,transaction);}
 @Bean SpeedRuleManagementService speedRuleManagementService(SpeedRuleRepositoryPort rules,VehicleSpeedStateRepositoryPort states,SpeedingEpisodeRepositoryPort episodes,SpeedManagementSupportPort support,SpeedManagementTransactionPort transaction){return new SpeedRuleManagementService(rules,states,episodes,support,transaction);}
 @Bean @Primary SecuredGeofenceUseCases securedGeofenceUseCases(GeofenceManagementService service){return new SecuredGeofenceUseCases(service,service);}
 @Bean @Primary SecuredSpeedMonitoringUseCases securedSpeedMonitoringUseCases(SpeedRuleManagementService service){return new SecuredSpeedMonitoringUseCases(service,service);}
}
