package com.transportlogistics.app.tracking;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import com.transportlogistics.app.shared.domain.BusinessRuleException;
import com.transportlogistics.app.support.PostgreSqlIntegrationTest;
import com.transportlogistics.app.tracking.domain.TrackingModels.*;
import com.transportlogistics.app.tracking.ports.inbound.TrackingMaintenanceUseCase;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.*;
import com.transportlogistics.app.tracking.ports.outbound.TrackingStore;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

class TrackingRemediationPostgreSqlAcceptanceTest extends PostgreSqlIntegrationTest {
 private static final UUID ACTOR=UUID.fromString("10000000-0000-0000-0000-000000000001");
 @Autowired TrackingStore store;@Autowired TrackingMaintenanceUseCase maintenance;@Autowired JdbcTemplate jdbc;
 @Test void v74BindingAuthorityIsGlobalTenantSafeAndNonceIsBindingScoped(){UUID a=UUID.randomUUID(),b=UUID.randomUUID();var first=maintenance.createProviderBinding(context(a),"opaque-key","FIXTURE","env:US48_TEST_SECRET");assertThat(store.providerBinding("opaque-key")).contains(first);assertThatThrownBy(()->maintenance.createProviderBinding(context(b),"opaque-key","FIXTURE","env:OTHER")).isInstanceOf(Exception.class);assertThatThrownBy(()->jdbc.update("UPDATE tracking_provider_binding SET tenant_id=? WHERE id=?",b,first.id())).isInstanceOf(Exception.class);Instant now=Instant.now();assertThat(store.reserveNonce(a,first.id(),"a".repeat(64),now,now.plusSeconds(600))).isTrue();assertThat(store.reserveNonce(a,first.id(),"a".repeat(64),now,now.plusSeconds(600))).isFalse();assertThat(jdbc.queryForObject("SELECT count(*) FROM tracking_ingest_nonce WHERE tenant_id=?",Integer.class,a)).isZero();}
 @Test void retentionBoundaryIsExactAndAbsentPolicyDoesNotRejectByAge(){var noPolicy=fixture();Instant received=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);assertThat(ingest(noPolicy,"unconfigured-old",received.minusSeconds(48*3600),received)).hasSize(1);var configured=fixture();maintenance.configureRetention(context(configured.tenant()),3600,"RETENTION-V1",received.minusSeconds(60));assertThat(ingest(configured,"exact",received.minusSeconds(3600),received)).hasSize(1);assertThatThrownBy(()->ingest(configured,"too-old",received.minusSeconds(3601),received)).isInstanceOfSatisfying(BusinessRuleException.class,e->assertThat(e.code()).isEqualTo("TRACKING_POSITION_TOO_OLD"));assertThat(jdbc.queryForObject("SELECT retain_until FROM tracking_position WHERE tenant_id=? AND provider_message_id='exact'",java.sql.Timestamp.class,configured.tenant()).toInstant()).isEqualTo(received);}
 @Test void rebuildRestoresDeterministicProjectionAndSecondRunIsIdempotent(){var f=fixture();Instant base=Instant.now().minusSeconds(30);ingest(f,"trusted-newer-source",base.plusSeconds(10),base.plusSeconds(11));ingest(f,"received-later",base,base.plusSeconds(20));var expectedReceived=jdbc.queryForObject("SELECT id FROM tracking_position WHERE tenant_id=? AND provider_message_id='received-later'",UUID.class,f.tenant());var expectedTrusted=jdbc.queryForObject("SELECT id FROM tracking_position WHERE tenant_id=? AND provider_message_id='trusted-newer-source'",UUID.class,f.tenant());jdbc.update("DELETE FROM tracking_vehicle_latest WHERE tenant_id=? AND vehicle_id=?",f.tenant(),f.vehicle());maintenance.rebuildLatest(f.tenant(),f.vehicle());assertThat(latestIds(f)).containsExactly(expectedReceived,expectedTrusted);long version=jdbc.queryForObject("SELECT version FROM tracking_vehicle_latest WHERE tenant_id=? AND vehicle_id=?",Long.class,f.tenant(),f.vehicle());maintenance.rebuildLatest(f.tenant(),f.vehicle());assertThat(latestIds(f)).containsExactly(expectedReceived,expectedTrusted);assertThat(jdbc.queryForObject("SELECT version FROM tracking_vehicle_latest WHERE tenant_id=? AND vehicle_id=?",Long.class,f.tenant(),f.vehicle())).isEqualTo(version);}
 @Test void providerAndRetentionMutationsWriteSafeAuditWithoutSecrets(){UUID tenant=UUID.randomUUID();var binding=maintenance.createProviderBinding(context(tenant),"audit-key","FIXTURE","env:FIRST");maintenance.updateProviderCredential(context(tenant),binding.id(),binding.version(),"env:SECOND");maintenance.configureRetention(context(tenant),86400,"P2",Instant.now());var details=jdbc.queryForList("SELECT safe_detail FROM tracking_audit_event WHERE tenant_id=?",String.class,tenant);assertThat(details).noneMatch(value->value!=null&&(value.contains("env:FIRST")||value.contains("env:SECOND")));assertThat(details).hasSize(3);}
 @Test void boundedIndexesAndReadLatenciesMeetClosureTargets(){var f=fixture();Instant received=Instant.now();ingest(f,"latency",received.minusSeconds(1),received);var indexes=jdbc.queryForList("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND tablename IN ('tracking_provider_binding','tracking_provider_ingest_nonce','tracking_retention_policy')",String.class);assertThat(indexes).contains("uq_tracking_provider_key_id","tracking_provider_ingest_nonce_pkey","idx_tracking_retention_policy_effective");long[] latest=new long[50],history=new long[50];for(int i=0;i<50;i++){long start=System.nanoTime();assertThat(store.state(f.tenant(),f.vehicle(),received)).isPresent();latest[i]=System.nanoTime()-start;start=System.nanoTime();assertThat(store.positions(f.tenant(),f.vehicle(),received.minusSeconds(86400),received.plusSeconds(1),null,100).items()).isNotEmpty();history[i]=System.nanoTime()-start;}java.util.Arrays.sort(latest);java.util.Arrays.sort(history);double latestP95=latest[47]/1_000_000d,historyP95=history[47]/1_000_000d;System.out.printf("US48_LATEST_P95_MS=%.3f US48_HISTORY_P95_MS=%.3f%n",latestP95,historyP95);assertThat(latestP95).isLessThanOrEqualTo(200d);assertThat(historyP95).isLessThanOrEqualTo(500d);}
 private Fixture fixture(){UUID tenant=UUID.randomUUID();var draft=store.insertDevice(context(tenant),new CreateDevice("device-"+tenant,"FIXTURE",null),Instant.now());UUID device=store.lifecycle(context(tenant),draft.id(),draft.version(),DeviceLifecycle.ACTIVE,Instant.now()).id();UUID vehicle=UUID.randomUUID();store.associate(context(tenant),device,new Associate(vehicle,Instant.now().minusSeconds(72*3600)),Instant.now());return new Fixture(tenant,device,vehicle);}
 private List<IngestResult> ingest(Fixture f,String message,Instant source,Instant received){return store.ingest(new ProviderContext(f.tenant(),"FIXTURE"),List.of(new PositionCommand(f.device(),message,1L,source,new BigDecimal("6.9271"),new BigDecimal("79.8612"),new BigDecimal("5"),null,null,null,EngineState.UNKNOWN,null,null,Map.of())),received);}
 private List<UUID> latestIds(Fixture f){return jdbc.queryForObject("SELECT ARRAY[latest_received_position_id,latest_trusted_position_id] FROM tracking_vehicle_latest WHERE tenant_id=? AND vehicle_id=?",(r,n)->List.of((UUID[])r.getArray(1).getArray()),f.tenant(),f.vehicle());}
 private Context context(UUID tenant){return new Context(tenant,ACTOR,"us48-remediation-test");}
 private record Fixture(UUID tenant,UUID device,UUID vehicle){}
}
