package com.transportlogistics.app.fleet.payroll.application;
import com.transportlogistics.app.fleet.payroll.domain.DriverPayrollInputLine;
import com.transportlogistics.app.fleet.payroll.domain.DriverPayrollWorkerMapping;
import com.transportlogistics.app.fleet.payroll.domain.DriverPayrollInputBatch;
import com.transportlogistics.app.fleet.payroll.ports.outbound.DriverPayrollStore;
import com.transportlogistics.app.fleet.payroll.ports.outbound.DriverPayrollTransaction;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.transportlogistics.app.fleet.DriverLookup;
import com.transportlogistics.app.fleet.DriverPayrollDeliveryPort;
import com.transportlogistics.app.fleet.DriverPayrollIntegrationPort;
import com.transportlogistics.app.fleet.DriverPayrollSourcePort;
import com.transportlogistics.app.fleet.payroll.DriverPayrollInputExportRequestedV1;

import com.transportlogistics.app.fleet.payroll.ports.inbound.DriverPayrollUseCase;

import com.transportlogistics.app.shared.domain.BusinessRuleException;
import com.transportlogistics.app.shared.domain.ConflictException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;

public final class DriverPayrollService implements DriverPayrollUseCase, DriverPayrollDeliveryPort {
 private static final int MAX_PAYLOAD=32*1024;
 private final DriverPayrollStore store; private final DriverPayrollSourcePort trips; private final DriverLookup drivers;
 private final DriverPayrollIntegrationPort integrations; private final DriverPayrollTransaction tx;
 private final ObjectMapper json; private final Clock clock;
 public DriverPayrollService(DriverPayrollStore store,DriverPayrollSourcePort trips,DriverLookup drivers,
   DriverPayrollIntegrationPort integrations,DriverPayrollTransaction tx,ObjectMapper json,Clock clock){this.store=store;this.trips=trips;this.drivers=drivers;this.integrations=integrations;this.tx=tx;this.json=json;this.clock=clock;}
 @Override public DriverPayrollInputBatch create(Context c,Create x,String idempotencyKey){return tx.execute(()->{String normalizedKey=key(idempotencyKey);store.lockBatchCommand(c.tenantId(),normalizedKey);var replay=store.findByIdempotency(c.tenantId(),normalizedKey);if(replay.isPresent())return replay.get();var at=now();var value=new DriverPayrollInputBatch(UUID.randomUUID(),c.tenantId(),x.type(),x.correctionOfBatchId(),x.periodStart(),x.periodEndExclusive(),x.cutoffAt(),x.currency(),DriverPayrollInputBatch.Lifecycle.DRAFT,List.of(),null,c.actorId(),null,null,null,UUID.randomUUID(),null,0,at,at);var saved=store.insert(value,normalizedKey);store.history(c.tenantId(),saved.id(),"BATCH_CREATED",null,"DRAFT",c.actorId(),null,at);return saved;});}
 @Override public List<DriverPayrollInputBatch> list(UUID t,int p,int s){return store.list(t,Math.max(0,p),Math.min(100,Math.max(1,s)));}
 @Override public DriverPayrollInputBatch get(UUID t,UUID id){return store.find(t,id).orElseThrow(()->rule("DRIVER_PAYROLL_BATCH_NOT_FOUND"));}
 @Override public DriverPayrollInputBatch replaceLines(Context c,UUID id,long version,List<LineCommand> commands){return tx.execute(()->{var b=get(c.tenantId(),id);check(b,version);var lines=commands.stream().map(this::line).toList();var n=b.replaceLines(lines,now());var saved=store.update(n,version);store.history(c.tenantId(),id,"LINES_REPLACED",b.lifecycle().name(),saved.lifecycle().name(),c.actorId(),Integer.toString(lines.size()),now());return saved;});}
 @Override public DriverPayrollInputBatch validate(Context c,UUID id,long version){return tx.execute(()->{var b=get(c.tenantId(),id);check(b,version);UUID config=integrations.activePayrollConfiguration(c.tenantId()).orElseThrow(()->rule("DRIVER_PAYROLL_EXPORT_CONFIGURATION_INVALID"));var snapshots=new ArrayList<DriverPayrollInputLine>();var seen=new HashSet<String>();for(var l:b.lines()){if(b.type()==DriverPayrollInputBatch.Type.CORRECTION&&(l.originalLineId()==null||!store.originalLineBelongsToBatch(c.tenantId(),l.originalLineId(),b.correctionOfBatchId())))throw rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE");if(b.type()==DriverPayrollInputBatch.Type.REGULAR&&l.originalLineId()!=null)throw rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE");var driver=drivers.findDriver(l.driverId()).filter(d->d.active()).orElseThrow(()->rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE"));var fact=trips.trip(l.driverId(),l.tripId(),b.periodStart(),b.periodEndExclusive()).orElseThrow(()->rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE"));if(!Set.of("COMPLETED","CLOSED").contains(fact.status())||fact.actualEndTime()==null||fact.actualEndTime().isAfter(b.cutoffAt()))throw rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE");String source=l.driverId()+":"+l.tripId()+":"+l.category()+":"+l.originalLineId();if(!seen.add(source)||store.releasedSourceExists(c.tenantId(),l.driverId(),l.tripId(),l.category().name(),l.originalLineId(),b.id()))throw rule("DRIVER_PAYROLL_SOURCE_DUPLICATE");var mapping=store.mapping(c.tenantId(),driver.id()).filter(DriverPayrollWorkerMapping::active).orElseThrow(()->rule("DRIVER_PAYROLL_WORKER_MAPPING_REQUIRED"));snapshots.add(l.snapshot(hash(fact.tripId()+"|"+fact.tripNumber()+"|"+fact.status()+"|"+fact.actualEndTime()),mapping.externalWorkerReference()));}var at=now();String validation=hash(canonicalForHash(b,snapshots));var validated=b.validated(snapshots,validation,config,at);requirePayloadSize(validated,at);var saved=store.update(validated,version);store.history(c.tenantId(),id,"BATCH_VALIDATED",b.lifecycle().name(),"VALIDATED",c.actorId(),validation,at);return saved;});}
 @Override public DriverPayrollInputBatch approve(Context c,UUID id,long version){return tx.execute(()->{var b=get(c.tenantId(),id);check(b,version);for(var l:b.lines().stream().sorted(Comparator.comparing(x->x.driverId()+":"+x.tripId()+":"+x.category()+":"+x.originalLineId())).toList()){store.lockReleasedSource(c.tenantId(),l.driverId(),l.tripId(),l.category().name(),l.originalLineId());if(store.releasedSourceExists(c.tenantId(),l.driverId(),l.tripId(),l.category().name(),l.originalLineId(),b.id()))throw rule("DRIVER_PAYROLL_SOURCE_DUPLICATE");}var at=now();var saved=store.update(b.approved(c.actorId(),at),version);store.history(c.tenantId(),id,"BATCH_APPROVED",b.lifecycle().name(),"APPROVED",c.actorId(),b.validationHash(),at);return saved;});}
 @Override public DriverPayrollInputBatch export(Context c,UUID id,long version){return tx.execute(()->{var b=get(c.tenantId(),id);if(Set.of(DriverPayrollInputBatch.Lifecycle.EXPORT_REQUESTED,DriverPayrollInputBatch.Lifecycle.EXPORTED,DriverPayrollInputBatch.Lifecycle.SUPERSEDED).contains(b.lifecycle()))return b;check(b,version);UUID event=b.exportEventId()==null?UUID.randomUUID():b.exportEventId();var at=now();requirePayloadSize(b,at);var payload=payload(b,at);integrations.publish(new DriverPayrollInputExportRequestedV1(event,c.tenantId(),b.id(),at,payload));var saved=store.update(b.exportRequested(event,at),version);store.history(c.tenantId(),id,"EXPORT_REQUESTED",b.lifecycle().name(),"EXPORT_REQUESTED",c.actorId(),event.toString(),at);return saved;});}
 @Override public DriverPayrollInputBatch correction(Context c,UUID id,CreateCorrection x,String key){return tx.execute(()->{var original=get(c.tenantId(),id);if(original.lifecycle()!=DriverPayrollInputBatch.Lifecycle.EXPORT_REQUESTED&&original.lifecycle()!=DriverPayrollInputBatch.Lifecycle.EXPORTED)throw rule("DRIVER_PAYROLL_INVALID_STATE");var batch=create(c,new Create(DriverPayrollInputBatch.Type.CORRECTION,id,x.periodStart(),x.periodEndExclusive(),x.cutoffAt(),x.currency()),key);if(!batch.lines().isEmpty())return batch;return replaceLines(c,batch.id(),batch.version(),x.lines());});}
 @Override public List<DriverPayrollStore.History> history(UUID t,UUID id){get(t,id);return store.history(t,id);}
 @Override public Optional<DriverPayrollWorkerMapping> mapping(UUID t,UUID d){drivers.findDriver(d).orElseThrow(()->rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE"));return store.mapping(t,d);}
 @Override public DriverPayrollWorkerMapping mapWorker(Context c,UUID d,MappingCommand x,String idempotencyKey){return tx.execute(()->{String normalizedKey=key(idempotencyKey);if(x.externalSystemAlias()==null||!x.externalSystemAlias().matches("[A-Z0-9_-]{1,80}")||x.externalWorkerReference()==null||x.externalWorkerReference().isBlank()||x.externalWorkerReference().length()>160)throw rule("DRIVER_PAYROLL_VALIDATION_FAILED");String workerReference=x.externalWorkerReference().trim();String requestHash=hash(d+"|"+x.externalSystemAlias()+"|"+workerReference+"|"+x.active()+"|"+x.version());store.lockMappingCommand(c.tenantId(),normalizedKey);var replay=store.mappingCommand(c.tenantId(),normalizedKey);if(replay.isPresent()){if(!replay.get().requestHash().equals(requestHash))throw conflict("DRIVER_PAYROLL_IDEMPOTENCY_CONFLICT");return replay.get().mapping();}drivers.findDriver(d).orElseThrow(()->rule("DRIVER_PAYROLL_SOURCE_NOT_ELIGIBLE"));var existing=store.mapping(c.tenantId(),d);if(existing.isPresent()&&existing.get().version()!=x.version())throw conflict("DRIVER_PAYROLL_STALE_VERSION");var at=postgresTimestamp(now());var saved=store.saveMapping(new DriverPayrollWorkerMapping(existing.map(DriverPayrollWorkerMapping::id).orElse(UUID.randomUUID()),c.tenantId(),d,x.externalSystemAlias(),workerReference,x.active(),existing.map(DriverPayrollWorkerMapping::version).orElse(0L),c.actorId(),existing.map(DriverPayrollWorkerMapping::createdAt).orElse(at),at),x.version());store.saveMappingCommand(c.tenantId(),d,normalizedKey,requestHash,saved,c.actorId(),at);return saved;});}
 @Override public void fileDelivered(UUID tenantId,UUID sourceEventId,String payloadHash,String targetFilename,OffsetDateTime deliveredAt){tx.execute(()->{var batch=store.findByExportEvent(tenantId,sourceEventId).orElse(null);if(batch==null||batch.lifecycle()==DriverPayrollInputBatch.Lifecycle.EXPORTED||batch.lifecycle()==DriverPayrollInputBatch.Lifecycle.SUPERSEDED)return null;var exported=store.update(batch.exported(deliveredAt),batch.version());store.history(tenantId,batch.id(),"FILE_DELIVERED",batch.lifecycle().name(),"EXPORTED",new UUID(0,0),payloadHash+":"+targetFilename,deliveredAt);if(exported.type()==DriverPayrollInputBatch.Type.CORRECTION&&exported.correctionOfBatchId()!=null){var original=get(tenantId,exported.correctionOfBatchId());if(original.lifecycle()==DriverPayrollInputBatch.Lifecycle.EXPORTED){store.update(original.superseded(deliveredAt),original.version());store.history(tenantId,original.id(),"SUPERSEDED","EXPORTED","SUPERSEDED",new UUID(0,0),exported.id().toString(),deliveredAt);}}return null;});}
 private DriverPayrollInputLine line(LineCommand x){return new DriverPayrollInputLine(x.id()==null?UUID.randomUUID():x.id(),x.driverId(),x.tripId(),x.tripNumber(),x.category(),x.reasonCode(),x.description(),x.quantity(),x.unit(),x.rate(),x.amount(),x.originalLineId(),null,null);}
 private Map<String,Object> payload(DriverPayrollInputBatch b,OffsetDateTime generated){var lines=b.lines().stream().sorted(Comparator.comparing(DriverPayrollInputLine::id)).map(l->{Map<String,Object> m=new LinkedHashMap<>();m.put("lineId",l.id().toString());m.put("tripId",l.tripId().toString());m.put("tripNumber",l.tripNumber());m.put("category",l.category().name());m.put("reasonCode",l.reasonCode());m.put("quantity",l.quantity().toPlainString());m.put("unit",l.unit().name());m.put("rate",l.rate().toPlainString());m.put("amount",l.amount().toPlainString());m.put("originalLineId",l.originalLineId()==null?null:l.originalLineId().toString());m.put("sourceSnapshotHash",l.sourceSnapshotHash());return m;}).toList();var grouped=b.lines().stream().map(DriverPayrollInputLine::driverId).distinct().sorted().map(d->Map.<String,Object>of("driverId",d.toString(),"externalWorkerReference",b.lines().stream().filter(l->l.driverId().equals(d)).findFirst().orElseThrow().externalWorkerReference(),"lines",lines.stream().filter(m->b.lines().stream().anyMatch(l->l.driverId().equals(d)&&l.id().toString().equals(m.get("lineId")))).toList())).toList();var t=b.totals();Map<String,Object> totals=new LinkedHashMap<>();totals.put("tripEarnings",t.tripEarnings().toPlainString());totals.put("allowances",t.allowances().toPlainString());totals.put("overtime",t.overtime().toPlainString());totals.put("deductions",t.deductions().toPlainString());totals.put("provisionalNetInput",t.provisionalNetInput().toPlainString());Map<String,Object> p=new LinkedHashMap<>();p.put("schemaVersion",1);p.put("batchId",b.id().toString());p.put("batchType",b.type().name());p.put("periodStart",b.periodStart().toString());p.put("periodEndExclusive",b.periodEndExclusive().toString());p.put("cutoffAt",b.cutoffAt().toString());p.put("generatedAt",generated.toString());p.put("currency",b.currency());p.put("totals",totals);p.put("drivers",grouped);return p;}
 private String canonicalForHash(DriverPayrollInputBatch b,List<DriverPayrollInputLine> lines){return b.id()+"|"+b.periodStart()+"|"+b.periodEndExclusive()+"|"+b.cutoffAt()+"|"+b.currency()+"|"+lines;}
 private void requirePayloadSize(DriverPayrollInputBatch batch,OffsetDateTime generatedAt){try{if(json.writeValueAsBytes(payload(batch,generatedAt)).length>MAX_PAYLOAD)throw rule("DRIVER_PAYROLL_VALIDATION_FAILED");}catch(com.fasterxml.jackson.core.JsonProcessingException e){throw rule("DRIVER_PAYROLL_VALIDATION_FAILED");}}
 private static String hash(String text){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static String key(String k){if(k==null||k.isBlank()||k.length()>160)throw rule("DRIVER_PAYROLL_VALIDATION_FAILED");return k.trim();}
 private static void check(DriverPayrollInputBatch b,long v){if(b.version()!=v)throw conflict("DRIVER_PAYROLL_STALE_VERSION");}
 private OffsetDateTime now(){return OffsetDateTime.ofInstant(clock.instant(),ZoneOffset.UTC);}
 private static OffsetDateTime postgresTimestamp(OffsetDateTime value){return value.withNano(value.getNano()/1_000*1_000);}
 private static BusinessRuleException rule(String c){return new BusinessRuleException(c,c);}
 private static ConflictException conflict(String c){return new ConflictException(c,c);}
}
