export type DeviationLifecycle='DRAFT'|'ACTIVE'|'DISABLED'|'RETIRED';
export type DeviationState='UNKNOWN'|'ON_ROUTE'|'DEVIATING';
export type DeviationAvailability='AVAILABLE'|'NOT_EVALUATED'|'CONFIGURATION_UNAVAILABLE';
export type DeviationSeverity='WARNING'|'HIGH';
export type ReviewStatus='APPROVED'|'REJECTED';
export type ReviewReason='AUTHORIZED_DETOUR'|'ROAD_CLOSURE'|'TRAFFIC_DIVERSION'|'OPERATIONAL_NECESSITY'|'UNKNOWN';
export interface DeviationRule{id:string;routeId:string;routeVersion:string;toleranceMeters:number;lifecycle:DeviationLifecycle;ruleVersion:number;version:number;effectiveAt?:string|null}
export interface DeviationRulePage{items:DeviationRule[];page:number;size:number;total:number}
export interface DeviationRuleInput{routeId:string;routeVersion:string;toleranceMeters:number}
export interface DeviationVehicleState{vehicleId:string;state:DeviationState;availability:DeviationAvailability;tripId?:string|null;routeId?:string|null;routeVersion?:string|null;ruleId?:string|null;ruleVersion?:number|null;activeEpisodeId?:string|null;lastSourceTimestamp?:string|null}
export interface DeviationStatePage{items:DeviationVehicleState[];page:number;size:number;total:number}
export interface DeviationEpisode{id:string;vehicleId:string;tripId?:string|null;driverId?:string|null;routeId:string;routeVersion:string;ruleId:string;ruleVersion:number;configuredToleranceMeters:number;effectiveToleranceMeters:number;firstCandidatePositionId:string;confirmingPositionId:string;startSourceTimestamp:string;confirmationSourceTimestamp:string;endSourceTimestamp?:string|null;maximumDistanceMeters:number;eligibleOutsideSampleCount:number;severity:DeviationSeverity;reviewStatus?:string|null;reviewVersion:number;terminalOutcome?:string|null;disruptionId?:string|null}
export interface DeviationEpisodePage{items:DeviationEpisode[];nextCursor?:string|null}
export interface DeviationReview{id:string;episodeId:string;status:ReviewStatus;reason:ReviewReason;note?:string|null;reviewerId:string;reviewedAt:string;reviewVersion:number;compensatesReviewId?:string|null}
export interface DeviationReviewPage{items:DeviationReview[]}
export interface RuleFilters{lifecycle?:DeviationLifecycle;page:number;size:number}
export interface StateFilters{state?:DeviationState;page:number;size:number}
export interface EpisodeFilters{vehicleId?:string;tripId?:string;routeId?:string;severity?:DeviationSeverity;open?:boolean;from:string;to:string;cursor?:string;limit:number}
export interface ReviewInput{status:ReviewStatus;reason:ReviewReason;note?:string}
export interface ApiError{code?:string;message?:string;fieldErrors?:Record<string,string>}
