package com.transportlogistics.app.freight.manifest.adapters.inbound.web.controllers;
import com.transportlogistics.app.freight.manifest.adapters.inbound.web.dto.request.*;import com.transportlogistics.app.freight.manifest.adapters.inbound.web.dto.response.*;import com.transportlogistics.app.freight.manifest.adapters.inbound.web.mappers.CargoManifestWebMapper;import com.transportlogistics.app.freight.manifest.ports.inbound.CargoManifestUseCase;import com.transportlogistics.app.shared.utils.PrincipalUtils;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.security.Principal;import java.util.UUID;
@RestController @RequestMapping("/v1/freight/manifests")
public class CargoManifestController {private final CargoManifestUseCase manifests;private final CargoManifestWebMapper mapper;public CargoManifestController(CargoManifestUseCase manifests,CargoManifestWebMapper mapper){this.manifests=manifests;this.mapper=mapper;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public CargoManifestResponse create(@Valid @RequestBody CreateCargoManifestRequest request,Principal principal){return mapper.toResponse(manifests.create(new CargoManifestUseCase.CreateCommand(request.freightOrderId()),actor(principal)));}
 @GetMapping("/{id}") public CargoManifestResponse get(@PathVariable UUID id){return mapper.toResponse(manifests.get(id));}
 @GetMapping public CargoManifestPageResponse search(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int limit,@RequestParam(required=false)String search,@RequestParam(required=false)UUID freightOrderId,@RequestParam(required=false)Boolean finalized,@RequestParam(defaultValue="createdAt")String sort,@RequestParam(defaultValue="desc")String direction){var result=manifests.search(new CargoManifestUseCase.SearchQuery(search,freightOrderId,finalized,page,limit,sort,direction));return new CargoManifestPageResponse(result.content().stream().map(mapper::toResponse).toList(),result.page(),result.limit(),result.totalElements(),result.totalPages());}
 @PatchMapping("/{id}") public CargoManifestResponse update(@PathVariable UUID id,@Valid @RequestBody UpdateCargoManifestRequest request,Principal principal){return mapper.toResponse(manifests.update(id,new CargoManifestUseCase.UpdateCommand(request.version()),actor(principal)));}
 @PostMapping("/{id}/items") public CargoManifestResponse addItem(@PathVariable UUID id,@Valid @RequestBody CargoManifestItemRequest request,Principal principal){return mapper.toResponse(manifests.addItem(id,mapper.toCommand(request),actor(principal)));}
 @PatchMapping("/{id}/items/{itemId}") public CargoManifestResponse updateItem(@PathVariable UUID id,@PathVariable UUID itemId,@Valid @RequestBody CargoManifestItemRequest request,Principal principal){return mapper.toResponse(manifests.updateItem(id,itemId,mapper.toCommand(request),actor(principal)));}
 @GetMapping("/{id}/readiness") public CargoManifestReadinessResponse readiness(@PathVariable UUID id){return mapper.toResponse(manifests.validate(id));}
 @PostMapping("/{id}/finalize") public CargoManifestResponse finalizeManifest(@PathVariable UUID id,@Valid @RequestBody FinalizeCargoManifestRequest request,Principal principal){return mapper.toResponse(manifests.finalizeManifest(id,request.version(),actor(principal)));}
 private String actor(Principal principal){return PrincipalUtils.resolveActorName(principal,null);}}
