package com.transportlogistics.app.billing.adapters.inbound.web.controllers;
import com.transportlogistics.app.billing.adapters.inbound.web.dto.request.BillingRequests;
import com.transportlogistics.app.billing.adapters.inbound.web.dto.response.BillingResponse;
import com.transportlogistics.app.billing.adapters.inbound.web.mappers.BillingWebMapper;
import com.transportlogistics.app.billing.ports.inbound.TransportBillingUseCase;
import com.transportlogistics.app.tenancy.CurrentTenant;
import jakarta.validation.Valid;
import java.util.*;
import org.springframework.http.*;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/v1/billing/records") public class TransportBillingController {
 private final TransportBillingUseCase use;private final CurrentTenant tenants;private final BillingWebMapper mapper;
 public TransportBillingController(TransportBillingUseCase use,CurrentTenant tenants,BillingWebMapper mapper){this.use=use;this.tenants=tenants;this.mapper=mapper;}
 @GetMapping @PreAuthorize("hasAuthority('BILLING_VIEW')") public List<BillingResponse> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)UUID customer,@RequestParam(required=false)com.transportlogistics.app.billing.domain.TransportBillingRecord.Source.SourceType sourceType,@RequestParam(required=false)UUID sourceId,@RequestParam(required=false)com.transportlogistics.app.billing.domain.TransportBillingRecord.Lifecycle lifecycle,@RequestParam(required=false)com.transportlogistics.app.billing.domain.TransportBillingRecord.RecordType recordType,@RequestParam(required=false)String currency,@RequestParam(required=false)String costCentreCode,@RequestParam(required=false)java.time.OffsetDateTime createdFrom,@RequestParam(required=false)java.time.OffsetDateTime createdTo,@RequestParam(required=false)java.time.OffsetDateTime finalizedFrom,@RequestParam(required=false)java.time.OffsetDateTime finalizedTo,@RequestParam(defaultValue="CREATED")TransportBillingUseCase.Sort sort){return use.list(context().tenantId(),new TransportBillingUseCase.Filters(customer,sourceType,sourceId,lifecycle,recordType,currency,costCentreCode,createdFrom,createdTo,finalizedFrom,finalizedTo,sort),page,size).stream().map(mapper::response).toList();}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('BILLING_PREPARE')") public BillingResponse create(@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody BillingRequests.Create r){return mapper.response(use.create(context(),new TransportBillingUseCase.Create(r.sourceType(),r.sourceId(),r.currency(),r.replacementOfRecordId()),key));}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('BILLING_VIEW')") public BillingResponse get(@PathVariable UUID id){return mapper.response(use.get(context().tenantId(),id));}
 @PutMapping("/{id}/lines") @PreAuthorize("hasAuthority('BILLING_PREPARE')") public BillingResponse replace(@PathVariable UUID id,@Valid @RequestBody BillingRequests.Replacement r){var tax=new TransportBillingUseCase.Tax(r.tax().status(),r.tax().category(),r.tax().jurisdictionReference(),r.tax().taxableAmount(),r.tax().rate(),r.tax().taxAmount(),r.tax().exemptionReference(),r.tax().provenance(),r.tax().snapshotHash());var centres=r.costCentres().stream().map(c->new TransportBillingUseCase.CostCentre(c.id(),c.code(),c.allocationPercent(),c.description(),c.source())).toList();var lines=r.lines().stream().map(l->new TransportBillingUseCase.Line(l.id(),l.category(),l.reasonCode(),l.provenance(),l.quantity(),l.unitRate(),l.amount())).toList();return mapper.response(use.replace(context(),id,r.version(),new TransportBillingUseCase.Replacement(lines,tax,centres)));}
 @PostMapping("/{id}/validate") @PreAuthorize("hasAuthority('BILLING_PREPARE')") public BillingResponse validate(@PathVariable UUID id,@Valid @RequestBody BillingRequests.Version r){return mapper.response(use.validate(context(),id,r.version()));}
 @PostMapping("/{id}/approve") @PreAuthorize("hasAuthority('BILLING_APPROVE')") public BillingResponse approve(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody BillingRequests.Version r){return mapper.response(use.approve(context(),id,r.version(),key));}
 @PostMapping("/{id}/cancel") @PreAuthorize("hasAuthority('BILLING_PREPARE')") public BillingResponse cancel(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody BillingRequests.Reason r){return mapper.response(use.cancel(context(),id,r.version(),r.reason(),key));}
 @PostMapping("/{id}/finalize") @PreAuthorize("hasAuthority('BILLING_FINALIZE')") public BillingResponse finalizeRecord(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody BillingRequests.Version r){return mapper.response(use.finalizeRecord(context(),id,r.version(),key));}
 @PostMapping("/{id}/reversals") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('BILLING_PREPARE')") public BillingResponse reverse(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody BillingRequests.Reason r){return mapper.response(use.reverse(context(),id,r.version(),r.reason(),key));}
 @PostMapping("/{id}/export") @PreAuthorize("hasAuthority('BILLING_EXPORT')") public BillingResponse export(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody BillingRequests.Version r){return mapper.response(use.export(context(),id,r.version(),key));}
 @GetMapping("/{id}/history") @PreAuthorize("hasAuthority('BILLING_VIEW')") public List<BillingResponse.History> history(@PathVariable UUID id){return use.history(context().tenantId(),id).stream().map(h->new BillingResponse.History(h.id(),h.action(),h.fromState(),h.toState(),h.actorId(),h.detail(),h.createdAt())).toList();}
 private TransportBillingUseCase.Context context(){var c=tenants.required();return new TransportBillingUseCase.Context(c.tenantId(),c.actorId(),c.correlationId());}
}
