package com.transportlogistics.app.fleet.payroll.adapters.outbound.persistence;
import com.transportlogistics.app.fleet.payroll.domain.*;import com.transportlogistics.app.fleet.payroll.ports.outbound.DriverPayrollStore;
import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Component;import java.time.*;import java.util.*;
@Component class JpaDriverPayrollStore implements DriverPayrollStore{
 private final BatchJpaRepository batches;private final LineJpaRepository lines;private final WorkerMappingJpaRepository mappings;private final HistoryJpaRepository histories;private final MappingCommandJpaRepository mappingCommands;
 JpaDriverPayrollStore(BatchJpaRepository b,LineJpaRepository l,WorkerMappingJpaRepository m,HistoryJpaRepository h,MappingCommandJpaRepository commands){batches=b;lines=l;mappings=m;histories=h;mappingCommands=commands;}
 public Optional<DriverPayrollInputBatch>find(UUID t,UUID id){return batches.findByTenantIdAndId(t,id).map(e->batch(e,lines.findByTenantIdAndBatchIdOrderById(t,id)));}
 public Optional<DriverPayrollInputBatch>findByIdempotency(UUID t,String k){return batches.findByTenantIdAndIdempotencyKey(t,k).flatMap(e->find(t,e.getId()));}
 public Optional<DriverPayrollInputBatch>findByExportEvent(UUID t,UUID eventId){return batches.findByTenantIdAndExportEventId(t,eventId).flatMap(e->find(t,e.getId()));}
 public List<DriverPayrollInputBatch>list(UUID t,int p,int s){return batches.findByTenantIdOrderByCreatedAtDesc(t,PageRequest.of(p,s)).stream().map(e->batch(e,lines.findByTenantIdAndBatchIdOrderById(t,e.getId()))).toList();}
 public DriverPayrollInputBatch insert(DriverPayrollInputBatch b,String k){var e=entity(b);e.setIdempotencyKey(k);batches.saveAndFlush(e);saveLines(b);return find(b.tenantId(),b.id()).orElseThrow();}
 public void lockBatchCommand(UUID t,String key){batches.lockCommand(t,key);}
 public void lockReleasedSource(UUID t,UUID d,UUID trip,String category,UUID original){lines.lockReleasedSource(t,d,trip,category,original);}
 public DriverPayrollInputBatch update(DriverPayrollInputBatch b,long v){var e=batches.findByTenantIdAndId(b.tenantId(),b.id()).orElseThrow();if(e.getVersion()!=v)throw new com.transportlogistics.app.shared.domain.ConflictException("DRIVER_PAYROLL_STALE_VERSION","DRIVER_PAYROLL_STALE_VERSION");copy(b,e);batches.saveAndFlush(e);if(Set.of(DriverPayrollInputBatch.Lifecycle.DRAFT,DriverPayrollInputBatch.Lifecycle.VALIDATED).contains(b.lifecycle())){lines.deleteByTenantIdAndBatchId(b.tenantId(),b.id());saveLines(b);}return find(b.tenantId(),b.id()).orElseThrow();}
 public Optional<DriverPayrollWorkerMapping>mapping(UUID t,UUID d){return mappings.findByTenantIdAndDriverId(t,d).map(this::mapping);}
 public DriverPayrollWorkerMapping saveMapping(DriverPayrollWorkerMapping m,long v){var e=mappings.findByTenantIdAndDriverId(m.tenantId(),m.driverId()).orElseGet(DriverPayrollWorkerMappingEntity::new);if(e.getId()!=null&&e.getVersion()!=v)throw new com.transportlogistics.app.shared.domain.ConflictException("DRIVER_PAYROLL_STALE_VERSION","DRIVER_PAYROLL_STALE_VERSION");e.setId(m.id());e.setTenantId(m.tenantId());e.setDriverId(m.driverId());e.setExternalSystemAlias(m.externalSystemAlias());e.setExternalWorkerReference(m.externalWorkerReference());e.setActive(m.active());e.setUpdatedBy(m.updatedBy());e.setCreatedAt(m.createdAt());e.setUpdatedAt(m.updatedAt());return mapping(mappings.saveAndFlush(e));}
 public Optional<MappingCommandResult>mappingCommand(UUID t,String key){return mappingCommands.findByTenantIdAndIdempotencyKey(t,key).map(this::mappingCommand);}
 public void lockMappingCommand(UUID t,String key){mappingCommands.lock(t,key);}
 public MappingCommandResult saveMappingCommand(UUID t,UUID d,String key,String hash,DriverPayrollWorkerMapping result,UUID actor,OffsetDateTime at){var e=new DriverPayrollMappingCommandEntity();e.setId(UUID.randomUUID());e.setTenantId(t);e.setDriverId(d);e.setIdempotencyKey(key);e.setRequestHash(hash);e.setResultMappingId(result.id());e.setResultVersion(result.version());e.setResultExternalSystemAlias(result.externalSystemAlias());e.setResultExternalWorkerReference(result.externalWorkerReference());e.setResultActive(result.active());e.setResultUpdatedBy(result.updatedBy());e.setResultCreatedAt(result.createdAt());e.setResultUpdatedAt(result.updatedAt());e.setActorId(actor);e.setCreatedAt(at);return mappingCommand(mappingCommands.saveAndFlush(e));}
 public boolean releasedSourceExists(UUID t,UUID d,UUID trip,String category,UUID original,UUID excluding){var value=DriverPayrollInputLine.Category.valueOf(category);return original==null?lines.releasedRegularSourceExists(t,d,trip,value,excluding):lines.releasedCorrectionSourceExists(t,d,trip,value,original,excluding);}
 public boolean originalLineBelongsToBatch(UUID t,UUID original,UUID batch){return lines.existsByTenantIdAndIdAndBatchId(t,original,batch);}
 public List<History>history(UUID t,UUID b){return histories.findByTenantIdAndBatchIdOrderByCreatedAtAsc(t,b).stream().map(h->new History(h.getId(),h.getAction(),h.getFromState(),h.getToState(),h.getActorId(),h.getDetail(),h.getCreatedAt())).toList();}
 public void history(UUID t,UUID b,String a,String f,String to,UUID actor,String detail,OffsetDateTime at){var h=new DriverPayrollHistoryEntity();h.setId(UUID.randomUUID());h.setTenantId(t);h.setBatchId(b);h.setAction(a);h.setFromState(f);h.setToState(to);h.setActorId(actor);h.setDetail(detail);h.setCreatedAt(at);histories.save(h);}
 private void saveLines(DriverPayrollInputBatch b){for(var l:b.lines()){var e=new DriverPayrollLineEntity();e.setId(l.id());e.setTenantId(b.tenantId());e.setBatchId(b.id());e.setDriverId(l.driverId());e.setTripId(l.tripId());e.setTripNumber(l.tripNumber());e.setCategory(l.category());e.setReasonCode(l.reasonCode());e.setDescription(l.description());e.setQuantity(l.quantity());e.setUnit(l.unit());e.setRate(l.rate());e.setAmount(l.amount());e.setOriginalLineId(l.originalLineId());e.setSourceSnapshotHash(l.sourceSnapshotHash());e.setExternalWorkerReference(l.externalWorkerReference());lines.save(e);}}
 private DriverPayrollInputBatch batch(DriverPayrollBatchEntity e,List<DriverPayrollLineEntity> ls){var t=new DriverPayrollInputBatch.Totals(e.getTripEarnings(),e.getAllowances(),e.getOvertime(),e.getDeductions(),e.getProvisionalNetInput());return new DriverPayrollInputBatch(e.getId(),e.getTenantId(),e.getType(),e.getCorrectionOfBatchId(),e.getPeriodStart(),e.getPeriodEndExclusive(),e.getCutoffAt(),e.getCurrency(),e.getLifecycle(),ls.stream().map(this::line).toList(),t,e.getPreparedBy(),e.getApprovedBy(),e.getApprovedAt(),e.getExportConfigurationId(),e.getExportEventId(),e.getValidationHash(),e.getVersion(),e.getCreatedAt(),e.getUpdatedAt());}
 private DriverPayrollInputLine line(DriverPayrollLineEntity e){return new DriverPayrollInputLine(e.getId(),e.getDriverId(),e.getTripId(),e.getTripNumber(),e.getCategory(),e.getReasonCode(),e.getDescription(),e.getQuantity(),e.getUnit(),e.getRate(),e.getAmount(),e.getOriginalLineId(),e.getSourceSnapshotHash(),e.getExternalWorkerReference());}
 private DriverPayrollWorkerMapping mapping(DriverPayrollWorkerMappingEntity e){return new DriverPayrollWorkerMapping(e.getId(),e.getTenantId(),e.getDriverId(),e.getExternalSystemAlias(),e.getExternalWorkerReference(),e.isActive(),e.getVersion(),e.getUpdatedBy(),e.getCreatedAt(),e.getUpdatedAt());}
 private MappingCommandResult mappingCommand(DriverPayrollMappingCommandEntity e){return new MappingCommandResult(e.getRequestHash(),new DriverPayrollWorkerMapping(e.getResultMappingId(),e.getTenantId(),e.getDriverId(),e.getResultExternalSystemAlias(),e.getResultExternalWorkerReference(),e.isResultActive(),e.getResultVersion(),e.getResultUpdatedBy(),e.getResultCreatedAt(),e.getResultUpdatedAt()));}
 private DriverPayrollBatchEntity entity(DriverPayrollInputBatch b){var e=new DriverPayrollBatchEntity();e.setId(b.id());e.setTenantId(b.tenantId());copy(b,e);e.setCreatedAt(b.createdAt());return e;}
 private void copy(DriverPayrollInputBatch b,DriverPayrollBatchEntity e){e.setType(b.type());e.setCorrectionOfBatchId(b.correctionOfBatchId());e.setPeriodStart(b.periodStart());e.setPeriodEndExclusive(b.periodEndExclusive());e.setCutoffAt(b.cutoffAt());e.setCurrency(b.currency());e.setLifecycle(b.lifecycle());e.setTripEarnings(b.totals().tripEarnings());e.setAllowances(b.totals().allowances());e.setOvertime(b.totals().overtime());e.setDeductions(b.totals().deductions());e.setProvisionalNetInput(b.totals().provisionalNetInput());e.setPreparedBy(b.preparedBy());e.setApprovedBy(b.approvedBy());e.setApprovedAt(b.approvedAt());e.setExportConfigurationId(b.exportConfigurationId());e.setExportEventId(b.exportEventId());e.setValidationHash(b.validationHash());e.setUpdatedAt(b.updatedAt());}
}
