import { expect,test,type APIRequestContext } from '@playwright/test';import { randomUUID } from 'node:crypto';import { adminLogin,authenticatePage,headers,provisionUser,type AuthTokens } from '../../helpers/notificationTestApi';
const customerId='10000000-0000-0000-0000-000000000001',originLocationId='20000000-0000-0000-0000-000000000001',destinationLocationId='20000000-0000-0000-0000-000000000002';
async function order(api:APIRequestContext,tokens:AuthTokens){const marker=randomUUID().slice(0,8);const response=await api.post('/api/v1/freight/orders',{headers:headers(tokens),data:{customerId,originLocationId,destinationLocationId,requestedPickupAt:'2027-03-01T08:00:00Z',requestedDeliveryAt:'2027-03-02T08:00:00Z',serviceLevel:`SLA_${marker}`,priority:'HIGH',lines:[{description:`Cargo ${marker}`,quantity:3}]}});expect(response.status(),await response.text()).toBe(201);return response.json();}
async function manifest(api:APIRequestContext,tokens:AuthTokens){const savedOrder=await order(api,tokens);const response=await api.post('/api/v1/freight/manifests',{headers:headers(tokens),data:{freightOrderId:savedOrder.id}});expect(response.status(),await response.text()).toBe(201);return {order:savedOrder,manifest:await response.json()};}
const item=(version:number,lineId:string,extra={})=>({version,freightOrderLineId:lineId,description:'Traceable cargo',quantity:3,packingInformation:'Supplier wrapped unit',commodityClassification:'SUPPLIER.CODE',customsApplicable:false,hazardous:false,fragile:false,temperatureSensitive:false,...extra});
test.describe('US-25 cargo manifest management',()=>{
 test('E2E-P2-MAN-001: create Cargo Manifest from saved Freight Order',async({request})=>{const admin=await adminLogin(request);const value=await manifest(request,admin);expect(value.manifest.manifestNumber).toMatch(/^CM-\d{4}-\d{6}$/);expect(value.manifest.freightOrderId).toBe(value.order.id);expect(value.manifest.finalized).toBe(false)});
 test('E2E-P2-MAN-002: add and update identifiable cargo item',async({request})=>{const admin=await adminLogin(request);const value=await manifest(request,admin);let response=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/items`,{headers:headers(admin),data:item(value.manifest.version,value.order.lines[0].id)});expect(response.status(),await response.text()).toBe(200);let changed=await response.json();response=await request.patch(`/api/v1/freight/manifests/${value.manifest.id}/items/${changed.items[0].id}`,{headers:headers(admin),data:{...item(changed.version,value.order.lines[0].id),packingInformation:'Updated supplier wrapping'}});expect(response.status(),await response.text()).toBe(200);changed=await response.json();expect(changed.items[0].packingInformation).toBe('Updated supplier wrapping')});
 test('E2E-P2-MAN-003: conditional customs information',async({request})=>{const admin=await adminLogin(request);const value=await manifest(request,admin);const invalid=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/items`,{headers:headers(admin),data:item(0,value.order.lines[0].id,{customsApplicable:true})});expect(invalid.status()).toBe(200);const changed=await invalid.json();const blocked=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/finalize`,{headers:headers(admin),data:{version:changed.version}});expect(blocked.status()).toBe(400);expect((await blocked.json()).code).toBe('CARGO_MANIFEST_INCOMPLETE')});
 test('E2E-P2-MAN-004: conditional hazardous-goods information',async({request})=>{const admin=await adminLogin(request);const value=await manifest(request,admin);const added=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/items`,{headers:headers(admin),data:item(0,value.order.lines[0].id,{hazardous:true})});const changed=await added.json();const readiness=await request.get(`/api/v1/freight/manifests/${value.manifest.id}/readiness`,{headers:headers(admin)});expect((await readiness.json()).failures.map((f:{code:string})=>f.code)).toContain('HAZARDOUS_CLASSIFICATION_REQUIRED');expect(changed.items[0].hazardous).toBe(true)});
 test('E2E-P2-MAN-005: reject invalid or incomplete finalization',async({request})=>{const admin=await adminLogin(request);const value=await manifest(request,admin);const response=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/finalize`,{headers:headers(admin),data:{version:0}});expect(response.status()).toBe(400);expect((await response.json()).code).toBe('CARGO_MANIFEST_INCOMPLETE')});
 test('E2E-P2-MAN-006: finalize valid manifest and reject ordinary edits afterward',async({request})=>{const admin=await adminLogin(request);const value=await manifest(request,admin);let response=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/items`,{headers:headers(admin),data:item(0,value.order.lines[0].id)});let changed=await response.json();response=await request.post(`/api/v1/freight/manifests/${value.manifest.id}/finalize`,{headers:headers(admin),data:{version:changed.version}});expect(response.status(),await response.text()).toBe(200);changed=await response.json();expect(changed.finalized).toBe(true);const conflict=await request.patch(`/api/v1/freight/manifests/${value.manifest.id}`,{headers:headers(admin),data:{version:changed.version}});expect(conflict.status()).toBe(409);expect((await conflict.json()).code).toBe('CARGO_MANIFEST_FINALIZED')});
 test('E2E-P2-MAN-007: Manifest VIEW, MANAGE and FINALIZE RBAC',async({page,request},testInfo)=>{const admin=await adminLogin(request);const value=await manifest(request,admin);const viewer=await provisionUser(request,admin,`manview-${testInfo.project.name}-${randomUUID().slice(0,6)}`,['CARGO_MANIFEST_VIEW']);await authenticatePage(page,viewer.tokens);await page.goto('/freight/manifests');await expect(page.getByText(value.manifest.manifestNumber)).toBeVisible();await expect(page.getByRole('button',{name:'New cargo manifest'})).toHaveCount(0);const forbidden=await request.post('/api/v1/freight/manifests',{headers:headers(viewer.tokens),data:{freightOrderId:value.order.id}});expect(forbidden.status()).toBe(403);const unauthenticated=await request.get('/api/v1/freight/manifests');expect(unauthenticated.status()).toBe(401)});
});
