package com.transportlogistics.app.fleet.payroll.adapters.inbound.web.controllers;
import com.transportlogistics.app.fleet.payroll.ports.inbound.DriverPayrollUseCase;import com.transportlogistics.app.fleet.payroll.adapters.inbound.web.dto.request.DriverPayrollRequests;import com.transportlogistics.app.fleet.payroll.adapters.inbound.web.dto.response.DriverPayrollResponse;import com.transportlogistics.app.fleet.payroll.adapters.inbound.web.mappers.DriverPayrollWebMapper;import com.transportlogistics.app.tenancy.CurrentTenant;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/v1/drivers") public class DriverPayrollController{private final DriverPayrollUseCase use;private final CurrentTenant tenants;private final DriverPayrollWebMapper mapper;public DriverPayrollController(DriverPayrollUseCase u,CurrentTenant t,DriverPayrollWebMapper m){use=u;tenants=t;mapper=m;}
 @GetMapping("/payroll-input-batches")public List<DriverPayrollResponse>list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return use.list(context().tenantId(),page,size).stream().map(mapper::response).toList();}
 @PostMapping("/payroll-input-batches")@ResponseStatus(HttpStatus.CREATED)public DriverPayrollResponse create(@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody DriverPayrollRequests.Create r){return mapper.response(use.create(context(),new DriverPayrollUseCase.Create(r.type(),r.correctionOfBatchId(),r.periodStart(),r.periodEndExclusive(),r.cutoffAt(),r.currency()),key));}
 @GetMapping("/payroll-input-batches/{id}")public DriverPayrollResponse get(@PathVariable UUID id){return mapper.response(use.get(context().tenantId(),id));}
 @PutMapping("/payroll-input-batches/{id}/lines")public DriverPayrollResponse lines(@PathVariable UUID id,@Valid @RequestBody DriverPayrollRequests.ReplaceLines r){return mapper.response(use.replaceLines(context(),id,r.version(),r.lines().stream().map(this::line).toList()));}
 @PostMapping("/payroll-input-batches/{id}/validate")public DriverPayrollResponse validate(@PathVariable UUID id,@Valid @RequestBody DriverPayrollRequests.Version r){return mapper.response(use.validate(context(),id,r.version()));}
 @PostMapping("/payroll-input-batches/{id}/approve")public DriverPayrollResponse approve(@PathVariable UUID id,@Valid @RequestBody DriverPayrollRequests.Version r){return mapper.response(use.approve(context(),id,r.version()));}
 @PostMapping("/payroll-input-batches/{id}/export")public DriverPayrollResponse export(@PathVariable UUID id,@Valid @RequestBody DriverPayrollRequests.Version r){return mapper.response(use.export(context(),id,r.version()));}
 @PostMapping("/payroll-input-batches/{id}/corrections")@ResponseStatus(HttpStatus.CREATED)public DriverPayrollResponse correction(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody DriverPayrollRequests.Correction r){return mapper.response(use.correction(context(),id,new DriverPayrollUseCase.CreateCorrection(r.version(),r.periodStart(),r.periodEndExclusive(),r.cutoffAt(),r.currency(),r.lines().stream().map(this::line).toList()),key));}
 @GetMapping("/payroll-input-batches/{id}/history")public List<DriverPayrollResponse.History>history(@PathVariable UUID id){return use.history(context().tenantId(),id).stream().map(h->new DriverPayrollResponse.History(h.id(),h.action(),h.fromState(),h.toState(),h.actorId(),h.detail(),h.createdAt())).toList();}
 @GetMapping("/{driverId}/payroll-worker-mapping")public ResponseEntity<DriverPayrollResponse.Mapping>mapping(@PathVariable UUID driverId){return use.mapping(context().tenantId(),driverId).map(mapper::response).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());}
 @PutMapping("/{driverId}/payroll-worker-mapping")public DriverPayrollResponse.Mapping mapping(@PathVariable UUID driverId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody DriverPayrollRequests.Mapping r){return mapper.response(use.mapWorker(context(),driverId,new DriverPayrollUseCase.MappingCommand(r.externalSystemAlias(),r.externalWorkerReference(),r.active(),r.version()),key));}
 private DriverPayrollUseCase.LineCommand line(DriverPayrollRequests.Line r){return new DriverPayrollUseCase.LineCommand(r.id(),r.driverId(),r.tripId(),r.tripNumber(),r.category(),r.reasonCode(),r.description(),r.quantity(),r.unit(),r.rate(),r.amount(),r.originalLineId());}
 private DriverPayrollUseCase.Context context(){var c=tenants.required();return new DriverPayrollUseCase.Context(c.tenantId(),c.actorId(),c.username(),c.correlationId());}}
