import { theme, type ThemeConfig } from 'antd';

export const appTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  cssVar: { prefix: 'tl' },
  token: {
    colorPrimary: '#147D92',
    colorInfo: '#147D92',
    colorSuccess: '#2F855A',
    colorWarning: '#B7791F',
    colorError: '#C53F3F',
    colorText: '#172B4D',
    colorTextSecondary: '#5D6B7E',
    colorBgLayout: '#F4F7FA',
    colorBgContainer: '#FFFFFF',
    colorBorder: '#D8E0E8',
    colorBorderSecondary: '#E8EDF2',
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    controlHeight: 36,
    controlHeightLG: 42,
    fontSize: 14,
    fontSizeSM: 12,
    lineHeight: 1.5,
    padding: 16,
    paddingSM: 12,
    margin: 16,
    marginSM: 12,
    fontFamily: "Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  components: {
    Layout: {
      headerBg: '#FFFFFF',
      siderBg: '#102A43',
      bodyBg: '#F4F7FA',
      headerHeight: 72,
    },
    Menu: {
      darkItemBg: '#102A43',
      darkSubMenuItemBg: '#0C2237',
      darkItemColor: '#C7D5E0',
      darkItemHoverBg: '#183F5D',
      darkItemSelectedBg: '#147D92',
      darkItemSelectedColor: '#FFFFFF',
      itemBorderRadius: 8,
      itemHeight: 42,
      itemMarginBlock: 4,
      itemMarginInline: 8,
    },
    Card: {
      headerFontSize: 15,
      headerHeight: 52,
      bodyPadding: 20,
    },
    Table: {
      headerBg: '#F7F9FB',
      headerColor: '#465B70',
      rowHoverBg: '#F2F8F9',
      borderColor: '#E8EDF2',
      cellPaddingBlock: 13,
      cellPaddingInline: 14,
      cellPaddingBlockSM: 9,
      cellPaddingInlineSM: 12,
    },
    Button: {
      borderRadius: 8,
      primaryShadow: 'none',
      defaultShadow: 'none',
    },
    Input: {
      activeBorderColor: '#147D92',
      hoverBorderColor: '#3D96A6',
      activeShadow: '0 0 0 2px rgba(20, 125, 146, 0.14)',
    },
    InputNumber: {
      activeBorderColor: '#147D92',
      hoverBorderColor: '#3D96A6',
      activeShadow: '0 0 0 2px rgba(20, 125, 146, 0.14)',
    },
    Select: {
      activeBorderColor: '#147D92',
      hoverBorderColor: '#3D96A6',
      activeOutlineColor: 'rgba(20, 125, 146, 0.14)',
    },
    DatePicker: {
      activeBorderColor: '#147D92',
      hoverBorderColor: '#3D96A6',
      activeShadow: '0 0 0 2px rgba(20, 125, 146, 0.14)',
    },
    Tabs: {
      itemSelectedColor: '#147D92',
      itemActiveColor: '#0D6677',
      itemHoverColor: '#147D92',
      inkBarColor: '#147D92',
      horizontalItemGutter: 28,
    },
    Breadcrumb: {
      linkColor: '#5D6B7E',
      lastItemColor: '#172B4D',
    },
    Statistic: {
      titleFontSize: 12,
      contentFontSize: 28,
    },
    Progress: {
      defaultColor: '#147D92',
      remainingColor: '#E8EDF2',
    },
    Modal: {
      titleFontSize: 17,
    },
    Drawer: {
      footerPaddingBlock: 12,
      footerPaddingInline: 20,
    },
  },
};
