package com.transportlogistics.app.freight.manifest.adapters.outbound.persistence;
import com.transportlogistics.app.freight.manifest.domain.model.CargoManifest; import com.transportlogistics.app.freight.manifest.ports.inbound.CargoManifestUseCase; import com.transportlogistics.app.freight.manifest.ports.outbound.CargoManifestRepository;
import jakarta.persistence.criteria.Predicate; import org.springframework.data.domain.*; import org.springframework.stereotype.Component; import java.util.*;
@Component class CargoManifestPersistenceAdapter implements CargoManifestRepository {
 private static final Set<String> SORTABLE=Set.of("manifestNumber","freightOrderNumber","createdAt","updatedAt","finalizedAt"); private final CargoManifestJpaRepository repository;private final CargoManifestPersistenceMapper mapper;
 CargoManifestPersistenceAdapter(CargoManifestJpaRepository repository,CargoManifestPersistenceMapper mapper){this.repository=repository;this.mapper=mapper;}
 public CargoManifest save(CargoManifest manifest){return mapper.toDomain(repository.saveAndFlush(mapper.toEntity(manifest)));} public Optional<CargoManifest> findById(UUID id){return repository.findById(id).map(mapper::toDomain);}
 public CargoManifestUseCase.PageResult<CargoManifest> search(CargoManifestUseCase.SearchQuery q){var spec=(org.springframework.data.jpa.domain.Specification<CargoManifestEntity>)(root,query,cb)->{var p=new ArrayList<Predicate>();if(q.freightOrderId()!=null)p.add(cb.equal(root.get("freightOrderId"),q.freightOrderId()));if(q.finalized()!=null)p.add(q.finalized()?cb.isNotNull(root.get("finalizedAt")):cb.isNull(root.get("finalizedAt")));if(q.search()!=null&&!q.search().isBlank()){String v="%"+q.search().trim().toLowerCase()+"%";p.add(cb.or(cb.like(cb.lower(root.get("manifestNumber")),v),cb.like(cb.lower(root.get("freightOrderNumber")),v)));}return cb.and(p.toArray(Predicate[]::new));};String property=SORTABLE.contains(q.sort())?q.sort():"createdAt";Sort.Direction d="asc".equalsIgnoreCase(q.direction())?Sort.Direction.ASC:Sort.Direction.DESC;var page=repository.findAll(spec,PageRequest.of(Math.max(q.page(),0),Math.min(Math.max(q.limit(),1),100),Sort.by(d,property)));return new CargoManifestUseCase.PageResult<>(page.stream().map(mapper::toDomain).toList(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages());}
}
