import { EyeOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, App, Button, Descriptions, Drawer, Empty, Form, Input, Modal, Select, Space, Steps, Table, Tag, Typography } from 'antd';
import axios from 'axios';
import { useState } from 'react';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { z } from 'zod';
import { vehicleApi } from '../../fleet/vehicleMaster/api/vehicleApi';
import { trackingApi } from '../api/trackingApi';
import { useProviderConnections, useProviderTypes } from '../hooks/useProviderConnections';
import type { TrackingDevice } from '../types';

const deviceSchema=z.object({providerConnectionId:z.string().min(1,'Select an active provider connection'),externalDeviceReference:z.string().trim().min(1,'Enter the external device reference').max(160),hardwareSerialReference:z.string().trim().max(160).optional()});
const bindingSchema=z.object({providerConnectionId:z.string().min(1,'Select an active provider connection'),externalDeviceReference:z.string().trim().min(1,'Enter the external device reference').max(160)});
const associationSchema=z.object({vehicleId:z.string().min(1,'Select a Vehicle')});
type DeviceValues=z.infer<typeof deviceSchema>;type BindingValues=z.infer<typeof bindingSchema>;type AssociationValues=z.infer<typeof associationSchema>;
type ApiError={code?:string;message?:string};
const lifecycleColor:Record<string,string>={DRAFT:'default',ACTIVE:'success',DISABLED:'warning',RETIRED:'error'};
const deviceKeys={all:['tracking','devices'] as const,detail:(id:string)=>['tracking','devices',id] as const};

export function DeviceManagement({canManage}:{canManage:boolean}){
 const {message,notification}=App.useApp();const cache=useQueryClient();const [createOpen,setCreateOpen]=useState(false);const [selectedId,setSelectedId]=useState<string>();const [bindOpen,setBindOpen]=useState(false);const [associateOpen,setAssociateOpen]=useState(false);
 const list=useQuery({queryKey:deviceKeys.all,queryFn:trackingApi.devices});const detail=useQuery({queryKey:deviceKeys.detail(selectedId??''),queryFn:()=>trackingApi.device(selectedId!),enabled:Boolean(selectedId)});const providers=useProviderConnections(0,100);const providerTypes=useProviderTypes();const vehicles=useQuery({queryKey:['fleet','vehicles','tracking-options'],queryFn:vehicleApi.list});
 const activeProviders=(providers.data?.items??[]).filter(item=>item.lifecycle==='ACTIVE');
 const createForm=useForm<DeviceValues>({resolver:zodResolver(deviceSchema),defaultValues:{providerConnectionId:'',externalDeviceReference:'',hardwareSerialReference:''}});const bindForm=useForm<BindingValues>({resolver:zodResolver(bindingSchema),defaultValues:{providerConnectionId:'',externalDeviceReference:''}});const associationForm=useForm<AssociationValues>({resolver:zodResolver(associationSchema),defaultValues:{vehicleId:''}});
 const selectedProviderId=useWatch({control:bindForm.control,name:'providerConnectionId'});
 const refresh=async(id?:string)=>{await cache.invalidateQueries({queryKey:deviceKeys.all});if(id)await cache.invalidateQueries({queryKey:deviceKeys.detail(id)});};
 const safeError=async(error:unknown,fallback:string,id?:string)=>{const body=axios.isAxiosError<ApiError>(error)?error.response?.data:undefined;notification.error({message:fallback,description:body?.code==='TRACKING_STALE_VERSION'?'This device changed since you opened it. Latest data has been reloaded.':body?.message??'The backend safely rejected this operation.'});await cache.invalidateQueries({queryKey:['tracking','provider-connections']});if(id)await refresh(id);};
 const create=useMutation({mutationFn:(value:DeviceValues)=>{const provider=activeProviders.find(item=>item.id===value.providerConnectionId)!;return trackingApi.createDevice({externalDeviceReference:value.externalDeviceReference,providerAlias:provider.providerAlias,hardwareSerialReference:value.hardwareSerialReference||undefined});},onSuccess:async device=>{await refresh(device.id);setSelectedId(device.id);setCreateOpen(false);createForm.reset();void message.success('Draft tracking device created');},onError:error=>void safeError(error,'Device creation failed')});
 const bind=useMutation({mutationFn:async(value:BindingValues)=>{const current=await trackingApi.device(selectedId!);return trackingApi.bindDevice({deviceId:current.id,input:{providerConnectionId:value.providerConnectionId,externalDeviceReference:value.externalDeviceReference,safeConfiguration:{},lifecycle:'ACTIVE',...(current.currentProviderBinding?{currentBindingVersion:current.currentProviderBinding.bindingVersion}:{})}});},onSuccess:async()=>{await refresh(selectedId);setBindOpen(false);bindForm.reset();void message.success(detail.data?.currentProviderBinding?'Provider rebound':'Provider bound');},onError:error=>void safeError(error,'Provider binding failed',selectedId)});
 const associate=useMutation({mutationFn:(value:AssociationValues)=>trackingApi.associate(selectedId!,value.vehicleId),onSuccess:async()=>{await refresh(selectedId);setAssociateOpen(false);associationForm.reset();void message.success('Vehicle associated');},onError:error=>void safeError(error,'Vehicle association failed',selectedId)});
 const lifecycle=useMutation({mutationFn:async(action:'activate'|'disable'|'retire')=>trackingApi.lifecycle(await trackingApi.device(selectedId!),action),onSuccess:async(value,action)=>{await refresh(value.id);void message.success(action==='retire'?'Device retired':`Device ${action}d`);},onError:error=>void safeError(error,'Device lifecycle action failed',selectedId)});
 const selected=detail.data;const binding=selected?.currentProviderBinding;const association=selected?.currentVehicleAssociation;const ready=Boolean(binding?.bindingLifecycle==='ACTIVE'&&binding.connectionLifecycle==='ACTIVE'&&association);const terminal=selected?.lifecycle==='RETIRED';
 const openBinding=()=>{bindForm.reset({providerConnectionId:binding?.providerConnectionId??'',externalDeviceReference:''});setBindOpen(true);};
 const confirmLifecycle=(action:'activate'|'disable'|'retire')=>Modal.confirm({title:action==='retire'?'Retire device?':action==='disable'?'Disable device?':'Activate device?',content:action==='retire'?'This action is permanent. Historical Tracking data is preserved.':action==='disable'?'Live ingestion stops until the device is reactivated. Historical Tracking data remains available.':'The prepared provider binding and Vehicle association will become operational.',okText:action==='retire'?'Retire':action==='disable'?'Disable':'Activate Device',okButtonProps:{danger:action==='retire'},onOk:()=>lifecycle.mutateAsync(action)});
 const providerOptions=activeProviders.map(item=>({value:item.id,label:`${item.displayName} · ${item.providerType} · ${item.providerAlias} · ${item.lifecycle}`}));const vehicleOptions=(vehicles.data??[]).filter(item=>item.active).map(item=>({value:item.id,label:`${item.registrationNumber}${item.manufacturer||item.model?` · ${[item.manufacturer,item.model].filter(Boolean).join(' ')}`:''}`}));
 const selectedProvider=activeProviders.find(item=>item.id===selectedProviderId);const selectedCapabilities=(providerTypes.data??[]).find(item=>item.providerType===selectedProvider?.providerType)?.capabilities??[];
 return <Space direction="vertical" size="large" style={{width:'100%'}}>
  <Space style={{justifyContent:'space-between',width:'100%'}} wrap><Typography.Paragraph type="secondary" style={{margin:0}}>Register devices as DRAFT, then bind a provider, associate a Vehicle, and activate explicitly. Credentials are never displayed.</Typography.Paragraph><Space><Button icon={<ReloadOutlined/>} onClick={()=>void list.refetch()}>Refresh</Button>{canManage&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setCreateOpen(true)}>Add Device</Button>}</Space></Space>
  {canManage&&!providers.isLoading&&!activeProviders.length&&<Alert type="warning" showIcon message="Create and activate a provider connection before onboarding a device." action={<Link to="/tracking/provider-connections">Provider Connections</Link>}/>} 
  {list.isError&&<Alert type="error" showIcon message="Tracking devices could not be loaded" description="Check your access and backend connection, then retry." action={<Button onClick={()=>void list.refetch()}>Retry</Button>}/>} 
  <Table<TrackingDevice> rowKey="id" loading={list.isLoading} dataSource={list.data??[]} scroll={{x:900}} pagination={false} locale={{emptyText:<Empty description="No tracking devices configured">{canManage&&<Button type="primary" onClick={()=>setCreateOpen(true)}>Add Device</Button>}</Empty>}} columns={[{title:'External reference',dataIndex:'externalReference'},{title:'Provider',dataIndex:'providerAlias'},{title:'Lifecycle',dataIndex:'lifecycle',render:value=><Tag color={lifecycleColor[value]}>{value}</Tag>},{title:'Vehicle',render:(_,item)=>item.currentVehicleAssociation?(vehicleOptions.find(option=>option.value===item.currentVehicleAssociation?.vehicleId)?.label??'Associated Vehicle'):'Not associated'},{title:'Last receipt',dataIndex:'lastSeenAt',render:value=>value?new Date(value).toLocaleString():'Never'},{title:'Actions',fixed:'right',render:(_,item)=><Button size="small" icon={<EyeOutlined/>} onClick={()=>setSelectedId(item.id)}>Details</Button>}]} />
  <Modal title="Add tracking device" open={createOpen} onCancel={()=>setCreateOpen(false)} onOk={createForm.handleSubmit(value=>create.mutate(value))} okText="Create DRAFT" confirmLoading={create.isPending}><Form layout="vertical"><Field id="create-provider" label="Active provider connection" error={createForm.formState.errors.providerConnectionId?.message}><Controller name="providerConnectionId" control={createForm.control} render={({field})=><Select {...field} id="create-provider" options={providerOptions} placeholder="Select provider" notFoundContent="No active provider connections"/>}/></Field>{!activeProviders.length&&<Alert type="warning" showIcon message="Create and activate a provider connection before onboarding a device."/>}<Field id="create-external-reference" label="External device reference" error={createForm.formState.errors.externalDeviceReference?.message}><Controller name="externalDeviceReference" control={createForm.control} render={({field})=><Input {...field} id="create-external-reference" maxLength={160}/>} /></Field><Field id="create-hardware-reference" label="Hardware serial reference" error={createForm.formState.errors.hardwareSerialReference?.message}><Controller name="hardwareSerialReference" control={createForm.control} render={({field})=><Input {...field} id="create-hardware-reference" maxLength={160}/>} /></Field></Form></Modal>
  <Drawer title="Tracking device details" width={720} open={Boolean(selectedId)} onClose={()=>setSelectedId(undefined)}>{detail.isLoading?<Typography.Text>Loading device details…</Typography.Text>:detail.isError?<Alert type="error" showIcon message="Device details unavailable" description="It may not exist in your Tenant, or your access changed."/>:selected&&<Space direction="vertical" size="large" style={{width:'100%'}}><Steps size="small" current={selected.lifecycle==='ACTIVE'?3:association?2:binding?1:0} items={[{title:'Device created'},{title:'Provider binding'},{title:'Vehicle association'},{title:'Activated'}]}/><Descriptions bordered size="small" column={1} items={[{key:'lifecycle',label:'Device lifecycle',children:<Tag color={lifecycleColor[selected.lifecycle]}>{selected.lifecycle}</Tag>},{key:'provider',label:'Provider connection',children:binding?`${binding.providerDisplayName} · ${binding.providerType} · ${binding.providerAlias}`:'Not bound'},{key:'binding',label:'Binding lifecycle',children:binding?<Tag color={lifecycleColor[binding.bindingLifecycle]}>{binding.bindingLifecycle}</Tag>:'Not bound'},{key:'external',label:'External device reference',children:binding?.maskedExternalDeviceReference??selected.externalReference},{key:'vehicle',label:'Vehicle association',children:association?(vehicleOptions.find(item=>item.value===association.vehicleId)?.label??'Associated Vehicle'):'Not associated'},{key:'connectivity',label:'Device connectivity',children:selected.lastSeenAt?'Telemetry received':'No telemetry received'},{key:'seen',label:'Last seen',children:selected.lastSeenAt?new Date(selected.lastSeenAt).toLocaleString():'Never'}]}/>{canManage&&!terminal&&<Space wrap>{!binding&&<Button onClick={openBinding}>Bind Provider</Button>}{binding&&<Button onClick={openBinding}>Rebind Provider</Button>}{selected.lifecycle==='DRAFT'&&!association&&<Button onClick={()=>setAssociateOpen(true)}>Associate Vehicle</Button>}{selected.lifecycle==='DRAFT'&&<Button type="primary" disabled={!ready} onClick={()=>confirmLifecycle('activate')}>Activate Device</Button>}{selected.lifecycle==='ACTIVE'&&<Button onClick={()=>confirmLifecycle('disable')}>Disable</Button>}{selected.lifecycle==='DISABLED'&&<Button type="primary" disabled={!ready} onClick={()=>confirmLifecycle('activate')}>Reactivate</Button>}<Button danger onClick={()=>confirmLifecycle('retire')}>Retire Device</Button></Space>}{selected.lifecycle==='DRAFT'&&!ready&&<Alert type="info" showIcon message="Activation not ready" description="Bind an active provider connection and associate a Vehicle before activation."/>}{terminal&&<Alert type="warning" showIcon message="Retired device" description="Retirement is permanent. Historical Tracking data remains available and no further device mutations are allowed."/>}</Space>}</Drawer>
  <Modal title={binding?'Rebind provider':'Bind provider'} open={bindOpen} onCancel={()=>setBindOpen(false)} onOk={bindForm.handleSubmit(value=>bind.mutate(value))} confirmLoading={bind.isPending} okText={binding?'Rebind':'Bind Provider'}><Form layout="vertical"><Field id="bind-provider" label="Active provider connection" error={bindForm.formState.errors.providerConnectionId?.message}><Controller name="providerConnectionId" control={bindForm.control} render={({field})=><Select {...field} id="bind-provider" options={providerOptions} placeholder="Select provider"/>}/></Field>{selectedCapabilities.includes('DISCOVERY')?<Button onClick={()=>selectedProvider&&trackingApi.discoverProviderDevices(selectedProvider.id).then(result=>Modal.info({title:'Discovered devices',content:result.devices.length?result.devices.map(item=><div key={item.maskedExternalDeviceReference}>{item.displayName??'Device'} · {item.maskedExternalDeviceReference}</div>):'No devices discovered'}))}>Discover Devices</Button>:<Typography.Paragraph type="secondary">This provider requires manual device entry.</Typography.Paragraph>}<Field id="bind-external-reference" label="External device reference" error={bindForm.formState.errors.externalDeviceReference?.message}><Controller name="externalDeviceReference" control={bindForm.control} render={({field})=><Input {...field} id="bind-external-reference" maxLength={160}/>} /></Field></Form></Modal>
  <Modal title="Associate Vehicle" open={associateOpen} onCancel={()=>setAssociateOpen(false)} onOk={associationForm.handleSubmit(value=>associate.mutate(value))} confirmLoading={associate.isPending}><Form layout="vertical"><Field id="associate-vehicle" label="Vehicle" error={associationForm.formState.errors.vehicleId?.message}><Controller name="vehicleId" control={associationForm.control} render={({field})=><Select {...field} id="associate-vehicle" showSearch optionFilterProp="label" options={vehicleOptions} placeholder="Select by registration"/>}/></Field></Form></Modal>
 </Space>;
}

function Field({id,label,error,children}:{id:string;label:string;error?:string;children:React.ReactNode}){return <Form.Item htmlFor={id} label={label} validateStatus={error?'error':undefined} help={error}>{children}</Form.Item>;}
