import { zodResolver } from '@hookform/resolvers/zod';
import { Alert,Button,Checkbox,Flex,Form,Input,InputNumber,Select,Space,Typography } from 'antd';
import { Controller,useFieldArray,useForm,useWatch } from 'react-hook-form';
import type { Geofence,GeofenceInput } from '../types';
import { geofenceSchema,type GeofenceFormValues } from '../validation/geofenceSchema';
import { PolygonPreview } from './PolygonPreview';

const blank={longitude:0,latitude:0};
export function GeofenceEditor({geofence,loading,onSubmit}:{geofence?:Geofence;loading:boolean;onSubmit:(value:GeofenceInput)=>Promise<void>}){
 const defaultValues:GeofenceFormValues=geofence?{name:geofence.name,type:geofence.type,locationId:geofence.locationId??'',polygon:geofence.polygon,alertPolicy:geofence.alertPolicy}:{name:'',type:'DEPOT',locationId:'',polygon:[{longitude:79.85,latitude:6.9},{longitude:79.86,latitude:6.9},{longitude:79.855,latitude:6.91}],alertPolicy:{alertOnEntry:true,alertOnExit:true}};
 const {control,handleSubmit,formState:{errors},setValue}=useForm<GeofenceFormValues>({resolver:zodResolver(geofenceSchema),defaultValues});
 const {fields,append,remove,move}=useFieldArray({control,name:'polygon'});const type=useWatch({control,name:'type'});const polygon=useWatch({control,name:'polygon'});const entry=useWatch({control,name:'alertPolicy.alertOnEntry'});
 return <Form layout="vertical" onFinish={()=>void handleSubmit(onSubmit)()}>
  <Controller name="name" control={control} render={({field})=><Form.Item label="Name" required validateStatus={errors.name?'error':undefined} help={errors.name?.message}><Input aria-label="Name" {...field}/></Form.Item>}/>
  <Controller name="type" control={control} render={({field})=><Form.Item label="Geofence type" required><Select aria-label="Geofence type" {...field} onChange={value=>{field.onChange(value);if(value==='UNAUTHORIZED_ZONE'){setValue('locationId',undefined);setValue('alertPolicy.alertOnEntry',true);}}} options={[{value:'DEPOT',label:'Depot'},{value:'CUSTOMER_SITE',label:'Customer site'},{value:'UNAUTHORIZED_ZONE',label:'Unauthorized zone'}]}/></Form.Item>}/>
  {type!=='UNAUTHORIZED_ZONE'&&<Controller name="locationId" control={control} render={({field})=><Form.Item label="Organization location ID" required validateStatus={errors.locationId?'error':undefined} help={errors.locationId?.message??'Current Organization UI exposes no reusable location selector; enter the same-Tenant location UUID.'}><Input aria-label="Organization location ID" {...field} value={field.value??''}/></Form.Item>}/>} 
  <Typography.Title level={3}>Alert policy</Typography.Title><Space direction="vertical"><Controller name="alertPolicy.alertOnEntry" control={control} render={({field})=><Checkbox checked={type==='UNAUTHORIZED_ZONE'||entry} disabled={type==='UNAUTHORIZED_ZONE'} onChange={event=>field.onChange(event.target.checked)}>Alert on entry{type==='UNAUTHORIZED_ZONE'?' (mandatory)':''}</Checkbox>}/><Controller name="alertPolicy.alertOnExit" control={control} render={({field})=><Checkbox checked={field.value} onChange={event=>field.onChange(event.target.checked)}>Alert on exit</Checkbox>}/></Space>
  <Typography.Title level={3}>Polygon vertices</Typography.Title><Typography.Paragraph type="secondary">Enter an open ring in longitude/latitude order. Do not repeat the first point.</Typography.Paragraph>
  {typeof errors.polygon?.message==='string'&&<Alert type="error" showIcon message={errors.polygon.message}/>}<Flex vertical gap={8}>{fields.map((field,index)=><Flex key={field.id} gap={8} align="start" wrap><Typography.Text style={{paddingTop:6,width:24}}>{index+1}</Typography.Text><Controller name={`polygon.${index}.longitude`} control={control} render={({field:input})=><Form.Item label={index===0?'Longitude':undefined} validateStatus={errors.polygon?.[index]?.longitude?'error':undefined} help={errors.polygon?.[index]?.longitude?.message}><InputNumber aria-label={`Vertex ${index+1} longitude`} min={-180} max={180} {...input}/></Form.Item>}/><Controller name={`polygon.${index}.latitude`} control={control} render={({field:input})=><Form.Item label={index===0?'Latitude':undefined} validateStatus={errors.polygon?.[index]?.latitude?'error':undefined} help={errors.polygon?.[index]?.latitude?.message}><InputNumber aria-label={`Vertex ${index+1} latitude`} min={-90} max={90} {...input}/></Form.Item>}/><Space><Button aria-label={`Move vertex ${index+1} up`} disabled={index===0} onClick={()=>move(index,index-1)}>Move Up</Button><Button aria-label={`Move vertex ${index+1} down`} disabled={index===fields.length-1} onClick={()=>move(index,index+1)}>Move Down</Button><Button aria-label={`Remove vertex ${index+1}`} disabled={fields.length<=3} onClick={()=>remove(index)}>Remove</Button></Space></Flex>)}</Flex>
  <Button onClick={()=>append(blank)} disabled={fields.length>=100}>Add Vertex</Button><Typography.Title level={3}>Local polygon preview</Typography.Title><PolygonPreview vertices={polygon}/><Form.Item style={{marginTop:20}}><Button type="primary" htmlType="submit" loading={loading} disabled={loading}>Save geofence</Button></Form.Item>
 </Form>;
}
