package com.transportlogistics.app.freight.manifest.application;
import com.transportlogistics.app.freight.manifest.domain.model.CargoManifest;import com.transportlogistics.app.freight.manifest.ports.inbound.CargoManifestUseCase;import com.transportlogistics.app.freight.manifest.ports.outbound.*;import com.transportlogistics.app.freight.order.ports.inbound.FreightOrderLookup;import com.transportlogistics.app.shared.domain.*;import org.junit.jupiter.api.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class CargoManifestServiceTest {CargoManifestRepository repository=mock(CargoManifestRepository.class);CargoManifestNumberGenerator numbers=()->"CM-2026-000001";FreightOrderLookup orders=mock(FreightOrderLookup.class);CargoManifestTransaction tx=new CargoManifestTransaction(){public<T>T execute(java.util.function.Supplier<T> operation){return operation.get();}};CargoManifestService service;UUID orderId=UUID.randomUUID(),lineId=UUID.randomUUID();
 @BeforeEach void setup(){service=new CargoManifestService(repository,numbers,orders,tx,Clock.fixed(Instant.parse("2026-08-25T00:00:00Z"),ZoneOffset.UTC));when(orders.find(orderId)).thenReturn(Optional.of(new FreightOrderLookup.OrderReference(orderId,"FO-2026-000001",List.of(new FreightOrderLookup.ExpectedLine(lineId,"Cargo",BigDecimal.TEN)))));when(repository.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void createsThroughFocusedOrderBoundary(){var created=service.create(new CargoManifestUseCase.CreateCommand(orderId),"operator");assertEquals(orderId,created.freightOrderId());assertEquals("CM-2026-000001",created.manifestNumber());verify(orders).find(orderId);}
 @Test void rejectsUnknownOrder(){assertThrows(NotFoundException.class,()->service.create(new CargoManifestUseCase.CreateCommand(UUID.randomUUID()),"operator"));}
 @Test void addsValidatesAndFinalizesTransactionally(){var manifest=service.create(new CargoManifestUseCase.CreateCommand(orderId),"operator");when(repository.findById(manifest.id())).thenReturn(Optional.of(manifest));var added=service.addItem(manifest.id(),new CargoManifestUseCase.ItemCommand(0L,lineId,"Cargo",BigDecimal.TEN,"Wrapped","CODE",false,null,false,null,null),"editor");when(repository.findById(manifest.id())).thenReturn(Optional.of(added));assertTrue(service.validate(manifest.id()).ready());var finalized=service.finalizeManifest(manifest.id(),added.version(),"finalizer");assertTrue(finalized.finalized());}
 @Test void staleMutationConflicts(){var manifest=service.create(new CargoManifestUseCase.CreateCommand(orderId),"operator");when(repository.findById(manifest.id())).thenReturn(Optional.of(manifest));assertThrows(ConflictException.class,()->service.update(manifest.id(),new CargoManifestUseCase.UpdateCommand(99L),"editor"));}
}
