import { useState } from 'react';
import { Alert,Button,Card,Descriptions,Input,Modal,Select,Space,Table,Tag,Timeline,Typography } from 'antd';
import { useAuth } from '../../../../auth/AuthContext';
import { useFuelExceptions } from '../hooks/useFuelExceptions';
import type { FuelException,FuelExceptionCategory } from '../types/fuelExceptions';
const categories:FuelExceptionCategory[]=['SUSPECTED_FUEL_LOSS','INCORRECT_READING','SUDDEN_PRICE_CHANGE','EMERGENCY_REFUEL','FUEL_CARD_POLICY_DEVIATION','NEGATIVE_BUNKER_BALANCE'];
export default function FuelExceptionsPage(){const {hasPermission}=useAuth();const [selected,setSelected]=useState<string>();const q=useFuelExceptions(selected);const [open,setOpen]=useState(false);const [form,setForm]=useState({category:'SUSPECTED_FUEL_LOSS' as FuelExceptionCategory,impact:'MEDIUM',sourceType:'FUEL_ISSUE',sourceId:'',summary:''});const [text,setText]=useState('');const detail=q.detail.data;return <Space direction="vertical" style={{width:'100%'}}>
 <Alert showIcon type="info" message="Fuel exceptions are review records" description="Use suspected, unexplained, policy deviation, and review-required language. A case is not a punitive finding."/>
 {hasPermission('FUEL_EXCEPTION_MANAGE')&&<Button type="primary" onClick={()=>setOpen(true)}>Create Fuel exception</Button>}
 <Card><Table<FuelException> rowKey="id" loading={q.list.isLoading} dataSource={q.list.data??[]} onRow={r=>({onClick:()=>setSelected(r.id)})} columns={[{title:'Category',dataIndex:'category'},{title:'Impact',dataIndex:'impact',render:v=><Tag>{v}</Tag>},{title:'Lifecycle',dataIndex:'lifecycle'},{title:'Source',render:(_,r)=><>{r.sourceType}<br/><Typography.Text type="secondary">{r.sourceId}</Typography.Text></>},{title:'Review',render:(_,r)=>r.reviewRequired?'Review required':'Reviewed'},{title:'Handoff',dataIndex:'handoffStatus'},{title:'Occurred',dataIndex:'occurredAt'},{title:'Created',dataIndex:'createdAt'}]}/></Card>
 {detail&&<Card title={detail.value.summary} extra={<Button onClick={()=>setSelected(undefined)}>Close</Button>}><Descriptions bordered size="small" items={[{key:'category',label:'Category',children:detail.value.category},{key:'impact',label:'Impact',children:detail.value.impact},{key:'lifecycle',label:'Lifecycle',children:detail.value.lifecycle},{key:'handoff',label:'Operations handoff',children:detail.value.handoffStatus},{key:'source',label:'Safe source',children:`${detail.value.sourceType} · ${detail.value.sourceId}`}]}/><Space wrap style={{marginTop:16}}>{hasPermission('FUEL_EXCEPTION_MANAGE')&&detail.value.lifecycle==='OPEN'&&<Button onClick={()=>q.command.mutate({id:detail.value.id,action:'review',value:{version:detail.value.version,reason:'Review started'}})}>Start review</Button>}{hasPermission('FUEL_EXCEPTION_ESCALATE')&&['HIGH','CRITICAL'].includes(detail.value.impact)&&['NOT_REQUIRED','FAILED'].includes(detail.value.handoffStatus)&&<Button onClick={()=>q.command.mutate({id:detail.value.id,action:'escalate',value:{version:detail.value.version,reason:'Cross-module coordination required'}})}>{detail.value.handoffStatus==='FAILED'?'Retry Operations handoff':'Escalate to Operations'}</Button>}</Space>
 <Typography.Title level={5}>Append-only notes and evidence</Typography.Title><Space.Compact style={{width:'100%'}}><Input aria-label="Case note" maxLength={2000} showCount value={text} onChange={e=>setText(e.target.value)}/><Button disabled={!text||!hasPermission('FUEL_EXCEPTION_MANAGE')} onClick={()=>{q.note.mutate({id:detail.value.id,text});setText('');}}>Add note</Button></Space.Compact><Timeline style={{marginTop:20}} items={[...detail.evidence.map(e=>({children:`Evidence: ${e.summary}`})),...detail.notes.map(n=>({children:`Note: ${n.note}`})),...detail.history.map(h=>({children:`${h.action}${h.detail?` — ${h.detail}`:''}`}))]}/>
 <Typography.Title level={5}>Corrections</Typography.Title>{detail.corrections.map(c=><Card size="small" key={c.id}>{c.correctionType} <Tag>{c.status}</Tag>{c.status==='AWAITING_APPROVAL'&&hasPermission('FUEL_EXCEPTION_APPROVE')&&<Space><Button onClick={()=>q.reviewCorrection.mutate({id:detail.value.id,correctionId:c.id,action:'approve',version:c.version,reason:'Independently approved'})}>Approve</Button><Button danger onClick={()=>q.reviewCorrection.mutate({id:detail.value.id,correctionId:c.id,action:'reject',version:c.version,reason:'Returned for review'})}>Reject</Button></Space>}</Card>)}</Card>}
 <Modal title="Create Fuel exception" open={open} onCancel={()=>setOpen(false)} onOk={()=>q.create.mutate({...form,occurredAt:new Date().toISOString(),safeMetadata:{}},{onSuccess:()=>setOpen(false)})}><Space direction="vertical" style={{width:'100%'}}><Select aria-label="Category" value={form.category} onChange={category=>setForm({...form,category})} options={categories.map(value=>({value}))}/><Select aria-label="Impact" value={form.impact} onChange={impact=>setForm({...form,impact})} options={['LOW','MEDIUM','HIGH','CRITICAL'].map(value=>({value}))}/><Input aria-label="Source type" value={form.sourceType} onChange={e=>setForm({...form,sourceType:e.target.value})}/><Input aria-label="Source UUID" value={form.sourceId} onChange={e=>setForm({...form,sourceId:e.target.value})}/><Input.TextArea aria-label="Review summary" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></Space></Modal>
 </Space>}
