import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { deliveryOrderApi } from '../api/deliveryOrderApi';
import type { DeliveryOrderFilters, DeliveryOrderPayload } from '../types/deliveryOrder';

export const deliveryOrderKeys = { all: ['delivery-orders'] as const, list: (filters: DeliveryOrderFilters) => ['delivery-orders', 'list', filters] as const, detail: (id?: string) => ['delivery-orders', 'detail', id] as const };
export const useDeliveryOrders = (filters: DeliveryOrderFilters) => useQuery({ queryKey: deliveryOrderKeys.list(filters), queryFn: () => deliveryOrderApi.search(filters) });
export const useDeliveryOrder = (id?: string) => useQuery({ queryKey: deliveryOrderKeys.detail(id), queryFn: () => deliveryOrderApi.get(id!), enabled: Boolean(id) });
export const useDeliveryCustomers = () => useQuery({ queryKey: ['delivery-orders', 'customers'], queryFn: deliveryOrderApi.customers });
export const useDeliveryLocations = () => useQuery({ queryKey: ['delivery-orders', 'locations'], queryFn: deliveryOrderApi.locations });
export function useSaveDeliveryOrder(id?: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: DeliveryOrderPayload) => id ? deliveryOrderApi.update(id, payload) : deliveryOrderApi.create(payload), onSuccess: () => client.invalidateQueries({ queryKey: deliveryOrderKeys.all }) }); }
export function useValidateDeliveryReadiness() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, version }: { id: string; version: number }) => deliveryOrderApi.validateReadiness(id, version), onSuccess: () => client.invalidateQueries({ queryKey: deliveryOrderKeys.all }) }); }
export const useDeliveryProof = (id?: string, enabled = true) => useQuery({ queryKey: ['delivery-orders', 'proof', id], queryFn: () => deliveryOrderApi.getProof(id!), enabled: Boolean(id) && enabled, retry: false });
export function useCreateDeliveryProof() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: string; payload: object }) => deliveryOrderApi.createProof(id, payload), onSuccess: (_, v) => client.invalidateQueries({ queryKey: ['delivery-orders', 'proof', v.id] }) }); }
export function useAddDeliveryEvidence() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, podVersion, type, file, barcodeValue, captureSource }: { id: string; podVersion: number; type: import('../types/deliveryOrder').PodEvidenceType; file?: File; barcodeValue?: string; captureSource?: string }) => deliveryOrderApi.addEvidence(id, podVersion, type, file, barcodeValue, captureSource), onSuccess: (_, v) => client.invalidateQueries({ queryKey: ['delivery-orders', 'proof', v.id] }) }); }
export function useFinalizeDeliveryProof() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, deliveryVersion, podVersion }: { id: string; deliveryVersion: number; podVersion: number }) => deliveryOrderApi.finalizeProof(id, deliveryVersion, podVersion), onSuccess: (_, v) => { void client.invalidateQueries({ queryKey: deliveryOrderKeys.all }); void client.invalidateQueries({ queryKey: ['delivery-orders', 'proof', v.id] }); } }); }
