import { useState } from 'react';
import { Alert, App as AntApp, Button, Card, DatePicker, Flex, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Typography } from 'antd';
import dayjs from 'dayjs';
import { Navigate } from 'react-router-dom';
import { isAxiosError } from 'axios';
import { useAuth } from '../auth/AuthContext';
import { useFuelPrices, useFuelVendors, useSaveFuelPrice } from './hooks/useFuelPurchases';
import type { FuelPrice } from './purchaseTypes';

export default function FuelPricePage(){const {hasPermission}=useAuth();const {message}=AntApp.useApp();const prices=useFuelPrices(),vendors=useFuelVendors();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<FuelPrice>();const [form]=Form.useForm();const save=useSaveFuelPrice(editing?.id);if(!hasPermission('FUEL_PRICE_VIEW'))return <Navigate to="/workspace" replace/>;
 const show=(price?:FuelPrice)=>{setEditing(price);form.setFieldsValue(price?{...price,effectiveFrom:dayjs(price.effectiveFrom),effectiveTo:price.effectiveTo?dayjs(price.effectiveTo):null}:{fuelType:'DIESEL',currencyCode:'LKR',active:true});setOpen(true)};
 const submit=async()=>{try{const v=await form.validateFields();await save.mutateAsync({...v,effectiveFrom:v.effectiveFrom.format('YYYY-MM-DD'),effectiveTo:v.effectiveTo?.format('YYYY-MM-DD')??null});void message.success(editing?'Fuel price updated':'Fuel price created');setOpen(false);form.resetFields()}catch{/* validation or API shown */}};const error=isAxiosError<{message?:string}>(save.error)?save.error.response?.data?.message:undefined;
 return <Flex vertical gap={18}><Flex justify="space-between"><div><Typography.Title level={3}>Fuel prices</Typography.Title><Typography.Text type="secondary">Expected vendor prices used for purchase variance comparison.</Typography.Text></div>{hasPermission('FUEL_PRICE_MANAGE')&&<Button type="primary" onClick={()=>show()}>Add price</Button>}</Flex>{prices.isError&&<Alert type="error" showIcon message="Fuel prices could not be loaded"/>}<Card><Table rowKey="id" loading={prices.isLoading} dataSource={prices.data??[]} columns={[{title:'Vendor',dataIndex:'vendorId',render:id=>vendors.data?.find(v=>v.id===id)?.name??id},{title:'Fuel type',dataIndex:'fuelType'},{title:'Unit price',dataIndex:'unitPrice'},{title:'Currency',dataIndex:'currencyCode'},{title:'Effective from',dataIndex:'effectiveFrom'},{title:'Effective to',dataIndex:'effectiveTo',render:v=>v??'Open ended'},{title:'Active',dataIndex:'active',render:v=>v?'Yes':'No'},{title:'Actions',render:(_,row)=>hasPermission('FUEL_PRICE_MANAGE')?<Button type="link" onClick={()=>show(row)}>Edit</Button>:null}]}/></Card><Modal open={open} title={editing?'Edit fuel price':'Add fuel price'} onCancel={()=>setOpen(false)} onOk={()=>void submit()} confirmLoading={save.isPending}>{error&&<Alert type="error" showIcon message={error}/>}<Form form={form} layout="vertical"><Form.Item name="vendorId" label="Vendor" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(vendors.data??[]).map(v=>({value:v.id,label:`${v.code} — ${v.name}`}))}/></Form.Item><Space align="start"><Form.Item name="fuelType" label="Fuel type" rules={[{required:true}]}><Select style={{width:160}} options={['DIESEL','PETROL','ELECTRIC','OTHER'].map(value=>({value}))}/></Form.Item><Form.Item name="unitPrice" label="Unit price" rules={[{required:true},{type:'number',min:0.0001}]}><InputNumber min={0} precision={4}/></Form.Item><Form.Item name="currencyCode" label="Currency" rules={[{required:true,pattern:/^[A-Za-z]{3}$/}]}><Input maxLength={3} style={{width:90}}/></Form.Item></Space><Space><Form.Item name="effectiveFrom" label="Effective from" rules={[{required:true}]}><DatePicker/></Form.Item><Form.Item name="effectiveTo" label="Effective to"><DatePicker/></Form.Item></Space><Form.Item name="active" label="Active" valuePropName="checked"><Switch/></Form.Item></Form></Modal></Flex>}
