import {App} from 'antd';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import IdleMonitoringPage from './IdleMonitoringPage';

const permissions=vi.hoisted(()=>new Set<string>());
const current=vi.hoisted(()=>({id:'session-a'}));
const idleApi=vi.hoisted(()=>({states:vi.fn(),episodes:vi.fn(),episode:vi.fn(),evidence:vi.fn()}));
vi.mock('../../../auth/AuthContext',()=>({useAuth:()=>({user:current,hasPermission:(p:string)=>permissions.has(p)})}));
vi.mock('./api',()=>({idleMonitoringApi:idleApi}));
const state={vehicleId:'vehicle-1',vehicleLabel:null,state:'UNSUPPORTED',capabilityState:'UNKNOWN',latestSourceTimestamp:null,candidateStartedAt:null,lastQualifyingAt:null,creditedSeconds:0,evidenceCount:0,version:0,fuelEstimateAvailability:'UNAVAILABLE',fuelEstimateSource:null};
const episode={id:'episode-1',vehicleId:'vehicle-1',vehicleLabel:null,lifecycle:'CLOSED',startSourceTimestamp:'2026-09-01T00:00:00Z',confirmedAt:'2026-09-01T00:05:00Z',lastSourceTimestamp:'2026-09-01T00:06:00Z',endSourceTimestamp:'2026-09-01T00:06:00Z',endReason:'ENGINE_STOPPED',confirmedDurationSeconds:300,evidenceCount:2,version:1,fuelEstimateAvailability:'UNAVAILABLE',fuelEstimateSource:null};
function view(path='/tracking/idle-monitoring'){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<MemoryRouter initialEntries={[path]}><QueryClientProvider client={client}><App><Routes><Route path="/tracking/idle-monitoring" element={<IdleMonitoringPage/>}/><Route path="/tracking/idle-monitoring/episodes" element={<IdleMonitoringPage/>}/><Route path="/tracking/idle-monitoring/episodes/:episodeId" element={<IdleMonitoringPage/>}/></Routes></App></QueryClientProvider></MemoryRouter>)}
describe('IdleMonitoringPage',()=>{beforeEach(()=>{permissions.clear();current.id='session-a';idleApi.states.mockReset().mockResolvedValue({items:[state],nextCursor:'next'});idleApi.episodes.mockReset().mockResolvedValue({items:[episode],nextCursor:null});idleApi.episode.mockReset().mockResolvedValue(episode);idleApi.evidence.mockReset().mockResolvedValue({items:[{id:'evidence-1',sourceTimestamp:'2026-09-01T00:00:00Z',evidenceQuality:'QUALIFYING',creditedDeltaSeconds:30,recordedAt:'2026-09-01T00:00:01Z'}]})});
it('enforces state and episode permissions independently',async()=>{permissions.add('IDLE_EVENT_VIEW');view();expect(screen.getByText('Current-state access denied')).toBeInTheDocument();expect(idleApi.states).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Episode history'}));expect(await screen.findByText('Choose a range of up to 31 days, then apply filters')).toBeInTheDocument()});
it('renders unknown state and unavailable fuel truthfully without candidate history',async()=>{permissions.add('IDLE_MONITOR_VIEW');view();expect(await screen.findByText('Unsupported')).toBeInTheDocument();expect(screen.getAllByText('Unavailable').length).toBeGreaterThan(0);expect(screen.queryByRole('button',{name:'Episode history'})).not.toBeInTheDocument();expect(screen.queryByText(/litres|fuel saved/i)).not.toBeInTheDocument()});
it('validates 31-day ranges and resets opaque paging when filters are applied',async()=>{permissions.add('IDLE_EVENT_VIEW');view('/tracking/idle-monitoring/episodes');fireEvent.change(screen.getByLabelText('Idle episode range from'),{target:{value:'2026-01-01T00:00'}});fireEvent.change(screen.getByLabelText('Idle episode range to'),{target:{value:'2026-03-01T00:00'}});expect(screen.getByText('The range cannot exceed 31 days.')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Idle episode range to'),{target:{value:'2026-01-02T00:00'}});fireEvent.click(screen.getByRole('button',{name:'Apply filters'}));await waitFor(()=>expect(idleApi.episodes).toHaveBeenCalledWith(expect.objectContaining({limit:50,cursor:undefined}),expect.anything()))});
it('renders confirmed detail and minimized evidence without sensitive facts',async()=>{permissions.add('IDLE_EVENT_VIEW');view('/tracking/idle-monitoring/episodes/episode-1');expect(await screen.findByText('Minimized immutable evidence')).toBeInTheDocument();expect(await screen.findByText('Qualifying')).toBeInTheDocument();expect(screen.queryByText(/coordinate|provider payload|credential|driver/i)).not.toBeInTheDocument()});
});
