import {expect,request,test} from '@playwright/test';
import {seedIdleMonitoring} from '../../utils/idleMonitoringAcceptanceFixture';
const backend=process.env.REAL_E2E_BACKEND_URL??'http://localhost:8088',suffix=`us51-${Date.now()}`;type Auth={accessToken:string;refreshToken:string};let stateViewer:Auth,eventViewer:Auth,tenantB:Auth,fixture:{vehicleId:string;episodeId:string};
test.describe.serial('US-51 idle monitoring CS06 real PostgreSQL journey',()=>{test.beforeAll(async()=>{const root=await authorized(await login());const tenant=await root.post('/api/e2e/tenant-fixtures',{data:{suffix}});expect(tenant.status(),await tenant.text()).toBe(201);const created=await tenant.json() as {tenantId:string;username:string;password:string};const admin=await login(created.username,created.password),api=await authorized(admin);stateViewer=await createUser(api,['IDLE_MONITOR_VIEW'],'state');eventViewer=await createUser(api,['IDLE_EVENT_VIEW'],'event');const device=await api.post('/api/v1/tracking/devices',{data:{externalDeviceReference:`idle-${suffix}`,providerAlias:'FIXTURE'}});expect(device.status(),await device.text()).toBe(201);fixture=seedIdleMonitoring(created.tenantId,(await device.json() as {id:string}).id);const other=await root.post('/api/e2e/tenant-fixtures',{data:{suffix:`${suffix}-b`}});const foreign=await other.json() as {username:string;password:string};tenantB=await login(foreign.username,foreign.password);await api.dispose();await root.dispose()});
test('state permission shows truthful read-only state only',async({page})=>{await auth(page,stateViewer);await page.goto('/tracking/idle-monitoring');const row=page.getByRole('row',{name:new RegExp(fixture.vehicleId)});await expect(row).toContainText('Normal');await expect(page.getByRole('button',{name:'Episode history'})).toHaveCount(0);await expect(page.getByRole('button',{name:/create|edit|delete|acknowledge/i})).toHaveCount(0)});
test('event permission shows bounded confirmed history, detail and minimized evidence',async({page})=>{await auth(page,eventViewer);await page.goto('/tracking/idle-monitoring/episodes');await page.getByLabel('Idle episode range from').fill(local(new Date(Date.now()-86_400_000)));await page.getByLabel('Idle episode range to').fill(local(new Date(Date.now()+60_000)));await page.getByRole('button',{name:'Apply filters'}).click();await page.getByRole('button',{name:`View idle episode ${fixture.episodeId}`}).click();await expect(page.getByRole('heading',{name:'Minimized immutable evidence'})).toBeVisible();await expect(page.getByText('Qualifying')).toBeVisible();await expect(page.locator('body')).not.toContainText(/latitude|longitude|credential|driver|provider payload/i)});
test('client enforces 31-day range and candidates are absent from history controls',async({page})=>{await auth(page,eventViewer);await page.goto('/tracking/idle-monitoring/episodes');await page.getByLabel('Idle episode range from').fill('2026-01-01T00:00');await page.getByLabel('Idle episode range to').fill('2026-03-01T00:00');await expect(page.getByText('The range cannot exceed 31 days.')).toBeVisible();await expect(page.getByText(/candidate/i)).toHaveCount(0)});
test('foreign Tenant receives non-disclosing absence',async()=>{const api=await authorized(tenantB),response=await api.get(`/api/v1/tracking/idle-monitoring/episodes/${fixture.episodeId}`);expect(response.status()).toBe(404);expect(await response.text()).not.toContain(fixture.vehicleId);await api.dispose()});});
async function login(username=process.env.E2E_ADMIN_USERNAME??'admin',password=process.env.E2E_ADMIN_PASSWORD??'AdminPass!2026'){const api=await request.newContext({baseURL:backend}),r=await api.post('/api/auth/login',{data:{username,password}});expect(r.status(),await r.text()).toBe(200);const result=await r.json() as Auth;await api.dispose();return result}function authorized(a:Auth){return request.newContext({baseURL:backend,extraHTTPHeaders:{Authorization:`Bearer ${a.accessToken}`}})}async function createUser(api:Awaited<ReturnType<typeof request.newContext>>,permissions:string[],kind:string){const marker=`${kind}-${Date.now()}-${Math.random().toString(16).slice(2)}`,role=await api.post('/api/roles',{data:{name:`US51 ${marker}`,active:true,permissions}});expect(role.status(),await role.text()).toBe(201);const username=`us51-${marker}`,password=`Us51Viewer!${Date.now()}`,user=await api.post('/api/users',{data:{username,email:`${username}@example.test`,password,firstName:'US51',lastName:kind,active:true,roleIds:[(await role.json() as {id:string}).id]}});expect(user.status(),await user.text()).toBe(201);return login(username,password)}async function auth(page:import('@playwright/test').Page,a:Auth){await page.addInitScript(v=>{localStorage.setItem('transport.accessToken',v.accessToken);localStorage.setItem('transport.refreshToken',v.refreshToken)},a)}function local(d:Date){return new Date(d.getTime()-d.getTimezoneOffset()*60_000).toISOString().slice(0,16)}
