import {expect,request,test} from '@playwright/test';
import {seedJourneyReplayEvidence} from '../../utils/journeyReplayAcceptanceFixture';
const backend=process.env.REAL_E2E_BACKEND_URL??'http://localhost:8088',suffix=`us53-${Date.now()}`;
type Auth={accessToken:string;refreshToken:string};
let viewer:Auth,unauthorized:Auth,vehicleId:string,from:string,to:string;

test.describe.serial('US-53 Journey Replay CS05 real Chromium journey',()=>{
  test.beforeAll(async()=>{const root=await authorized(await login());const response=await root.post('/api/e2e/tenant-fixtures',{data:{suffix}});expect(response.status(),await response.text()).toBe(201);const fixture=await response.json() as {tenantId:string;username:string;password:string};viewer=await login(fixture.username,fixture.password);unauthorized=await createUser(await authorized(viewer),[]);({vehicleId,from,to}=seedJourneyReplayEvidence(fixture.tenantId));await root.dispose()});
  test('1/5 exposes permission-gated navigation and keeps selectors out of the URL',async({page})=>{await authenticate(page,viewer);await page.goto('/tracking/journey-replay');await expect(page.getByRole('heading',{name:'Journey Replay'})).toBeVisible();await expect(page.getByRole('menuitem',{name:'Journey Replay'})).toBeVisible();expect(page.url()).not.toContain(vehicleId)});
  test('2/5 loads real Timescale points and deterministic stop evidence',async({page})=>{await load(page);await expect(page.getByRole('img',{name:/Journey map with 8 chronological points/})).toBeVisible();await expect(page.getByText(/5 min · 6 points/)).toBeVisible();await expect(page.getByText(/TIME GAP/)).toBeVisible()});
  test('3/5 provides paused keyboard-operable synchronized playback',async({page})=>{await load(page);await expect(page.getByText(/Replay paused at 1x — point 1 of 8/)).toBeVisible();await page.getByRole('button',{name:'Play replay'}).click();await expect(page.getByText(/Replay playing/)).toBeVisible();await page.getByRole('button',{name:'Pause replay'}).click();const speed=page.getByRole('combobox',{name:'Playback speed'});await speed.locator('xpath=../..').click();await page.getByText('8x',{exact:true}).last().click();await expect(page.getByText(/Replay paused at 8x/)).toBeVisible()});
  test('4/5 hides coordinates until explicit expansion and remains usable on phone width',async({page})=>{await page.setViewportSize({width:390,height:844});await load(page);expect(await page.locator('body').innerText()).not.toContain('Coordinates:');await page.getByRole('button',{name:'Show coordinates'}).click();await expect(page.getByText(/Coordinates:/)).toBeVisible();await expect(page.getByLabel('Replay timeline seek')).toBeVisible()});
  test('5/5 guards an unauthorized deep link and literal API',async({page})=>{const api=await authorized(unauthorized);const denied=await api.post('/api/v1/tracking/journey-replays/points/query',{data:{vehicleId,from,to}});expect(denied.status()).toBe(403);await api.dispose();await authenticate(page,unauthorized);await page.goto('/tracking/journey-replay');await expect(page).toHaveURL(/\/$/);await expect(page.getByText(vehicleId)).toHaveCount(0)});
});

async function load(page:import('@playwright/test').Page){await authenticate(page,viewer);await page.goto('/tracking/journey-replay');await page.getByLabel('Vehicle ID').fill(vehicleId);await page.getByLabel('Range start').fill(local(from));await page.getByLabel('Range end').fill(local(to));await page.getByRole('button',{name:'Load replay'}).click()}
function local(value:string){const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16)}
async function login(username=process.env.E2E_ADMIN_USERNAME??'admin',password=process.env.E2E_ADMIN_PASSWORD??'AdminPass!2026'){const api=await request.newContext({baseURL:backend});const response=await api.post('/api/auth/login',{data:{username,password}});expect(response.status(),await response.text()).toBe(200);const auth=await response.json() as Auth;await api.dispose();return auth}
function authorized(auth:Auth){return request.newContext({baseURL:backend,extraHTTPHeaders:{Authorization:`Bearer ${auth.accessToken}`}})}
async function createUser(api:Awaited<ReturnType<typeof request.newContext>>,permissions:string[]){const role=await api.post('/api/roles',{data:{name:`US53 none ${suffix}`,active:true,permissions}});expect(role.status(),await role.text()).toBe(201);const roleId=(await role.json() as {id:string}).id,username=`us53-none-${Date.now()}`,password=`Us53None!${Date.now()}`;const user=await api.post('/api/users',{data:{username,email:`${username}@example.test`,password,firstName:'US53',lastName:'None',active:true,roleIds:[roleId]}});expect(user.status(),await user.text()).toBe(201);await api.dispose();return login(username,password)}
async function authenticate(page:import('@playwright/test').Page,auth:Auth){await page.addInitScript(value=>{localStorage.setItem('transport.accessToken',value.accessToken);localStorage.setItem('transport.refreshToken',value.refreshToken)},auth)}
