import { createHmac } from 'node:crypto';
import { expect, request, test } from '@playwright/test';

const backend=process.env.REAL_E2E_BACKEND_URL??'http://localhost:8088';const secret='us48-controlled-provider-secret';const provider='FIXTURE';const providerKeyId='us48-fixture-key';const suffix=`us48-${Date.now()}`;
type Auth={accessToken:string;refreshToken:string};type Device={id:string;externalReference:string;providerAlias:string;lifecycle:string;version:number};type Association={id:string};type Position={id:string;vehicleId:string;providerMessageId:string;sourceTimestamp:string;ordering:string};
type State={vehicleId:string;latestTrusted?:Position;freshness:string;connectivity:string};type Page<T>={items:T[];nextCursor?:string};
type ConnectionPage={items:Array<{id:string;providerAlias:string;lifecycle:string}>};

test.describe.serial('US-48 controlled signed-provider real PostgreSQL acceptance',()=>{
 let admin:Auth;let limited:Auth;let tenantB:Auth;let device:Device;let association:Association;let vehicleA:string;let vehicleB:string;let staleVehicle:string;let vehicleCandidates:string[];let newest:Position;let fixtureConnectionId:string;
 test.beforeAll(async()=>{admin=await login();const api=await authorized(admin);const connections=await json<ConnectionPage>(api.get('/api/v1/tracking/provider-connections?page=0&size=100'));fixtureConnectionId=connections.items.find(item=>item.providerAlias===provider&&item.lifecycle==='ACTIVE')!.id;expect(fixtureConnectionId).toBeTruthy();const categories=entities(await json(api.get('/api/vehicle-categories')));const types=entities(await json(api.get('/api/vehicle-types')));expect(categories.length).toBeGreaterThan(0);expect(types.length).toBeGreaterThan(0);vehicleCandidates=[];for(let index=0;index<3;index++){const response=await api.post('/api/vehicles',{data:{registrationNumber:`US48-${suffix}-${index}`.toUpperCase(),categoryId:categories[0].id,typeId:types[0].id,chassisNumber:`US48-CH-${suffix}-${index}`.toUpperCase(),engineNumber:`US48-EN-${suffix}-${index}`.toUpperCase(),manufacturer:'Acceptance',model:'US48',manufactureYear:2026,ownershipType:'COMPANY_OWNED',operationalStatus:'AVAILABLE',active:true}});expect(response.status(),await response.text()).toBe(201);vehicleCandidates.push((await response.json() as {id:string}).id);}limited=await createUser(api,['TRACKING_VIEW']);const tenant=await api.post('/api/e2e/tenant-fixtures',{data:{suffix}});expect(tenant.status(),await tenant.text()).toBe(201);const other=await tenant.json() as {username:string;password:string};tenantB=await login(other.username,other.password);await api.dispose();});

 test('1/10 creates a DRAFT device, binds, associates, then activates',async({page})=>{const api=await authorized(admin);let response=await api.post('/api/v1/tracking/devices',{data:{externalDeviceReference:`fixture-${suffix}`,providerAlias:provider,hardwareSerialReference:`serial-${suffix}`}});expect(response.status(),await response.text()).toBe(201);device=await response.json() as Device;response=await api.post(`/api/v1/tracking/devices/${device.id}/provider-bindings`,{data:{providerConnectionId:fixtureConnectionId,externalDeviceReference:`fixture-${suffix}`,safeConfiguration:{},lifecycle:'ACTIVE'}});expect(response.status(),await response.text()).toBe(201);for(const candidate of vehicleCandidates){response=await api.post(`/api/v1/tracking/devices/${device.id}/associations`,{data:{vehicleId:candidate,effectiveFrom:new Date(Date.now()-60_000).toISOString()}});if(response.status()===201){vehicleA=candidate;association=await response.json() as Association;break;}expect((await response.json() as {code:string}).code).toBe('TRACKING_VEHICLE_ALREADY_ASSOCIATED');}expect(vehicleA).toBeTruthy();device=await json<Device>(api.get(`/api/v1/tracking/devices/${device.id}`));response=await api.post(`/api/v1/tracking/devices/${device.id}/activate`,{data:{version:device.version}});expect(response.status(),await response.text()).toBe(200);device=await response.json() as Device;await authenticate(page,admin);await page.goto('/tracking/vehicles');await page.getByRole('tab',{name:'Tracking devices'}).click();await expect(page.getByText(device.externalReference)).toBeVisible();await api.dispose();});
 test('2/10 accepts a valid fresh signed point as latest trusted state',async({page})=>{const source=new Date().toISOString();newest=await send(device.id,'fresh',2,source,6.9271);const api=await authorized(admin);const state=await json<State>(api.get(`/api/v1/tracking/vehicles/${vehicleA}/latest`));expect(state.latestTrusted?.providerMessageId).toBe(newest.providerMessageId);await authenticate(page,admin);await page.goto('/tracking/vehicles');const vehicleRow=page.getByRole('row',{name:new RegExp(vehicleA)});await expect(vehicleRow.getByText('CURRENT',{exact:true})).toBeVisible();await expect(vehicleRow.getByRole('cell',{name:'±5 m'})).toBeVisible();await api.dispose();});
 test('3/10 makes exact signed replay idempotent',async()=>{const source=newest.sourceTimestamp;const first=await send(device.id,'replay',3,source,6.9272);const second=await send(device.id,'replay',3,source,6.9272);expect(second.id).toBe(first.id);});
 test('4/10 retains an older point without replacing newer trusted state',async()=>{const older=await send(device.id,'older',1,new Date(Date.parse(newest.sourceTimestamp)-30_000).toISOString(),6.926);expect(older.ordering).toBe('OUT_OF_ORDER');const api=await authorized(admin);const state=await json<State>(api.get(`/api/v1/tracking/vehicles/${vehicleA}/latest`));expect(state.latestTrusted?.providerMessageId).not.toBe(older.providerMessageId);await api.dispose();});
 test('5/10 rejects invalid coordinates without a history fact',async()=>{const response=await signed({deviceId:device.id,providerMessageId:'invalid',providerSequence:5,sourceTimestamp:new Date().toISOString(),latitude:91,longitude:79.8612,horizontalAccuracyMeters:5});expect(response.status()).toBe(400);expect((await response.json() as {code:string}).code).toBe('TRACKING_POSITION_INVALID');await response.dispose();});
 test('6/10 renders stale data explicitly as LAST KNOWN with timestamp and age',async({page})=>{const api=await authorized(admin);const create=await api.post('/api/v1/tracking/devices',{data:{externalDeviceReference:`stale-${suffix}`,providerAlias:provider,hardwareSerialReference:`stale-serial-${suffix}`}});expect(create.status(),await create.text()).toBe(201);let staleDevice=await create.json() as Device;const binding=await api.post(`/api/v1/tracking/devices/${staleDevice.id}/provider-bindings`,{data:{providerConnectionId:fixtureConnectionId,externalDeviceReference:`stale-${suffix}`,safeConfiguration:{},lifecycle:'ACTIVE'}});expect(binding.status(),await binding.text()).toBe(201);let staleAssociation:Association|undefined;for(const candidate of vehicleCandidates.filter(id=>id!==vehicleA)){const response=await api.post(`/api/v1/tracking/devices/${staleDevice.id}/associations`,{data:{vehicleId:candidate,effectiveFrom:new Date(Date.now()-20*60_000).toISOString()}});if(response.status()===201){staleVehicle=candidate;staleAssociation=await response.json() as Association;break;}}expect(staleVehicle).toBeTruthy();staleDevice=await json<Device>(api.get(`/api/v1/tracking/devices/${staleDevice.id}`));const activate=await api.post(`/api/v1/tracking/devices/${staleDevice.id}/activate`,{data:{version:staleDevice.version}});expect(activate.status(),await activate.text()).toBe(200);staleDevice=await activate.json() as Device;await send(staleDevice.id,'stale',1,new Date(Date.now()-10*60_000).toISOString(),6.928);await authenticate(page,admin);await page.goto('/tracking/vehicles');await expect(page.getByText('LAST KNOWN',{exact:true}).first()).toBeVisible();await expect(page.getByText(/s ago/).first()).toBeVisible();const ended=await api.post(`/api/v1/tracking/devices/${staleDevice.id}/associations/${staleAssociation!.id}/end`,{data:{effectiveTo:new Date().toISOString()}});expect(ended.status(),await ended.text()).toBe(200);await api.dispose();});
 test('7/10 reassigns by source time without re-parenting old history',async()=>{const api=await authorized(admin);const boundary=new Date().toISOString();let response=await api.post(`/api/v1/tracking/devices/${device.id}/associations/${association.id}/end`,{data:{effectiveTo:boundary}});expect(response.status(),await response.text()).toBe(200);for(const candidate of vehicleCandidates.filter(id=>id!==vehicleA)){response=await api.post(`/api/v1/tracking/devices/${device.id}/associations`,{data:{vehicleId:candidate,effectiveFrom:boundary}});if(response.status()===201){vehicleB=candidate;break;}}expect(vehicleB).toBeTruthy();await new Promise(resolve=>setTimeout(resolve,5));const point=await send(device.id,'reassigned',7,new Date().toISOString(),6.929);expect(point.vehicleId).toBe(vehicleB);const old=await history(api,vehicleA);expect(old.items.some(item=>item.providerMessageId===newest.providerMessageId)).toBe(true);await api.dispose();});
 test('8/10 denies limited history and hides guessed cross-Tenant resources',async()=>{const limitedApi=await authorized(limited);expect((await limitedApi.get(`/api/v1/tracking/vehicles/${vehicleA}/positions?from=${encodeURIComponent(new Date(Date.now()-3600_000).toISOString())}&to=${encodeURIComponent(new Date().toISOString())}`)).status()).toBe(403);const other=await authorized(tenantB);const hidden=await other.get(`/api/v1/tracking/devices/${device.id}`);expect(hidden.status(),await hidden.text()).toBe(404);await limitedApi.dispose();await other.dispose();});
 test('9/10 masks device references and exposes no credential material',async()=>{const api=await authorized(limited);const devices=await json<Device[]>(api.get('/api/v1/tracking/devices'));const visible=devices.find(item=>item.id===device.id)!;expect(visible.externalReference).toMatch(/^\*\*\*\*/);expect(visible).not.toHaveProperty('secret');expect(visible).not.toHaveProperty('credentialReference');await api.dispose();});
 test('10/10 bounds and orders 24-hour history',async()=>{const api=await authorized(admin);const page=await history(api,vehicleB);expect(page.items.length).toBeGreaterThan(0);expect(page.items.map(item=>Date.parse(item.sourceTimestamp))).toEqual([...page.items.map(item=>Date.parse(item.sourceTimestamp))].sort((a,b)=>b-a));const tooWide=await api.get(`/api/v1/tracking/vehicles/${vehicleB}/positions?from=${encodeURIComponent(new Date(Date.now()-25*3600_000).toISOString())}&to=${encodeURIComponent(new Date().toISOString())}`);expect(tooWide.status()).toBe(400);await api.dispose();});

 async function send(deviceId:string,message:string,sequence:number,sourceTimestamp:string,latitude:number){const providerMessageId=`${message}-${suffix}`;const response=await signed({deviceId,providerMessageId,providerSequence:sequence,sourceTimestamp,latitude,longitude:79.8612,horizontalAccuracyMeters:5});expect(response.status(),await response.text()).toBe(200);return (await response.json() as Array<{positionId:string;vehicleId:string;ordering:string}>).map(item=>({id:item.positionId,vehicleId:item.vehicleId,providerMessageId,sourceTimestamp,ordering:item.ordering}))[0];}
 async function signed(data:Record<string,unknown>){const body=JSON.stringify(data);const epoch=Math.floor(Date.now()/1000);const nonce=crypto.randomUUID();const signature=createHmac('sha256',secret).update(`${epoch}\n${nonce}\n${providerKeyId}\n${provider}\n${body}`).digest('hex');const api=await request.newContext({baseURL:backend});const response=await api.post('/api/integration/v1/tracking/positions',{headers:{'Content-Type':'application/json','X-Tracking-Provider-Key-Id':providerKeyId,'X-Tracking-Provider':provider,'X-Tracking-Timestamp':String(epoch),'X-Tracking-Nonce':nonce,'X-Tracking-Signature':signature},data:body});return response;}
 async function history(api:Awaited<ReturnType<typeof request.newContext>>,vehicle:string){const to=new Date();const from=new Date(to.getTime()-24*3600_000);return json<Page<Position>>(api.get(`/api/v1/tracking/vehicles/${vehicle}/positions?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}&limit=100`));}
});

async function login(username=process.env.E2E_ADMIN_USERNAME??'admin',password=process.env.E2E_ADMIN_PASSWORD??'AdminPass!2026'){const api=await request.newContext({baseURL:backend});const response=await api.post('/api/auth/login',{data:{username,password}});expect(response.status(),await response.text()).toBe(200);const auth=await response.json() as Auth;await api.dispose();return auth;}
function authorized(auth:Auth){return request.newContext({baseURL:backend,extraHTTPHeaders:{Authorization:`Bearer ${auth.accessToken}`}});}
async function json<T=unknown>(promise:Promise<import('@playwright/test').APIResponse>){const response=await promise;expect(response.status(),await response.text()).toBe(200);return response.json() as Promise<T>;}
function entities(value:unknown):Array<{id:string}>{if(Array.isArray(value))return value as Array<{id:string}>;return ((value as {content?:Array<{id:string}>}).content??[]);}
async function createUser(api:Awaited<ReturnType<typeof request.newContext>>,permissions:string[]){const role=await api.post('/api/roles',{data:{name:`US48 limited ${suffix}`,active:true,permissions}});expect(role.status(),await role.text()).toBe(201);const roleId=(await role.json() as {id:string}).id;const username=`us48-limited-${Date.now()}`;const password=`Us48Limited!${Date.now()}`;const user=await api.post('/api/users',{data:{username,email:`${username}@example.test`,password,firstName:'US48',lastName:'Limited',active:true,roleIds:[roleId]}});expect(user.status(),await user.text()).toBe(201);return login(username,password);}
async function authenticate(page:import('@playwright/test').Page,auth:Auth){await page.addInitScript(value=>{localStorage.setItem('transport.accessToken',value.accessToken);localStorage.setItem('transport.refreshToken',value.refreshToken);},auth);}
