import { expect, request, test } from '@playwright/test';

const backend=process.env.REAL_E2E_BACKEND_URL??'http://localhost:8088';const suffix=`cs08-${Date.now()}`;
type Auth={accessToken:string;refreshToken:string};type Connection={id:string;displayName:string;lifecycle:string;testStatus:string;credentialConfigured:boolean;safeConfiguration:Record<string,string>;version:number};type ConnectionPage={items:Connection[]};

test.describe.serial('US-48 CS08 provider connections real PostgreSQL journey',()=>{
 let admin:Auth;let limited:Auth;let connection:Connection;
 test.beforeAll(async()=>{admin=await login();const api=await authorized(admin);limited=await createUser(api,['TRACKING_VIEW']);await api.dispose();});
 test('1/10 authorized operator opens Provider Connections',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');await expect(page.getByRole('heading',{name:'Provider Connections'})).toHaveCount(1);await expect(page.getByRole('button',{name:/Add Provider Connection/}).first()).toBeVisible();});
 test('2/10 installed provider types come from CS06',async()=>{const api=await authorized(admin);const response=await api.get('/api/v1/tracking/provider-types');expect(response.status(),await response.text()).toBe(200);const types=await response.json() as Array<{providerType:string;supported:boolean}>;expect(types.some(item=>item.providerType==='FLESPI'&&item.supported)).toBe(true);await api.dispose();});
 test('3/10 creates a DRAFT connection through the UI',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');await page.getByRole('button',{name:/Add Provider Connection/}).first().click();await page.getByLabel('Provider type').press('ArrowDown');await page.getByLabel('Provider type').press('Enter');await page.getByLabel('Display name').fill(`CS08 ${suffix}`);await page.getByLabel('Provider alias').fill(`CS08_${Date.now()}`);await page.getByLabel('Provider key ID').fill(`cs08-key-${suffix}`);await page.getByLabel('Endpoint URI').fill('https://flespi.io');await page.getByLabel('Credential reference').fill('env:US48_FIXTURE_SECRET');await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText('Draft provider connection created')).toBeVisible();const api=await authorized(admin);const list=await json<ConnectionPage>(api.get('/api/v1/tracking/provider-connections?page=0&size=100'));connection=list.items.find(item=>item.displayName===`CS08 ${suffix}`)!;expect(connection.lifecycle).toBe('DRAFT');expect(connection.credentialConfigured).toBe(true);expect(connection).not.toHaveProperty('credentialReference');await api.dispose();});
 test('4/10 lists safe connection data without credential material',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');const row=page.getByRole('row',{name:new RegExp(`CS08 ${suffix}`)});await expect(row).toContainText('Configured');await expect(page.getByText('env:US48_FIXTURE_SECRET')).toHaveCount(0);});
 test('5/10 renders a controlled safe Test Connection PASS result',async({page})=>{await page.route(`**/api/v1/tracking/provider-connections/${connection.id}/test`,async route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({connection:{...connection,testStatus:'PASS'},status:'PASS',detailCode:'CONNECTION_OK'})}));await authenticate(page,admin);await page.goto('/tracking/provider-connections');await page.getByRole('row',{name:new RegExp(`CS08 ${suffix}`)}).getByRole('button',{name:/Test Connection/}).click();await expect(page.getByText('Connection successful')).toBeVisible();});
 test('6/10 activates then disables through optimistic lifecycle commands',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');const row=page.getByRole('row',{name:new RegExp(`CS08 ${suffix}`)});await row.getByRole('button',{name:'Activate'}).click();await page.getByRole('dialog').getByRole('button',{name:'Activate',exact:true}).click();await expect(row).toContainText('ACTIVE');await row.getByRole('button',{name:'Disable'}).click();await page.getByRole('dialog').getByRole('button',{name:'Disable',exact:true}).click();await expect(row).toContainText('DISABLED');});
 test('7/10 updates safe configuration while preserving the credential',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');await page.getByRole('row',{name:new RegExp(`CS08 ${suffix}`)}).getByRole('button',{name:'Edit'}).click();await expect(page.getByLabel('Replacement credential reference')).toHaveValue('');await page.getByLabel('Safe configuration (JSON)').fill('{"overlapSeconds":"120"}');await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText('Provider connection updated')).toBeVisible();const api=await authorized(admin);connection=await json<Connection>(api.get(`/api/v1/tracking/provider-connections/${connection.id}`));expect(connection.safeConfiguration).toEqual({overlapSeconds:'120'});expect(connection.credentialConfigured).toBe(true);await api.dispose();});
 test('8/10 retires permanently with historical-data wording',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');const row=page.getByRole('row',{name:new RegExp(`CS08 ${suffix}`)});await row.getByRole('button',{name:'Retire'}).click();await expect(page.getByText(/action is permanent.*Historical Tracking data is preserved/i)).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Retire',exact:true}).click();await expect(row).toContainText('RETIRED');});
 test('9/10 terminal connection hides mutable actions',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/provider-connections');const row=page.getByRole('row',{name:new RegExp(`CS08 ${suffix}`)});await expect(row.getByRole('button',{name:'Edit'})).toHaveCount(0);await expect(row.getByRole('button',{name:/Test Connection/})).toHaveCount(0);await expect(row.getByRole('button',{name:'Activate'})).toHaveCount(0);});
 test('10/10 view-only role cannot manage or call CS06',async({page})=>{const api=await authorized(limited);expect((await api.get('/api/v1/tracking/provider-connections')).status()).toBe(403);await api.dispose();await authenticate(page,limited);await page.goto('/tracking/provider-connections');await expect(page).toHaveURL(/\/tracking\/vehicles$/);await expect(page.getByRole('button',{name:/Add Provider Connection/})).toHaveCount(0);});
});

async function login(username=process.env.E2E_ADMIN_USERNAME??'admin',password=process.env.E2E_ADMIN_PASSWORD??'AdminPass!2026'){const api=await request.newContext({baseURL:backend});const response=await api.post('/api/auth/login',{data:{username,password}});expect(response.status(),await response.text()).toBe(200);const auth=await response.json() as Auth;await api.dispose();return auth;}
function authorized(auth:Auth){return request.newContext({baseURL:backend,extraHTTPHeaders:{Authorization:`Bearer ${auth.accessToken}`}});}
async function json<T>(promise:Promise<import('@playwright/test').APIResponse>){const response=await promise;expect(response.status(),await response.text()).toBe(200);return response.json() as Promise<T>;}
async function createUser(api:Awaited<ReturnType<typeof request.newContext>>,permissions:string[]){const role=await api.post('/api/roles',{data:{name:`CS08 limited ${suffix}`,active:true,permissions}});expect(role.status(),await role.text()).toBe(201);const roleId=(await role.json() as {id:string}).id;const username=`cs08-limited-${Date.now()}`;const password=`Cs08Limited!${Date.now()}`;const user=await api.post('/api/users',{data:{username,email:`${username}@example.test`,password,firstName:'CS08',lastName:'Limited',active:true,roleIds:[roleId]}});expect(user.status(),await user.text()).toBe(201);return login(username,password);}
async function authenticate(page:import('@playwright/test').Page,auth:Auth){await page.addInitScript(value=>{localStorage.setItem('transport.accessToken',value.accessToken);localStorage.setItem('transport.refreshToken',value.refreshToken);},auth);}
