import {expect,request,test} from '@playwright/test';
import {seedRouteDeviationEvidence,type RouteDeviationFixture} from '../../utils/routeDeviationAcceptanceFixture';

const backend=process.env.REAL_E2E_BACKEND_URL??'http://localhost:8088',suffix=`us52-${Date.now()}`;
type Auth={accessToken:string;refreshToken:string};type Rule={id:string;routeId:string;routeVersion:string;toleranceMeters:number;lifecycle:string;ruleVersion:number;version:number};
let manager:Auth,viewer:Auth,eventViewer:Auth,reviewerA:Auth,reviewerB:Auth,tenantB:Auth,rule:Rule,fixture:RouteDeviationFixture;

test.describe.serial('US-52 route deviation operator frontend real PostgreSQL journey',()=>{
  test.beforeAll(async()=>{
    const bootstrap=await login();const root=await authorized(bootstrap);
    const tenantAResponse=await root.post('/api/e2e/tenant-fixtures',{data:{suffix:`${suffix}-a`}});expect(tenantAResponse.status(),await tenantAResponse.text()).toBe(201);
    const tenantA=await tenantAResponse.json() as {tenantId:string;username:string;password:string};manager=await login(tenantA.username,tenantA.password);
    const tenantBResponse=await root.post('/api/e2e/tenant-fixtures',{data:{suffix:`${suffix}-b`}});expect(tenantBResponse.status(),await tenantBResponse.text()).toBe(201);
    const other=await tenantBResponse.json() as {username:string;password:string};tenantB=await login(other.username,other.password);await root.dispose();
    const api=await authorized(manager);viewer=await createUser(api,['ROUTE_DEVIATION_VIEW']);eventViewer=await createUser(api,['ROUTE_DEVIATION_EVENT_VIEW']);reviewerA=await createUser(api,['ROUTE_DEVIATION_EVENT_VIEW','ROUTE_DEVIATION_APPROVE']);reviewerB=await createUser(api,['ROUTE_DEVIATION_EVENT_VIEW','ROUTE_DEVIATION_APPROVE']);
    const routeId=crypto.randomUUID();const created=await api.post('/api/v1/tracking/route-deviations/rules',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{routeId,routeVersion:'REVISION:1',toleranceMeters:100}});expect(created.status(),await created.text()).toBe(201);rule=await created.json() as Rule;
    const activated=await api.post(`/api/v1/tracking/route-deviations/rules/${rule.id}/activate`,{headers:{'Idempotency-Key':crypto.randomUUID()},data:{expectedVersion:rule.version}});expect(activated.status(),await activated.text()).toBe(200);rule=await activated.json() as Rule;
    fixture=seedRouteDeviationEvidence(tenantA.tenantId,rule.id,routeId);await api.dispose();
  });

  test('1/10 manager creates, activates and reads a rule through the operator UI',async({page})=>{await authenticate(page,manager);await page.goto(`/tracking/route-deviations/rules/${rule.id}`);await expect(page.getByText('ACTIVE',{exact:true})).toBeVisible();await expect(page.getByText('REVISION:1',{exact:true})).toBeVisible();await expect(page.getByText('100 m')).toBeVisible();});
  test('2/10 VIEW-only user reads state and rule but cannot manage',async({page})=>{const api=await authorized(viewer);const denied=await api.post('/api/v1/tracking/route-deviations/rules',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{routeId:crypto.randomUUID(),routeVersion:'REVISION:1',toleranceMeters:100}});expect(denied.status()).toBe(403);await api.dispose();await authenticate(page,viewer);await page.goto('/tracking/route-deviations');await expect(page.getByText(`${rule.routeId} / REVISION:1`)).toBeVisible();await expect(page.getByRole('button',{name:'Create route-deviation rule'})).toHaveCount(0);await page.goto('/tracking/route-deviations/states');await expect(page.getByRole('row',{name:new RegExp(fixture.vehicleId)})).toContainText('DEVIATING');});
  test('3/10 EVENT_VIEW without APPROVE cannot review',async({page})=>{await authenticate(page,eventViewer);await page.goto(`/tracking/route-deviations/episodes/${fixture.highApproveId}`);await expect(page.getByText('HIGH',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Review HIGH episode'})).toHaveCount(0);});
  test('4/10 authorized reviewer approves a HIGH episode',async({page})=>{await authenticate(page,reviewerA);await page.goto(`/tracking/route-deviations/episodes/${fixture.highApproveId}`);await page.getByRole('button',{name:'Review HIGH episode'}).click();await page.getByRole('button',{name:'Submit review'}).click();await expect(page.getByText('APPROVED',{exact:true})).toBeVisible();});
  test('5/10 same reviewer cannot reverse their own decision',async({page})=>{await authenticate(page,reviewerA);await page.goto(`/tracking/route-deviations/episodes/${fixture.highApproveId}`);await expect(page.getByText(/different authorized reviewer is required/i)).toBeVisible();await expect(page.getByRole('button',{name:'Append review correction'})).toHaveCount(0);});
  test('6/10 second reviewer appends a compensating correction',async({page})=>{await authenticate(page,reviewerB);await page.goto(`/tracking/route-deviations/episodes/${fixture.highApproveId}`);await page.getByRole('button',{name:'Append review correction'}).click();const dialog=page.getByRole('dialog',{name:'Append review correction'});await page.getByLabel('Decision').first().click();await page.getByText('REJECTED',{exact:true}).last().click();await dialog.getByText('Append review correction',{exact:true}).click();await dialog.getByRole('button',{name:'Append correction'}).click();await expect(dialog).toBeHidden();const history=page.getByRole('table',{name:'Immutable route deviation review history'});await expect(history.getByRole('cell',{name:'REJECTED'})).toBeVisible();await expect(history.getByRole('row')).toHaveCount(3);});
  test('7/10 UNKNOWN reason requires a safe note before rejection',async({page})=>{await authenticate(page,reviewerA);await page.goto(`/tracking/route-deviations/episodes/${fixture.highRejectId}`);await page.getByRole('button',{name:'Review HIGH episode'}).click();const dialog=page.getByRole('dialog',{name:'Review HIGH deviation'});await page.getByLabel('Decision').first().click();await page.getByText('REJECTED',{exact:true}).last().click();await dialog.getByText('Review HIGH deviation',{exact:true}).click();await page.getByLabel('Review reason').first().click();await page.getByText('UNKNOWN',{exact:true}).last().click();await dialog.getByText('Review HIGH deviation',{exact:true}).click();await dialog.getByRole('button',{name:'Submit review'}).click();await expect(dialog.getByText(/at least 10 characters/i)).toBeVisible();await dialog.getByLabel('Review note').fill('Controlled acceptance reason');await dialog.getByRole('button',{name:'Submit review'}).click();await expect(dialog).toBeHidden();await expect(page.getByRole('table',{name:'Immutable route deviation review history'}).getByRole('cell',{name:'REJECTED'})).toBeVisible();});
  test('8/10 bounded keyset history filters and navigates without coordinates',async({page})=>{await authenticate(page,eventViewer);await page.goto('/tracking/route-deviations/episodes');const history=page.getByRole('table',{name:'Route deviation episode history'});await expect(history).toBeVisible();await expect(page.getByRole('button',{name:'Next history page'})).toBeEnabled();await page.getByRole('button',{name:'Next history page'}).click();await expect(page.getByRole('button',{name:'Previous history page'})).toBeEnabled();await page.getByLabel('Severity filter').first().click();await page.getByText('HIGH',{exact:true}).last().click();await page.getByRole('heading',{name:'Route Deviations'}).click();await expect(page.getByRole('button',{name:'Previous history page'})).toBeDisabled();expect(await history.innerText()).not.toMatch(/latitude|longitude|geometry|provider|device/i);});
  test('9/10 Tenant boundary returns safe 404 for rule and episode',async()=>{const api=await authorized(tenantB);expect((await api.get(`/api/v1/tracking/route-deviations/rules/${rule.id}`)).status()).toBe(404);expect((await api.get(`/api/v1/tracking/route-deviations/episodes/${fixture.highApproveId}`)).status()).toBe(404);await api.dispose();});
  test('10/10 unauthorized deep link is guarded and tablet layout remains usable',async({page})=>{await authenticate(page,viewer);await page.setViewportSize({width:768,height:1024});await page.goto(`/tracking/route-deviations/episodes/${fixture.warningId}`);await expect(page).toHaveURL(/\/$/);await expect(page.locator('body')).not.toContainText(fixture.warningId);});
});

async function login(username=process.env.E2E_ADMIN_USERNAME??'admin',password=process.env.E2E_ADMIN_PASSWORD??'AdminPass!2026'){const api=await request.newContext({baseURL:backend});const response=await api.post('/api/auth/login',{data:{username,password}});expect(response.status(),await response.text()).toBe(200);const auth=await response.json() as Auth;await api.dispose();return auth;}
function authorized(auth:Auth){return request.newContext({baseURL:backend,extraHTTPHeaders:{Authorization:`Bearer ${auth.accessToken}`}});}
async function createUser(api:Awaited<ReturnType<typeof request.newContext>>,permissions:string[]){const marker=`${Date.now()}-${Math.random().toString(16).slice(2)}`,roleResponse=await api.post('/api/roles',{data:{name:`US52 ${marker}`,active:true,permissions}});expect(roleResponse.status(),await roleResponse.text()).toBe(201);const roleId=(await roleResponse.json() as {id:string}).id,username=`us52-${marker}`,password=`Us52Viewer!${Date.now()}`;const userResponse=await api.post('/api/users',{data:{username,email:`${username}@example.test`,password,firstName:'US52',lastName:'Operator',active:true,roleIds:[roleId]}});expect(userResponse.status(),await userResponse.text()).toBe(201);return login(username,password);}
async function authenticate(page:import('@playwright/test').Page,auth:Auth){await page.addInitScript(value=>{localStorage.setItem('transport.accessToken',value.accessToken);localStorage.setItem('transport.refreshToken',value.refreshToken);},auth);}
