import {expect,request,test} from '@playwright/test';
const backend=process.env.REAL_E2E_BACKEND_URL??'http://localhost:8088',suffix=`us54-${Date.now()}`;
type Auth={accessToken:string;refreshToken:string};
let admin:Auth,dashboardOnly:Auth,unauthorized:Auth;

test.describe.serial('US-54 Tracking Dashboard CS04 real Chromium journey',()=>{
  test.describe.configure({timeout:90_000});
  test.beforeAll(async()=>{const root=await authorized(await login());const response=await root.post('/api/e2e/tenant-fixtures',{data:{suffix}});expect(response.status(),await response.text()).toBe(201);const fixture=await response.json() as {username:string;password:string};await root.dispose();admin=await login(fixture.username,fixture.password);const api=await authorized(admin);dashboardOnly=await createUser(api,['TRACKING_DASHBOARD_VIEW'],'dashboard');const api2=await authorized(admin);unauthorized=await createUser(api2,['TRACKING_VIEW'],'unauthorized')});
  test('1/6 exposes only permission-gated navigation and a body-query route',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/dashboard');await expect(page.getByRole('heading',{name:'Tracking Dashboard'})).toBeVisible();await expect(page.getByRole('menuitem',{name:'Tracking Dashboard'})).toBeVisible();expect(page.url()).not.toContain('vehicleId')});
  test('2/6 renders bounded table-first state and observed-motion wording',async({page})=>{await authenticate(page,admin);await page.goto('/tracking/dashboard');await expect(page.getByRole('table',{name:'Tracking dashboard Vehicle evidence'})).toBeVisible();await expect(page.getByText(/Motion is observed speed, not engine or idle state/)).toBeVisible();await expect(page.getByRole('button',{name:'Refresh'})).toBeVisible()});
  test('3/6 preserves producer acceptance labels without upgrading evidence',async({page})=>{const api=await authorized(admin);const response=await api.post('/api/v1/tracking/dashboard/query',{data:{includeHeatMap:true,includeIncidents:true,pageSize:100},timeout:40_000});expect(response.status(),await response.text()).toBe(200);const result=await response.json() as {producerStatuses:Record<string,string>};expect(result.producerStatuses['US-49']).toBe('ACCEPTED');expect(result.producerStatuses['US-50']).toBe('FIELD_FIDELITY_PENDING');await api.dispose();await authenticate(page,admin);await page.goto('/tracking/dashboard');await expect(page.getByText('Producer evidence labels')).toBeVisible();await expect(page.getByText(/Field acceptance pending|Field fidelity pending|Accepted|Unavailable/).first()).toBeVisible({timeout:40_000})});
  test('4/6 dashboard-only authority omits precise map coordinates',async({page})=>{const api=await authorized(dashboardOnly);const response=await api.post('/api/v1/tracking/dashboard/query',{data:{includeHeatMap:true,includeIncidents:true,pageSize:100}});expect(response.status(),await response.text()).toBe(200);const data=await response.json() as {vehicles:Array<{latestTrusted?:{latitude?:number;longitude?:number}}>};expect(data.vehicles.every(vehicle=>vehicle.latestTrusted?.latitude===undefined&&vehicle.latestTrusted?.longitude===undefined)).toBe(true);await api.dispose();await authenticate(page,dashboardOnly);await page.goto('/tracking/dashboard');await expect(page.getByRole('img',{name:'Fleet map with no authorized positions'})).toBeVisible()});
  test('5/6 literal API and deep link deny broad Tracking authority',async({page})=>{const api=await authorized(unauthorized);const response=await api.post('/api/v1/tracking/dashboard/query',{data:{includeHeatMap:false,includeIncidents:false,pageSize:100}});expect(response.status()).toBe(403);await api.dispose();await authenticate(page,unauthorized);await page.goto('/tracking/dashboard');await expect(page).toHaveURL(/\/$/);await expect(page.getByRole('table',{name:'Tracking dashboard Vehicle evidence'})).toHaveCount(0)});
  test('6/6 pauses offline polling and remains usable at phone width',async({page,context})=>{await page.setViewportSize({width:390,height:844});await authenticate(page,admin);await page.goto('/tracking/dashboard');await expect(page.getByRole('table',{name:'Tracking dashboard Vehicle evidence'})).toBeVisible();await context.setOffline(true);await expect(page.getByText('Dashboard polling paused while offline')).toBeVisible();await expect(page.getByRole('button',{name:'Refresh'})).toBeVisible();await context.setOffline(false)});
});

async function login(username=process.env.E2E_ADMIN_USERNAME??'admin',password=process.env.E2E_ADMIN_PASSWORD??'AdminPass!2026'){const api=await request.newContext({baseURL:backend});const response=await api.post('/api/auth/login',{data:{username,password}});expect(response.status(),await response.text()).toBe(200);const auth=await response.json() as Auth;await api.dispose();return auth}
function authorized(auth:Auth){return request.newContext({baseURL:backend,extraHTTPHeaders:{Authorization:`Bearer ${auth.accessToken}`}})}
async function createUser(api:Awaited<ReturnType<typeof request.newContext>>,permissions:string[],kind:string){const name=`US54 ${kind} ${suffix}`;const role=await api.post('/api/roles',{data:{name,active:true,permissions}});expect(role.status(),await role.text()).toBe(201);const roleId=(await role.json() as {id:string}).id,username=`us54-${kind}-${Date.now()}`,password=`Us54${kind}!${Date.now()}`;const user=await api.post('/api/users',{data:{username,email:`${username}@example.test`,password,firstName:'US54',lastName:kind,active:true,roleIds:[roleId]}});expect(user.status(),await user.text()).toBe(201);await api.dispose();return login(username,password)}
async function authenticate(page:import('@playwright/test').Page,auth:Auth){await page.addInitScript(value=>{localStorage.setItem('transport.accessToken',value.accessToken);localStorage.setItem('transport.refreshToken',value.refreshToken)},auth)}
