package com.transportlogistics.app.tracking.domain.journeyreplay;

public enum JourneyReplayError {
    INVALID_SELECTOR,
    INVALID_RANGE,
    RANGE_TOO_LARGE,
    INVALID_PAGE_SIZE,
    INVALID_CURSOR,
    CURSOR_QUERY_MISMATCH,
    UNSUPPORTED_OVERLAY,
    UNSUPPORTED_ENGINE_EVIDENCE,
    UNSUPPORTED_EXPORT,
    RETENTION_UNAVAILABLE,
    REPLAY_EVIDENCE_NOT_FOUND,
    SAFE_ABSENCE,
    ATTRIBUTION_UNAVAILABLE,
    REQUIRED_CAPABILITY_UNAVAILABLE,
    INVALID_COORDINATE,
    INVALID_COVERAGE,
    INSUFFICIENT_EVIDENCE,
    REPLAY_POINT_LIMIT_EXCEEDED,
    REPLAY_CURSOR_NOT_ADVANCING,
    REPLAY_CURSOR_EXPIRED,
    STOP_CURSOR_INVALID,
    STOP_CURSOR_EXPIRED
}
