package com.transportlogistics.app.tracking.adapters.outbound.persistence;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.transportlogistics.app.shared.domain.BusinessRuleException;
import com.transportlogistics.app.tracking.domain.TrackingModels.Association;
import com.transportlogistics.app.tracking.domain.TrackingModels.Connectivity;
import com.transportlogistics.app.tracking.domain.TrackingModels.Device;
import com.transportlogistics.app.tracking.domain.TrackingModels.DeviceLifecycle;
import com.transportlogistics.app.tracking.domain.TrackingModels.EngineState;
import com.transportlogistics.app.tracking.domain.TrackingModels.Freshness;
import com.transportlogistics.app.tracking.domain.TrackingModels.Observation;
import com.transportlogistics.app.tracking.domain.TrackingModels.Ordering;
import com.transportlogistics.app.tracking.domain.TrackingModels.State;
import com.transportlogistics.app.tracking.domain.TrackingModels.Trust;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.Associate;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.Context;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.CreateDevice;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.HistoryPage;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.IngestResult;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.PositionCommand;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.ProviderContext;
import com.transportlogistics.app.tracking.ports.inbound.TrackingUseCase.UpdateDevice;
import com.transportlogistics.app.tracking.ports.outbound.TrackingStore;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.*;
import java.time.*;
import java.util.*;
import org.springframework.dao.*;
import org.springframework.jdbc.core.*;
import org.springframework.stereotype.Component;
import org.springframework.transaction.support.TransactionTemplate;

@Component
class JdbcTrackingStore implements TrackingStore {
 private static final String POLICY="US48_DEFAULT"; private static final String POLICY_VERSION="1";
 private final JdbcTemplate jdbc; private final TransactionTemplate tx; private final ObjectMapper json;
 JdbcTrackingStore(JdbcTemplate jdbc,TransactionTemplate tx,ObjectMapper json){this.jdbc=jdbc;this.tx=tx;this.json=json;}

 @Override public Device insertDevice(Context c,CreateDevice x,Instant now){return tx.execute(s->{UUID id=UUID.randomUUID();jdbc.update("INSERT INTO tracking_device(id,tenant_id,external_device_reference,provider_alias,hardware_serial_reference,lifecycle,registered_at,registered_by,created_at,updated_at) VALUES(?,?,?,?,?,'ACTIVE',?,?,?,?)",id,c.tenantId(),x.externalDeviceReference().trim(),x.providerAlias().trim().toUpperCase(Locale.ROOT),blank(x.hardwareSerialReference()),Timestamp.from(now),c.actorId(),Timestamp.from(now),Timestamp.from(now));audit(c,"DEVICE_CREATED","DEVICE",id,null,now);return device(c.tenantId(),id).orElseThrow();});}
 @Override public Device updateDevice(Context c,UUID id,long version,UpdateDevice x,Instant now){int n=jdbc.update("UPDATE tracking_device SET external_device_reference=?,hardware_serial_reference=?,version=version+1,updated_at=? WHERE tenant_id=? AND id=? AND version=?",x.externalDeviceReference().trim(),blank(x.hardwareSerialReference()),Timestamp.from(now),c.tenantId(),id,version);changed(n);audit(c,"DEVICE_UPDATED","DEVICE",id,null,now);return device(c.tenantId(),id).orElseThrow();}
 @Override public Device lifecycle(Context c,UUID id,long version,DeviceLifecycle lifecycle,Instant now){int n=jdbc.update("UPDATE tracking_device SET lifecycle=?,version=version+1,updated_at=? WHERE tenant_id=? AND id=? AND version=?",lifecycle.name(),Timestamp.from(now),c.tenantId(),id,version);changed(n);audit(c,"DEVICE_"+lifecycle.name(),"DEVICE",id,null,now);return device(c.tenantId(),id).orElseThrow();}
 @Override public Optional<Device> device(UUID t,UUID id){return one("SELECT * FROM tracking_device WHERE tenant_id=? AND id=?",this::device,t,id);}
 @Override public List<Device> devices(UUID t,int page,int size){return jdbc.query("SELECT * FROM tracking_device WHERE tenant_id=? ORDER BY created_at DESC,id LIMIT ? OFFSET ?",this::device,t,size,page*size);}

 @Override public Association associate(Context c,UUID deviceId,Associate x,Instant now){return tx.execute(s->{lock(c.tenantId(),deviceId);lock(c.tenantId(),x.vehicleId());Device d=device(c.tenantId(),deviceId).orElseThrow(()->error("TRACKING_DEVICE_NOT_FOUND","Device not found"));if(d.lifecycle()!=DeviceLifecycle.ACTIVE)throw error("TRACKING_DEVICE_NOT_FOUND","Device is disabled");if(active("tracking_device_id",c.tenantId(),deviceId))throw error("TRACKING_DEVICE_ALREADY_ASSOCIATED","Device already has an active association");if(active("vehicle_id",c.tenantId(),x.vehicleId()))throw error("TRACKING_VEHICLE_ALREADY_ASSOCIATED","Vehicle already has an active association");try{UUID id=UUID.randomUUID();jdbc.update("INSERT INTO tracking_vehicle_device_assignment(id,tenant_id,tracking_device_id,vehicle_id,effective_from,created_at,created_by) VALUES(?,?,?,?,?,?,?)",id,c.tenantId(),deviceId,x.vehicleId(),Timestamp.from(x.effectiveFrom()),Timestamp.from(now),c.actorId());audit(c,"ASSOCIATION_STARTED","ASSOCIATION",id,null,now);return association(c.tenantId(),id).orElseThrow();}catch(DataIntegrityViolationException e){throw error("TRACKING_ASSOCIATION_CONFLICT","Association conflicts with existing history");}});}
 @Override public Association endAssociation(Context c,UUID deviceId,UUID associationId,Instant effectiveTo,Instant now){return tx.execute(s->{lock(c.tenantId(),deviceId);int n=jdbc.update("UPDATE tracking_vehicle_device_assignment SET effective_to=? WHERE tenant_id=? AND id=? AND tracking_device_id=? AND effective_to IS NULL AND effective_from<?",Timestamp.from(effectiveTo),c.tenantId(),associationId,deviceId,Timestamp.from(effectiveTo));if(n!=1)throw error("TRACKING_ASSOCIATION_CONFLICT","Active association not found or interval invalid");audit(c,"ASSOCIATION_ENDED","ASSOCIATION",associationId,null,now);return association(c.tenantId(),associationId).orElseThrow();});}

 @Override public List<IngestResult> ingest(ProviderContext p,List<PositionCommand> commands,Instant received){return tx.execute(s->{List<IngestResult> out=new ArrayList<>();for(PositionCommand c:commands)out.add(ingestOne(p,c,received));return out;});}
 private IngestResult ingestOne(ProviderContext p,PositionCommand c,Instant received){validate(c);lock(p.tenantId(),c.deviceId());device(p.tenantId(),c.deviceId()).filter(x->x.lifecycle()==DeviceLifecycle.ACTIVE&&x.providerAlias().equalsIgnoreCase(p.providerAlias())).orElseThrow(()->error("TRACKING_PROVIDER_UNAUTHORIZED","Provider/device mismatch"));Association a=associationAt(p.tenantId(),c.deviceId(),c.sourceTimestamp()).orElseThrow(()->error("TRACKING_DEVICE_NOT_ASSOCIATED","No association covers source time"));lock(p.tenantId(),a.vehicleId());String identity=identity(p,c);String payload=payloadHash(p,c);Optional<Observation> existing=one("SELECT * FROM tracking_position WHERE tenant_id=? AND dedupe_identity=?",this::observation,p.tenantId(),identity);if(existing.isPresent()){if(!existing.get().payloadHash().equals(payload))throw error("TRACKING_POSITION_CONFLICT","Identity already belongs to a different payload");return new IngestResult(existing.get().id(),existing.get().vehicleId(),identity,true,existing.get().trust(),existing.get().ordering());}
  Observation currentTrusted=one("SELECT p.* FROM tracking_vehicle_latest l JOIN tracking_position p ON p.id=l.latest_trusted_position_id AND p.tenant_id=l.tenant_id WHERE l.tenant_id=? AND l.vehicle_id=?",this::observation,p.tenantId(),a.vehicleId()).orElse(null);
  Duration age=Duration.between(c.sourceTimestamp(),received);Ordering order=age.compareTo(Duration.ofHours(24))>0?Ordering.LATE:c.sourceTimestamp().isAfter(received.plusSeconds(120))?Ordering.FUTURE:c.sourceTimestamp().isAfter(received)?Ordering.CLOCK_SKEW:currentTrusted!=null&&c.sourceTimestamp().isBefore(currentTrusted.sourceTimestamp())?Ordering.OUT_OF_ORDER:Ordering.IN_ORDER;
  Trust trust=order==Ordering.LATE||order==Ordering.FUTURE?Trust.UNTRUSTED:c.horizontalAccuracyMeters()==null?Trust.UNKNOWN:c.horizontalAccuracyMeters().compareTo(BigDecimal.valueOf(1000))<=0?Trust.TRUSTED:Trust.UNTRUSTED;String quality=c.horizontalAccuracyMeters()==null?"ACCURACY_UNKNOWN":trust==Trust.UNTRUSTED?"POOR_ACCURACY":"ACCEPTABLE";
  UUID id=UUID.randomUUID();String metadata;try{metadata=json.writeValueAsString(c.safeMetadata()==null?Map.of():c.safeMetadata());}catch(Exception e){throw error("TRACKING_POSITION_INVALID","Invalid safe metadata");}
  jdbc.update("INSERT INTO tracking_position(id,tenant_id,device_id,vehicle_id,provider_alias,provider_message_id,provider_sequence,dedupe_identity,payload_hash,source_timestamp,received_at,latitude,longitude,horizontal_accuracy_meters,speed_kph,heading_degrees,altitude_meters,engine_state,odometer_km,engine_hours,trust,quality,ordering_classification,retention_policy,retention_policy_version,retain_until,safe_metadata) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb)",id,p.tenantId(),c.deviceId(),a.vehicleId(),p.providerAlias(),blank(c.providerMessageId()),c.providerSequence(),identity,payload,Timestamp.from(c.sourceTimestamp()),Timestamp.from(received),c.latitude(),c.longitude(),c.horizontalAccuracyMeters(),c.speedKph(),c.headingDegrees(),c.altitudeMeters(),(c.engineState()==null?EngineState.UNKNOWN:c.engineState()).name(),c.odometerKm(),c.engineHours(),trust.name(),quality,order.name(),POLICY,POLICY_VERSION,null,metadata);
  jdbc.update("UPDATE tracking_device SET last_seen_at=GREATEST(COALESCE(last_seen_at,?),?),updated_at=? WHERE tenant_id=? AND id=?",Timestamp.from(received),Timestamp.from(received),Timestamp.from(received),p.tenantId(),c.deviceId());
  boolean advances=trust==Trust.TRUSTED&&order!=Ordering.OUT_OF_ORDER&&(currentTrusted==null||compare(c,identity,currentTrusted)>0);
  jdbc.update("INSERT INTO tracking_vehicle_latest(tenant_id,vehicle_id,latest_received_position_id,latest_trusted_position_id,last_successful_receipt_at,policy_version,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(tenant_id,vehicle_id) DO UPDATE SET latest_received_position_id=CASE WHEN (SELECT received_at FROM tracking_position WHERE id=EXCLUDED.latest_received_position_id) >= (SELECT received_at FROM tracking_position WHERE id=tracking_vehicle_latest.latest_received_position_id) THEN EXCLUDED.latest_received_position_id ELSE tracking_vehicle_latest.latest_received_position_id END,latest_trusted_position_id=COALESCE(EXCLUDED.latest_trusted_position_id,tracking_vehicle_latest.latest_trusted_position_id),last_successful_receipt_at=GREATEST(tracking_vehicle_latest.last_successful_receipt_at,EXCLUDED.last_successful_receipt_at),updated_at=EXCLUDED.updated_at,version=tracking_vehicle_latest.version+1",p.tenantId(),a.vehicleId(),id,advances?id:null,Timestamp.from(received),POLICY_VERSION,Timestamp.from(received));
  return new IngestResult(id,a.vehicleId(),identity,false,trust,order);
 }

 @Override public List<State> states(UUID t,int page,int size,Instant now){List<LatestRefs> refs=jdbc.query("SELECT vehicle_id,latest_received_position_id,latest_trusted_position_id,last_successful_receipt_at FROM tracking_vehicle_latest WHERE tenant_id=? ORDER BY updated_at DESC,vehicle_id LIMIT ? OFFSET ?",(rs,n)->new LatestRefs(uuid(rs,"vehicle_id"),uuid(rs,"latest_received_position_id"),uuid(rs,"latest_trusted_position_id"),instant(rs,"last_successful_receipt_at")),t,size,page*size);Set<UUID> ids=new LinkedHashSet<>();refs.forEach(r->{ids.add(r.received());if(r.trusted()!=null)ids.add(r.trusted());});Map<UUID,Observation> positions=positions(t,ids);return refs.stream().map(r->new State(r.vehicle(),positions.get(r.received()),positions.get(r.trusted()),fresh(positions.get(r.trusted()),r.receipt(),now),connect(r.receipt(),now),POLICY_VERSION,now)).toList();}
 @Override public Optional<State> state(UUID t,UUID vehicle,Instant now){return one("SELECT l.latest_received_position_id,l.latest_trusted_position_id,l.last_successful_receipt_at FROM tracking_vehicle_latest l WHERE l.tenant_id=? AND l.vehicle_id=?",(rs,n)->{Observation r=position(t,UUID.fromString(rs.getString(1))).orElseThrow();String trusted=rs.getString(2);Observation tr=trusted==null?null:position(t,UUID.fromString(trusted)).orElseThrow();Instant receipt=rs.getTimestamp(3).toInstant();return new State(vehicle,r,tr,fresh(tr,receipt,now),connect(receipt,now),POLICY_VERSION,now);},t,vehicle);}
 @Override public HistoryPage positions(UUID t,UUID vehicle,Instant from,Instant to,String cursor,int limit){Instant ct=null;UUID ci=null;if(cursor!=null&&!cursor.isBlank()){try{String[] x=new String(Base64.getUrlDecoder().decode(cursor),StandardCharsets.UTF_8).split("\\|");ct=Instant.parse(x[0]);ci=UUID.fromString(x[1]);}catch(Exception e){throw error("TRACKING_POSITION_INVALID","Invalid cursor");}}String sql="SELECT * FROM tracking_position WHERE tenant_id=? AND vehicle_id=? AND source_timestamp>=? AND source_timestamp<?"+(ct==null?"":" AND (source_timestamp<? OR (source_timestamp=? AND id<?))")+" ORDER BY source_timestamp DESC,id DESC LIMIT ?";List<Observation> rows=ct==null?jdbc.query(sql,this::observation,t,vehicle,Timestamp.from(from),Timestamp.from(to),limit+1):jdbc.query(sql,this::observation,t,vehicle,Timestamp.from(from),Timestamp.from(to),Timestamp.from(ct),Timestamp.from(ct),ci,limit+1);String next=null;if(rows.size()>limit){Observation last=rows.get(limit-1);next=Base64.getUrlEncoder().withoutPadding().encodeToString((last.sourceTimestamp()+"|"+last.id()).getBytes(StandardCharsets.UTF_8));rows=new ArrayList<>(rows.subList(0,limit));}return new HistoryPage(rows,next);}
 @Override public boolean reserveNonce(UUID t,String provider,String hash,Instant now,Instant expiry){jdbc.update("DELETE FROM tracking_ingest_nonce WHERE tenant_id=? AND expires_at<?",t,Timestamp.from(now));try{return jdbc.update("INSERT INTO tracking_ingest_nonce(tenant_id,provider_alias,nonce_hash,used_at,expires_at) VALUES(?,?,?,?,?)",t,provider,hash,Timestamp.from(now),Timestamp.from(expiry))==1;}catch(DuplicateKeyException e){return false;}}

 private Optional<Association> association(UUID t,UUID id){return one("SELECT * FROM tracking_vehicle_device_assignment WHERE tenant_id=? AND id=?",this::association,t,id);}
 private boolean active(String column,UUID tenant,UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM tracking_vehicle_device_assignment WHERE tenant_id=? AND "+column+"=? AND effective_to IS NULL)",Boolean.class,tenant,id));}
 private Optional<Association> associationAt(UUID t,UUID device,Instant source){return one("SELECT * FROM tracking_vehicle_device_assignment WHERE tenant_id=? AND tracking_device_id=? AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) ORDER BY effective_from DESC LIMIT 1",this::association,t,device,Timestamp.from(source),Timestamp.from(source));}
 private Optional<Observation> position(UUID t,UUID id){return one("SELECT * FROM tracking_position WHERE tenant_id=? AND id=?",this::observation,t,id);}
 private Map<UUID,Observation> positions(UUID tenant,Set<UUID> ids){if(ids.isEmpty())return Map.of();String placeholders=String.join(",",Collections.nCopies(ids.size(),"?"));List<Object> args=new ArrayList<>();args.add(tenant);args.addAll(ids);return jdbc.query("SELECT * FROM tracking_position WHERE tenant_id=? AND id IN ("+placeholders+")",this::observation,args.toArray()).stream().collect(java.util.stream.Collectors.toMap(Observation::id,java.util.function.Function.identity()));}
 @SuppressWarnings("PMD.UnusedFormalParameter") private Device device(ResultSet r,int n)throws SQLException{return new Device(uuid(r,"id"),uuid(r,"tenant_id"),r.getString("external_device_reference"),r.getString("provider_alias"),r.getString("hardware_serial_reference"),DeviceLifecycle.valueOf(r.getString("lifecycle")),instant(r,"registered_at"),uuid(r,"registered_by"),instant(r,"last_seen_at"),r.getLong("version"));}
 @SuppressWarnings("PMD.UnusedFormalParameter") private Association association(ResultSet r,int n)throws SQLException{return new Association(uuid(r,"id"),uuid(r,"tenant_id"),uuid(r,"tracking_device_id"),uuid(r,"vehicle_id"),instant(r,"effective_from"),instant(r,"effective_to"),instant(r,"created_at"),uuid(r,"created_by"));}
 @SuppressWarnings("PMD.UnusedFormalParameter") private Observation observation(ResultSet r,int n)throws SQLException{Map<String,String> m=Map.of();try{m=json.readValue(r.getString("safe_metadata"),new TypeReference<>(){});}catch(Exception ignored){}return new Observation(uuid(r,"id"),uuid(r,"tenant_id"),uuid(r,"device_id"),uuid(r,"vehicle_id"),r.getString("provider_alias"),r.getString("provider_message_id"),(Long)r.getObject("provider_sequence"),r.getString("dedupe_identity"),r.getString("payload_hash"),instant(r,"source_timestamp"),instant(r,"received_at"),r.getBigDecimal("latitude"),r.getBigDecimal("longitude"),r.getBigDecimal("horizontal_accuracy_meters"),r.getBigDecimal("speed_kph"),r.getBigDecimal("heading_degrees"),r.getBigDecimal("altitude_meters"),EngineState.valueOf(r.getString("engine_state")),r.getBigDecimal("odometer_km"),r.getBigDecimal("engine_hours"),Trust.valueOf(r.getString("trust")),r.getString("quality"),Ordering.valueOf(r.getString("ordering_classification")),r.getString("retention_policy"),r.getString("retention_policy_version"),instant(r,"retain_until"),m);}
 private void validate(PositionCommand c){if(c.deviceId()==null||c.sourceTimestamp()==null||bad(c.latitude(),-90,90)||bad(c.longitude(),-180,180)||badOptional(c.horizontalAccuracyMeters(),0,null)||badOptional(c.speedKph(),0,400d)||badOptional(c.headingDegrees(),0,359.999d)||badOptional(c.odometerKm(),0,null)||badOptional(c.engineHours(),0,null))throw error("TRACKING_POSITION_INVALID","Invalid normalized telemetry");}
 private static boolean bad(BigDecimal x,double min,double max){return x==null||x.compareTo(BigDecimal.valueOf(min))<0||x.compareTo(BigDecimal.valueOf(max))>0;}
 private static boolean badOptional(BigDecimal x,double min,Double max){return x!=null&&(x.compareTo(BigDecimal.valueOf(min))<0||(max!=null&&x.compareTo(BigDecimal.valueOf(max))>0));}
 private String identity(ProviderContext p,PositionCommand c){return sha(c.providerMessageId()!=null?p.tenantId()+"|"+p.providerAlias()+"|"+c.providerMessageId():p.tenantId()+"|"+c.deviceId()+"|"+c.sourceTimestamp()+"|"+c.latitude().toPlainString()+"|"+c.longitude().toPlainString()+"|"+c.providerSequence());}
 private String payloadHash(ProviderContext p,PositionCommand c){return sha(p.providerAlias()+"|"+c.toString());}
 private static String sha(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static int compare(PositionCommand candidate,String identity,Observation current){int source=candidate.sourceTimestamp().truncatedTo(java.time.temporal.ChronoUnit.MICROS).compareTo(current.sourceTimestamp());if(source!=0)return source;int sequence=Long.compare(candidate.providerSequence()==null?Long.MIN_VALUE:candidate.providerSequence(),current.providerSequence()==null?Long.MIN_VALUE:current.providerSequence());return sequence!=0?sequence:identity.compareTo(current.dedupeIdentity());}
 private void lock(UUID t,UUID d){jdbc.execute("SELECT pg_advisory_xact_lock(hashtextextended(?,0))",(PreparedStatementCallback<Void>)statement->{statement.setString(1,t+":"+d);statement.execute();return null;});}
 private void audit(Context c,String action,String type,UUID id,String detail,Instant now){jdbc.update("INSERT INTO tracking_audit_event(id,tenant_id,actor_id,action,target_type,target_id,safe_detail,occurred_at) VALUES(?,?,?,?,?,?,?,?)",UUID.randomUUID(),c.tenantId(),c.actorId(),action,type,id,detail,Timestamp.from(now));}
 private static void changed(int n){if(n!=1)throw error("TRACKING_STALE_VERSION","Resource missing or stale");}
 private static BusinessRuleException error(String c,String m){return new BusinessRuleException(c,m);}
 private static String blank(String x){return x==null||x.isBlank()?null:x.trim();}
 private static UUID uuid(ResultSet r,String c)throws SQLException{String x=r.getString(c);return x==null?null:UUID.fromString(x);}
 private static Instant instant(ResultSet r,String c)throws SQLException{Timestamp x=r.getTimestamp(c);return x==null?null:x.toInstant();}
 private static Freshness fresh(Observation t,Instant receipt,Instant now){if(t==null)return Freshness.UNKNOWN;Duration a=Duration.between(t.sourceTimestamp(),now),b=Duration.between(receipt,now);if(!a.isNegative()&&a.compareTo(Duration.ofSeconds(60))<=0&&b.compareTo(Duration.ofSeconds(60))<=0)return Freshness.LIVE;if(a.compareTo(Duration.ofMinutes(5))<=0)return Freshness.RECENT;return Freshness.STALE;}
 private static Connectivity connect(Instant receipt,Instant now){if(receipt==null)return Connectivity.UNKNOWN;Duration a=Duration.between(receipt,now);return a.compareTo(Duration.ofSeconds(60))<=0?Connectivity.CONNECTED:a.compareTo(Duration.ofMinutes(5))<=0?Connectivity.DEGRADED:Connectivity.OFFLINE;}
 private <T>Optional<T> one(String sql,RowMapper<T> mapper,Object...args){List<T>x=jdbc.query(sql,mapper,args);return x.stream().findFirst();}
 private record LatestRefs(UUID vehicle,UUID received,UUID trusted,Instant receipt){}
}
