INSERT INTO app_permission (code, description, active) VALUES
    ('VEHICLE_VIEW', 'View vehicles, categories, types, and vehicle documents', TRUE),
    ('VEHICLE_CREATE', 'Create vehicles, categories, and types', TRUE),
    ('VEHICLE_UPDATE', 'Update vehicles, categories, and types', TRUE),
    ('VEHICLE_STATUS_UPDATE', 'Deactivate vehicles, categories, and types', TRUE),
    ('VEHICLE_DOCUMENT_MANAGE', 'Create, update, and retire vehicle documents', TRUE),
    ('VEHICLE_AVAILABILITY_VIEW', 'View vehicle eligibility and availability', TRUE),
    ('DRIVER_VIEW', 'View drivers and driver licenses', TRUE),
    ('DRIVER_CREATE', 'Create drivers', TRUE),
    ('DRIVER_UPDATE', 'Update or deactivate drivers', TRUE),
    ('DRIVER_LICENSE_MANAGE', 'Create, update, and retire driver licenses', TRUE),
    ('DRIVER_AVAILABILITY_VIEW', 'View driver eligibility and availability', TRUE),
    ('ROUTE_VIEW', 'View routes and route stops', TRUE),
    ('ROUTE_CREATE', 'Create routes and route stops', TRUE),
    ('ROUTE_UPDATE', 'Update or deactivate routes and route stops', TRUE),
    ('TRIP_VIEW', 'View trips and trip history', TRUE),
    ('TRIP_CREATE', 'Create trip orders', TRUE),
    ('TRIP_UPDATE', 'Update draft trip orders', TRUE),
    ('TRIP_SUBMIT', 'Submit trip orders for approval', TRUE),
    ('TRIP_APPROVE', 'Approve submitted trip orders', TRUE),
    ('TRIP_REJECT', 'Reject submitted trip orders', TRUE),
    ('TRIP_ASSIGN_VEHICLE', 'Assign and unassign trip vehicles', TRUE),
    ('TRIP_ASSIGN_DRIVER', 'Assign and unassign trip drivers', TRUE),
    ('TRIP_ASSIGN_ROUTE', 'Assign and unassign trip routes', TRUE),
    ('TRIP_DISPATCH', 'Dispatch assigned trips', TRUE),
    ('TRIP_START', 'Start dispatched trips', TRUE),
    ('TRIP_COMPLETE', 'Complete trips in progress', TRUE),
    ('TRIP_CLOSE', 'Close completed trips', TRUE),
    ('TRIP_CANCEL', 'Cancel eligible trips', TRUE),
    ('REPORT_VIEW', 'View operational reports', TRUE),
    ('DASHBOARD_VIEW', 'View operational dashboards', TRUE);
