
export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    ME: '/api/auth/me',
    LOGOUT: '/api/auth/logout',
    REFRESH: '/api/auth/refresh',
  },
  FLEET: {
    VEHICLES: '/api/vehicles',
    CATEGORIES: '/api/vehicle-categories',
    TYPES: '/api/vehicle-types',
    DOCUMENTS: (vehicleId: string) => `/api/vehicles/${vehicleId}/documents`,
    READINGS: (vehicleId: string) => `/api/vehicles/${vehicleId}/readings`,
    READINGS_LATEST: (vehicleId: string) => `/api/vehicles/${vehicleId}/readings/latest`,
    MAINTENANCE: (vehicleId: string) => `/api/vehicles/${vehicleId}/maintenance-schedules`,
    MILEAGE: (vehicleId: string) => `/api/vehicles/${vehicleId}/mileage`,
  },
  DRIVERS: {
    DRIVERS: '/api/drivers',
    LICENSES: (driverId: string) => `/api/drivers/${driverId}/licenses`,
    VIOLATIONS: (driverId: string) => `/api/drivers/${driverId}/violations`,
    VIOLATION_PAYMENT: (driverId: string, violationId: string) => `/api/drivers/${driverId}/violations/${violationId}/payment`,
    PERFORMANCE: (driverId: string) => `/api/drivers/${driverId}/performance`,
    EXCEPTIONS: (driverId: string) => `/api/drivers/${driverId}/exceptions`,
  },
  ROUTES: {
    ROUTES: '/api/routes',
    ROUTE_DETAILS: (routeId: string) => `/api/routes/${routeId}`,
  },
  TRIPS: {
    TRIPS: '/api/trips',
    TRIP_DETAILS: (tripId: string) => `/api/trips/${tripId}`,
    ASSIGN_VEHICLE: (tripId: string) => `/api/trips/${tripId}/assign-vehicle`,
    ASSIGN_DRIVER: (tripId: string) => `/api/trips/${tripId}/assign-driver`,
    ASSIGN_ROUTE: (tripId: string) => `/api/trips/${tripId}/assign-route`,
    SUBMIT: (tripId: string) => `/api/trips/${tripId}/submit`,
    APPROVE: (tripId: string) => `/api/trips/${tripId}/approve`,
    REJECT: (tripId: string) => `/api/trips/${tripId}/reject`,
    DISPATCH: (tripId: string) => `/api/trips/${tripId}/dispatch`,
    START: (tripId: string) => `/api/trips/${tripId}/start`,
    COMPLETE: (tripId: string) => `/api/trips/${tripId}/complete`,
    CLOSE: (tripId: string) => `/api/trips/${tripId}/close`,
    CANCEL: (tripId: string) => `/api/trips/${tripId}/cancel`,
    STATUS_HISTORY: (tripId: string) => `/api/trips/${tripId}/status-history`,
    FUEL_COST: (tripId: string) => `/api/trips/${tripId}/fuel-cost`,
    RECALCULATE_FUEL_COST: (tripId: string) => `/api/trips/${tripId}/fuel-cost/recalculate`,
  },
  FUEL: {
    ISSUES: '/api/fuel-issues',
    ISSUE_DETAILS: (id: string) => `/api/fuel-issues/${id}`,
    APPROVE_ISSUE: (id: string) => `/api/fuel-issues/${id}/approve`,
    PURCHASES: '/api/fuel-purchases',
    PURCHASE_DETAILS: (id: string) => `/api/fuel-purchases/${id}`,
    RECEIVE_PURCHASE: (id: string) => `/api/fuel-purchases/${id}/receive`,
    BUNKER_TANKS: '/api/bunker-tanks',
    BUNKER_DETAILS: (id: string) => `/api/bunker-tanks/${id}`,
    DIP_READINGS: (id: string) => `/api/bunker-tanks/${id}/dip-readings`,
    TRANSFERS: (id: string) => `/api/bunker-tanks/${id}/transfers`,
    PRICES: '/api/fuel-prices',
  },
  MASTER_DATA: {
    CUSTOMERS: '/api/customers',
    DEPARTMENTS: '/api/departments',
    PROJECTS: '/api/projects',
    LOCATIONS: '/api/locations',
    VENDORS: '/api/vendors',
    FUEL_STATIONS: '/api/fuel-stations',
    USERS: '/api/users',
    ROLES: '/api/roles',
  },
  REPORTING: {
    DASHBOARD_OPERATIONS: '/api/dashboard/operations',
    TRIPS: '/api/reports/trips',
    DRIVER_ASSIGNMENTS: '/api/reports/driver-assignments',
    VEHICLE_UTILIZATION: '/api/reports/vehicle-utilization',
  },
};
