import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {routeDeviationApi} from '../api/routeDeviationApi';
import type {EpisodeFilters,RuleFilters,StateFilters} from '../types';
export const deviationKeys={rules:['tracking','route-deviations','rules'] as const,rule:(id:string)=>['tracking','route-deviations','rules',id] as const,states:['tracking','route-deviations','states'] as const,state:(id:string)=>['tracking','route-deviations','states',id] as const,episodes:['tracking','route-deviations','episodes'] as const,episode:(id:string)=>['tracking','route-deviations','episodes',id] as const,reviews:(id:string)=>['tracking','route-deviations','episodes',id,'reviews'] as const};
export const useDeviationRules=(filters:RuleFilters)=>useQuery({queryKey:[...deviationKeys.rules,filters],queryFn:()=>routeDeviationApi.rules(filters)});
export const useDeviationRule=(id?:string)=>useQuery({queryKey:deviationKeys.rule(id??''),queryFn:()=>routeDeviationApi.rule(id!),enabled:Boolean(id)});
export const useDeviationStates=(filters:StateFilters)=>useQuery({queryKey:[...deviationKeys.states,filters],queryFn:()=>routeDeviationApi.states(filters)});
export const useDeviationState=(id?:string)=>useQuery({queryKey:deviationKeys.state(id??''),queryFn:()=>routeDeviationApi.state(id!),enabled:Boolean(id)});
export const useDeviationEpisodes=(filters:EpisodeFilters,enabled=true)=>useQuery({queryKey:[...deviationKeys.episodes,filters],queryFn:()=>routeDeviationApi.episodes(filters),enabled});
export const useDeviationEpisode=(id?:string)=>useQuery({queryKey:deviationKeys.episode(id??''),queryFn:()=>routeDeviationApi.episode(id!),enabled:Boolean(id)});
export const useDeviationReviews=(id?:string)=>useQuery({queryKey:deviationKeys.reviews(id??''),queryFn:()=>routeDeviationApi.reviews(id!),enabled:Boolean(id)});
export function useDeviationMutations(){const cache=useQueryClient();const refreshRule=async(id?:string)=>{await cache.invalidateQueries({queryKey:deviationKeys.rules});if(id)await cache.invalidateQueries({queryKey:deviationKeys.rule(id)});};const refreshEpisode=async(id:string)=>{await cache.invalidateQueries({queryKey:deviationKeys.episode(id)});await cache.invalidateQueries({queryKey:deviationKeys.reviews(id)});await cache.invalidateQueries({queryKey:deviationKeys.episodes});};return {create:useMutation({mutationFn:routeDeviationApi.createRule,onSuccess:value=>refreshRule(value.id)}),update:useMutation({mutationFn:routeDeviationApi.updateRule,onSuccess:value=>refreshRule(value.id)}),command:useMutation({mutationFn:routeDeviationApi.command,onSuccess:value=>refreshRule(value.id)}),review:useMutation({mutationFn:routeDeviationApi.review,onSuccess:value=>refreshEpisode(value.episodeId)}),correct:useMutation({mutationFn:routeDeviationApi.correctReview,onSuccess:value=>refreshEpisode(value.episodeId)})};}
